syntax = "proto3";

package org.apache.airavata.api.groupprofile;

option java_package = "org.apache.airavata.api.groupprofile";
option java_multiple_files = true;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "org/apache/airavata/model/appcatalog/groupresourceprofile/group_resource_profile.proto";
import "org/apache/airavata/model/appcatalog/gatewaygroups/gateway_groups.proto";
import "org/apache/airavata/model/commons/commons.proto";


// A GroupResourceProfile unioned with the caller's access flags (see commons.AccessFlags).
message GroupResourceProfileWithAccess {
  org.apache.airavata.model.appcatalog.groupresourceprofile.GroupResourceProfile group_resource_profile = 1;
  org.apache.airavata.model.commons.AccessFlags access = 2;
}