source "https://rubygems.org"

# Specify your gem's dependencies in airavata-ruby-sdk.gemspec
gemspec

gem "rake", "~> 12.0"
gem "rspec", "~> 3.0"

gem "httparty", "~> 0.18.1"

gem "thrift", "~> 0.13.0"
