-- profile service
--- disable foreign key checks in MySQL/MariaDB
SET FOREIGN_KEY_CHECKS=0;
update GATEWAY set REQUESTER_USERNAME = lower(REQUESTER_USERNAME);
update USER_PROFILE set AIRAVATA_INTERNAL_USER_ID = lower(AIRAVATA_INTERNAL_USER_ID), USER_ID = lower(USER_ID);
update USER_PROFILE_EMAIL set AIRAVATA_INTERNAL_USER_ID = lower(AIRAVATA_INTERNAL_USER_ID);
update USER_PROFILE_PHONE set AIRAVATA_INTERNAL_USER_ID = lower(AIRAVATA_INTERNAL_USER_ID);
SET FOREIGN_KEY_CHECKS=1;