# Generated by Django 3.2.15 on 2022-11-18 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_auth', '0018_merge_0014_auto_20220217_2255_0017_auto_20220616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.IntegerField(choices=[(1, 'Verify Email Template'), (2, 'New User Email Template'), (3, 'Password Reset Email Template'), (4, 'User Added to Group Template'), (5, 'Verify Email Change Template'), (6, 'User Profile Completed Template')], primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='extendeduserprofilevalue',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile_values', to='django_airavata_auth.userprofile'),
        ),
    ]
