/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * Apache Airavata - Unified Database Schema
 * 
 * This baseline schema represents the consolidated, entity-matched database structure.
 * All tables match their corresponding JPA entity definitions.
 */

-- ============================================================================
-- CORE UNIFIED ENTITIES
-- ============================================================================

-- GATEWAY - Unified gateway entity (formerly split across profile and experiment catalog)
CREATE TABLE IF NOT EXISTS GATEWAY (
    AIRAVATA_INTERNAL_GATEWAY_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) UNIQUE,
    GATEWAY_NAME VARCHAR(255),
    GATEWAY_DOMAIN VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    GATEWAY_APPROVAL_STATUS VARCHAR(50),
    GATEWAY_ACRONYM VARCHAR(255),
    GATEWAY_URL VARCHAR(255),
    GATEWAY_PUBLIC_ABSTRACT TEXT,
    GATEWAY_REVIEW_PROPOSAL_DESCRIPTION TEXT,
    GATEWAY_ADMIN_FIRST_NAME VARCHAR(255),
    GATEWAY_ADMIN_LAST_NAME VARCHAR(255),
    GATEWAY_ADMIN_EMAIL VARCHAR(255),
    DECLINED_REASON TEXT,
    REQUEST_CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REQUESTER_USERNAME VARCHAR(255),
    -- Domain fields (merged from sharing DOMAIN table)
    DOMAIN_DESCRIPTION TEXT,
    DOMAIN_CREATED_TIME BIGINT,
    LAST_UPDATED_TIME BIGINT,
    INITIAL_USER_GROUP_ID VARCHAR(255),
    PRIMARY KEY (AIRAVATA_INTERNAL_GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_gateway_id ON GATEWAY(GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_gateway_approval_status ON GATEWAY(GATEWAY_APPROVAL_STATUS);

-- AIRAVATA_USER - User entity storing only OpenID Connect scope fields
-- Additional user profile data should be fetched from the identity provider (Keycloak)
CREATE TABLE IF NOT EXISTS AIRAVATA_USER (
    -- Internal composite ID: userId@gatewayId
    AIRAVATA_INTERNAL_USER_ID VARCHAR(512) NOT NULL,
    -- OIDC 'openid' scope
    SUB VARCHAR(255) NOT NULL,                    -- OIDC subject identifier (user ID)
    GATEWAY_ID VARCHAR(255) NOT NULL,             -- Airavata gateway context
    -- OIDC 'profile' scope
    GIVEN_NAME VARCHAR(255),                      -- given_name claim
    FAMILY_NAME VARCHAR(255),                     -- family_name claim
    PREFERRED_USERNAME VARCHAR(255),              -- preferred_username claim
    PICTURE_URL VARCHAR(1024),                    -- picture claim (URL)
    ZONEINFO VARCHAR(100),                        -- zoneinfo claim (timezone)
    LOCALE VARCHAR(50),                           -- locale claim
    -- OIDC 'email' scope
    EMAIL VARCHAR(255),                           -- email claim
    EMAIL_VERIFIED BOOLEAN,                       -- email_verified claim
    -- Timestamps
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT BIGINT,                            -- OIDC updated_at claim (seconds since epoch)
    PRIMARY KEY (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_user_sub ON AIRAVATA_USER(SUB);
CREATE INDEX IF NOT EXISTS idx_user_gateway_id ON AIRAVATA_USER(GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_user_sub_gateway_id ON AIRAVATA_USER(SUB, GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_user_email ON AIRAVATA_USER(EMAIL);

-- ============================================================================
-- UNIFIED DATA TRACKING ENTITIES
-- ============================================================================

-- STATUS - Unified status tracking for all entity types
-- Entity uses composite PK: (STATUS_ID, PARENT_ID, PARENT_TYPE)
CREATE TABLE IF NOT EXISTS STATUS (
    STATUS_ID VARCHAR(255) NOT NULL,
    PARENT_ID VARCHAR(255) NOT NULL,
    PARENT_TYPE VARCHAR(50) NOT NULL,
    STATE VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    REASON LONGTEXT,
    SEQUENCE_NUM BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (STATUS_ID, PARENT_ID(100), PARENT_TYPE),
    INDEX idx_status_parent (PARENT_ID, PARENT_TYPE),
    INDEX idx_status_time (TIME_OF_STATE_CHANGE),
    INDEX idx_status_state (STATE),
    INDEX idx_status_sequence (SEQUENCE_NUM),
    -- Performance optimization: Efficient lookup for latest status queries
    INDEX idx_status_parent_sequence (PARENT_ID, PARENT_TYPE, SEQUENCE_NUM DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ERROR - Unified error tracking for all entity types
-- Entity uses composite PK: (ERROR_ID, PARENT_ID, PARENT_TYPE)
CREATE TABLE IF NOT EXISTS ERROR (
    ERROR_ID VARCHAR(255) NOT NULL,
    PARENT_ID VARCHAR(255) NOT NULL,
    PARENT_TYPE VARCHAR(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACTUAL_ERROR_MESSAGE LONGTEXT,
    USER_FRIENDLY_MESSAGE LONGTEXT,
    TRANSIENT_OR_PERSISTENT BOOLEAN,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, PARENT_ID(100), PARENT_TYPE),
    INDEX idx_error_parent (PARENT_ID, PARENT_TYPE),
    INDEX idx_error_creation_time (CREATION_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- INPUT_DATA - Unified input data for experiments, processes, applications, handlers
-- Entity uses composite PK: (PARENT_ID, PARENT_TYPE, INPUT_NAME)
CREATE TABLE IF NOT EXISTS INPUT_DATA (
    PARENT_ID VARCHAR(255) NOT NULL,
    PARENT_TYPE VARCHAR(50) NOT NULL,
    INPUT_NAME VARCHAR(255) NOT NULL,
    INPUT_VALUE LONGTEXT,
    DATA_TYPE VARCHAR(50),
    APPLICATION_ARGUMENT VARCHAR(255),
    STANDARD_INPUT BOOLEAN,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    METADATA VARCHAR(4096),
    INPUT_ORDER INT,
    IS_REQUIRED BOOLEAN,
    REQUIRED_TO_ADDED_TO_CMD BOOLEAN,
    DATA_STAGED BOOLEAN,
    STORAGE_RESOURCE_ID VARCHAR(255),
    IS_READ_ONLY BOOLEAN,
    OVERRIDE_FILENAME VARCHAR(255),
    PRIMARY KEY (PARENT_ID(100), PARENT_TYPE, INPUT_NAME(100)),
    INDEX idx_input_parent (PARENT_ID, PARENT_TYPE),
    INDEX idx_input_name (INPUT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OUTPUT_DATA - Unified output data for experiments, processes, applications, handlers
-- Entity uses composite PK: (PARENT_ID, PARENT_TYPE, OUTPUT_NAME)
CREATE TABLE IF NOT EXISTS OUTPUT_DATA (
    PARENT_ID VARCHAR(255) NOT NULL,
    PARENT_TYPE VARCHAR(50) NOT NULL,
    OUTPUT_NAME VARCHAR(255) NOT NULL,
    OUTPUT_VALUE LONGTEXT,
    DATA_TYPE VARCHAR(50),
    APPLICATION_ARGUMENT VARCHAR(255),
    IS_REQUIRED BOOLEAN,
    REQUIRED_TO_ADDED_TO_CMD BOOLEAN,
    DATA_MOVEMENT BOOLEAN,
    LOCATION VARCHAR(255),
    SEARCH_QUERY VARCHAR(255),
    OUTPUT_STREAMING BOOLEAN,
    STORAGE_RESOURCE_ID VARCHAR(255),
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    METADATA VARCHAR(4096),
    OUTPUT_ORDER INT,
    PRIMARY KEY (PARENT_ID(100), PARENT_TYPE, OUTPUT_NAME(100)),
    INDEX idx_output_parent (PARENT_ID, PARENT_TYPE),
    INDEX idx_output_name (OUTPUT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- METADATA - Unified metadata for data products, replicas, etc.
-- Entity uses composite PK: (PARENT_TYPE, PARENT_ID, METADATA_KEY)
CREATE TABLE IF NOT EXISTS METADATA (
    PARENT_TYPE VARCHAR(50) NOT NULL,
    PARENT_ID VARCHAR(255) NOT NULL,
    METADATA_KEY VARCHAR(255) NOT NULL,
    METADATA_VALUE LONGTEXT,
    VALUE_TYPE VARCHAR(50),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PARENT_TYPE, PARENT_ID(150), METADATA_KEY(100)),
    INDEX idx_metadata_parent (PARENT_TYPE, PARENT_ID),
    INDEX idx_metadata_key (METADATA_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- RESOURCE MANAGEMENT ENTITIES
-- ============================================================================

-- RESOURCE_PROFILE - Unified resource profile (gateway and user)
-- Entity uses composite PK: (PROFILE_ID, PROFILE_TYPE)
CREATE TABLE IF NOT EXISTS RESOURCE_PROFILE (
    PROFILE_ID VARCHAR(255) NOT NULL,
    PROFILE_TYPE VARCHAR(50) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    CREDENTIAL_STORE_TOKEN VARCHAR(255),
    IDENTITY_SERVER_PWD_CRED_TOKEN VARCHAR(255),
    IDENTITY_SERVER_TENANT VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PROFILE_ID, PROFILE_TYPE),
    INDEX idx_resource_profile_gateway (GATEWAY_ID),
    INDEX idx_resource_profile_type (PROFILE_TYPE),
    INDEX idx_resource_profile_gateway_type (GATEWAY_ID, PROFILE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RESOURCE_PREFERENCE - Unified key-value preferences for all resource types
--
-- This table stores hierarchical preferences with GATEWAY > GROUP > USER precedence.
-- For each key, the most specific level (USER) wins over less specific levels (GROUP, GATEWAY).
--
-- Supported RESOURCE_TYPEs:
--   COMPUTE      - Compute resource preferences (Resource ID: computeResourceId)
--   STORAGE      - Storage resource preferences (Resource ID: storageResourceId)
--   PROFILE      - Profile-level metadata (Resource ID: profileId)
--   BATCH_QUEUE  - Queue policies and limits (Resource ID: computeResourceId:queueName)
--   APPLICATION  - Application defaults and settings (Resource ID: applicationInterfaceId)
--   GATEWAY      - Gateway-level configuration (Resource ID: gatewayId)
--   SYSTEM       - System-wide settings (Resource ID: "GLOBAL" or gatewayId for overrides)
--
-- OWNER_ID format by PREFERENCE_LEVEL:
--   GATEWAY: gatewayId
--   GROUP: groupResourceProfileId
--   USER: userId@gatewayId (airavataInternalUserId)
--
-- Entity uses composite PK: (RESOURCE_TYPE, RESOURCE_ID, OWNER_ID, PREFERENCE_LEVEL, PREFERENCE_KEY)
-- Note: Uses prefix lengths to fit within MySQL's 3072-byte key limit
CREATE TABLE IF NOT EXISTS RESOURCE_PREFERENCE (
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(512) NOT NULL,
    PREFERENCE_LEVEL VARCHAR(50) NOT NULL,
    PREFERENCE_KEY VARCHAR(255) NOT NULL,
    PREFERENCE_VALUE LONGTEXT,
    VALUE_TYPE VARCHAR(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_TYPE, RESOURCE_ID(100), OWNER_ID(100), PREFERENCE_LEVEL, PREFERENCE_KEY(100)),
    INDEX idx_res_pref_resource (RESOURCE_TYPE, RESOURCE_ID),
    INDEX idx_res_pref_owner (OWNER_ID),
    INDEX idx_res_pref_level (PREFERENCE_LEVEL),
    INDEX idx_res_pref_lookup (RESOURCE_TYPE, RESOURCE_ID, PREFERENCE_LEVEL, PREFERENCE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RESOURCE_INTERFACE - Unified interfaces (job submission, data movement, storage)
-- Entity uses composite PK: (RESOURCE_ID, INTERFACE_ID, INTERFACE_TYPE)
CREATE TABLE IF NOT EXISTS RESOURCE_INTERFACE (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    INTERFACE_ID VARCHAR(255) NOT NULL,
    INTERFACE_TYPE VARCHAR(50) NOT NULL,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    PROTOCOL VARCHAR(255) NOT NULL,
    PRIORITY_ORDER INT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_ID(100), INTERFACE_ID(100), INTERFACE_TYPE),
    INDEX idx_res_iface_resource (RESOURCE_ID),
    INDEX idx_res_iface_type (INTERFACE_TYPE),
    INDEX idx_res_iface_resource_type (RESOURCE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- JOB_MANAGER_COMMAND - Unified job manager and parallelism commands
-- Entity uses composite PK: (RESOURCE_JOB_MANAGER_ID, COMMAND_CATEGORY, COMMAND_TYPE)
CREATE TABLE IF NOT EXISTS JOB_MANAGER_COMMAND (
    RESOURCE_JOB_MANAGER_ID VARCHAR(255) NOT NULL,
    COMMAND_CATEGORY VARCHAR(50) NOT NULL,
    COMMAND_TYPE VARCHAR(255) NOT NULL,
    COMMAND VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_JOB_MANAGER_ID(100), COMMAND_CATEGORY, COMMAND_TYPE(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- COMPUTE RESOURCE ENTITIES
-- ============================================================================

-- COMPUTE_RESOURCE
CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    HOST_NAME VARCHAR(255) NOT NULL,
    RESOURCE_DESCRIPTION VARCHAR(255),
    ENABLED SMALLINT DEFAULT 1,
    GATEWAY_USAGE_REPORTING BOOLEAN,
    GATEWAY_USAGE_MODULE_LOAD_CMD VARCHAR(255),
    GATEWAY_USAGE_EXECUTABLE VARCHAR(255),
    MAX_MEMORY_NODE INT,
    CPUS_PER_NODE INT,
    DEFAULT_NODE_COUNT INT,
    DEFAULT_CPU_COUNT INT,
    DEFAULT_WALLTIME INT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS HOST_ALIAS (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    ALIAS VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS HOST_IPADDRESS (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    IP_ADDRESS VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- BATCH_QUEUE
CREATE TABLE IF NOT EXISTS BATCH_QUEUE (
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    QUEUE_NAME VARCHAR(255) NOT NULL,
    MAX_JOB_IN_QUEUE INT,
    MAX_MEMORY INT,
    MAX_NODES INT,
    MAX_PROCESSORS INT,
    MAX_RUNTIME INT,
    QUEUE_DESCRIPTION VARCHAR(255),
    CPU_PER_NODE INT,
    DEFAULT_NODE_COUNT INT,
    DEFAULT_CPU_COUNT INT,
    DEFAULT_WALLTIME INT,
    QUEUE_SPECIFIC_MACROS VARCHAR(255),
    IS_DEFAULT_QUEUE BOOLEAN,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (COMPUTE_RESOURCE_ID, QUEUE_NAME),
    FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- COMPUTE_RESOURCE_FILE_SYSTEM
CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_FILE_SYSTEM (
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    FILE_SYSTEM VARCHAR(50) NOT NULL,
    PATH VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (COMPUTE_RESOURCE_ID, FILE_SYSTEM),
    FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RESOURCE_JOB_MANAGER
CREATE TABLE IF NOT EXISTS RESOURCE_JOB_MANAGER (
    RESOURCE_JOB_MANAGER_ID VARCHAR(255) NOT NULL,
    RESOURCE_JOB_MANAGER_TYPE VARCHAR(50) NOT NULL,
    JOB_MANAGER_BIN_PATH VARCHAR(255),
    PUSH_MONITORING_ENDPOINT VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- UNIFIED_JOB_SUBMISSION - Single table for all job submission types with JSON config
-- This is the simplified model; legacy protocol-specific tables below are retained for backward compatibility
CREATE TABLE IF NOT EXISTS UNIFIED_JOB_SUBMISSION (
    INTERFACE_ID VARCHAR(255) NOT NULL,
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    PROTOCOL VARCHAR(50) NOT NULL,
    SECURITY_PROTOCOL VARCHAR(50),
    PRIORITY_ORDER INT,
    CONFIG JSON,
    RESOURCE_JOB_MANAGER_ID VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (INTERFACE_ID),
    INDEX idx_uj_sub_resource (COMPUTE_RESOURCE_ID),
    INDEX idx_uj_sub_protocol (PROTOCOL),
    INDEX idx_uj_sub_priority (PRIORITY_ORDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- SSH_JOB_SUBMISSION
-- Note: Entity does not extend BaseJobSubmissionEntity, so FK to JOB_SUBMISSION_BASE removed
CREATE TABLE IF NOT EXISTS SSH_JOB_SUBMISSION (
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    RESOURCE_JOB_MANAGER_ID VARCHAR(255) NOT NULL,
    ALTERNATIVE_SSH_HOSTNAME VARCHAR(255),
    SSH_PORT INT,
    MONITOR_MODE VARCHAR(255),
    SECURITY_PROTOCOL VARCHAR(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_SUBMISSION_INTERFACE_ID),
    FOREIGN KEY (RESOURCE_JOB_MANAGER_ID) REFERENCES RESOURCE_JOB_MANAGER(RESOURCE_JOB_MANAGER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- SCP_DATA_MOVEMENT
-- Note: Entity does not extend BaseDataMovementEntity, so FK to DATA_MOVEMENT_BASE removed
CREATE TABLE IF NOT EXISTS SCP_DATA_MOVEMENT (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    ALTERNATIVE_SCP_HOSTNAME VARCHAR(255),
    SSH_PORT INT,
    QUEUE_DESCRIPTION VARCHAR(255),
    SECURITY_PROTOCOL VARCHAR(50) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- GRIDFTP_ENDPOINT
-- Note: Entity references GridftpDataMovementEntity directly, not via DATA_MOVEMENT_BASE
CREATE TABLE IF NOT EXISTS GRIDFTP_ENDPOINT (
    ENDPOINT VARCHAR(255) NOT NULL,
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ENDPOINT, DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- JOB_SUBMISSION_INTERFACE
CREATE TABLE IF NOT EXISTS JOB_SUBMISSION_INTERFACE (
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    JOB_SUBMISSION_PROTOCOL VARCHAR(50) NOT NULL,
    PRIORITY_ORDER INT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (COMPUTE_RESOURCE_ID, JOB_SUBMISSION_INTERFACE_ID),
    FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DATA_MOVEMENT_INTERFACE
CREATE TABLE IF NOT EXISTS DATA_MOVEMENT_INTERFACE (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    COMPUTE_RESOURCE_ID VARCHAR(255),
    DATA_MOVEMENT_PROTOCOL VARCHAR(50) NOT NULL,
    PRIORITY_ORDER INT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID),
    FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- STORAGE_RESOURCE
CREATE TABLE IF NOT EXISTS STORAGE_RESOURCE (
    STORAGE_RESOURCE_ID VARCHAR(255) NOT NULL,
    HOST_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    ENABLED BOOLEAN DEFAULT TRUE,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (STORAGE_RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- STORAGE_INTERFACE
CREATE TABLE IF NOT EXISTS STORAGE_INTERFACE (
    STORAGE_RESOURCE_ID VARCHAR(255) NOT NULL,
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    DATA_MOVEMENT_PROTOCOL VARCHAR(50) NOT NULL,
    PRIORITY_ORDER INT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (STORAGE_RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID),
    FOREIGN KEY (STORAGE_RESOURCE_ID) REFERENCES STORAGE_RESOURCE(STORAGE_RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- APPLICATION CATALOG ENTITIES
-- ============================================================================

-- APPLICATION_INTERFACE
CREATE TABLE IF NOT EXISTS APPLICATION_INTERFACE (
    INTERFACE_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    APPLICATION_NAME VARCHAR(255),
    APPLICATION_DESCRIPTION VARCHAR(255),
    ARCHIVE_WORKING_DIRECTORY BOOLEAN,
    HAS_OPTIONAL_FILE_INPUTS BOOLEAN,
    CLEAN_AFTER_STAGED BOOLEAN,
    -- Direct module info (optional alternative to APP_MODULE_MAPPING indirection)
    MODULE_NAME VARCHAR(255),
    MODULE_VERSION VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (INTERFACE_ID),
    INDEX idx_app_interface_gateway (GATEWAY_ID),
    INDEX idx_app_interface_name (APPLICATION_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS APP_MODULE_MAPPING (
    INTERFACE_ID VARCHAR(255) NOT NULL,
    MODULE_ID VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (INTERFACE_ID) REFERENCES APPLICATION_INTERFACE(INTERFACE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- APPLICATION_DEPLOYMENT
CREATE TABLE IF NOT EXISTS APPLICATION_DEPLOYMENT (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    APP_MODULE_ID VARCHAR(255) NOT NULL,
    COMPUTE_HOSTID VARCHAR(255) NOT NULL,
    APPLICATION_DESC VARCHAR(255),
    EXECUTABLE_PATH VARCHAR(255),
    ENV_MODULE_LOAD_CMD VARCHAR(255),
    PARALLELISM VARCHAR(50),
    DEFAULT_NODE_COUNT INT,
    DEFAULT_CPU_COUNT INT,
    DEFAULT_WALLTIME INT,
    DEFAULT_QUEUE_NAME VARCHAR(255),
    EDITABLE_BY_USER BOOLEAN,
    -- Direct reference to interface (optional alternative to module indirection)
    APPLICATION_INTERFACE_ID VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_deployment_interface ON APPLICATION_DEPLOYMENT(APPLICATION_INTERFACE_ID);
CREATE INDEX IF NOT EXISTS idx_deployment_gateway ON APPLICATION_DEPLOYMENT(GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_deployment_compute_host ON APPLICATION_DEPLOYMENT(COMPUTE_HOSTID);
CREATE INDEX IF NOT EXISTS idx_deployment_module ON APPLICATION_DEPLOYMENT(APP_MODULE_ID);

-- APPLICATION_DEPLOYMENT_COMMAND - Commands for deployment (prejob, postjob, module_load)
-- Entity: ApplicationDeploymentCommandEntity with composite PK (DEPLOYMENT_ID, COMMAND_TYPE, COMMAND)
CREATE TABLE IF NOT EXISTS APPLICATION_DEPLOYMENT_COMMAND (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    COMMAND_TYPE VARCHAR(50) NOT NULL,
    COMMAND VARCHAR(1024) NOT NULL,
    COMMAND_ORDER INT,
    PRIMARY KEY (DEPLOYMENT_ID(100), COMMAND_TYPE, COMMAND(200)),
    INDEX idx_deploy_cmd_deployment (DEPLOYMENT_ID),
    INDEX idx_deploy_cmd_type (COMMAND_TYPE),
    INDEX idx_deploy_cmd_deployment_type (DEPLOYMENT_ID, COMMAND_TYPE),
    INDEX idx_deploy_cmd_order (DEPLOYMENT_ID, COMMAND_TYPE, COMMAND_ORDER),
    FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT(DEPLOYMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- APP_ENVIRONMENT - Environment variables for deployment
-- Entity: AppEnvironmentEntity with composite PK (DEPLOYMENT_ID, NAME)
CREATE TABLE IF NOT EXISTS APP_ENVIRONMENT (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    `VALUE` VARCHAR(255),
    ENV_ORDER INT,
    PRIMARY KEY (DEPLOYMENT_ID(150), NAME(100)),
    INDEX idx_app_env_deployment (DEPLOYMENT_ID),
    FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT(DEPLOYMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- LIBRARY_PATH - Library paths for deployment (prepend and append)
-- Entity: LibraryPathEntity with composite PK (DEPLOYMENT_ID, PATH_TYPE, NAME)
CREATE TABLE IF NOT EXISTS LIBRARY_PATH (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    PATH_TYPE VARCHAR(50) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PATH_VALUE VARCHAR(255),
    PRIMARY KEY (DEPLOYMENT_ID(100), PATH_TYPE, NAME(100)),
    INDEX idx_lib_path_deployment (DEPLOYMENT_ID),
    INDEX idx_lib_path_type (PATH_TYPE),
    INDEX idx_lib_path_deployment_type (DEPLOYMENT_ID, PATH_TYPE),
    FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT(DEPLOYMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSER
CREATE TABLE IF NOT EXISTS PARSER (
    PARSER_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    IMAGE_NAME VARCHAR(255) NOT NULL,
    OUTPUT_DIR_PATH VARCHAR(255) NOT NULL,
    INPUT_DIR_PATH VARCHAR(255) NOT NULL,
    EXECUTION_COMMAND VARCHAR(255) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PARSER_ID),
    INDEX idx_parser_gateway (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSER_IO - Unified parser inputs and outputs (new unified model)
-- Entity: ParserIOEntity
CREATE TABLE IF NOT EXISTS PARSER_IO (
    PARSER_IO_ID VARCHAR(255) NOT NULL,
    PARSER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DIRECTION VARCHAR(50) NOT NULL,
    REQUIRED BOOLEAN NOT NULL,
    DATA_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARSER_IO_ID),
    INDEX idx_parser_io_parser (PARSER_ID),
    INDEX idx_parser_io_direction (DIRECTION),
    INDEX idx_parser_io_parser_direction (PARSER_ID, DIRECTION),
    FOREIGN KEY (PARSER_ID) REFERENCES PARSER(PARSER_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSING_TEMPLATE - Templates for parsing application outputs
-- Entity: ParsingTemplateEntity
CREATE TABLE IF NOT EXISTS PARSING_TEMPLATE (
    PARSING_TEMPLATE_ID VARCHAR(255) NOT NULL,
    APP_INTERFACE_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARSING_TEMPLATE_ID),
    INDEX idx_parsing_template_interface (APP_INTERFACE_ID),
    INDEX idx_parsing_template_gateway (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSER_CONNECTOR - Connects parsers within a parsing template
-- Entity: ParserConnectorEntity
CREATE TABLE IF NOT EXISTS PARSER_CONNECTOR (
    PARSER_CONNECTOR_ID VARCHAR(255) NOT NULL,
    PARENT_PARSER_ID VARCHAR(255) NOT NULL,
    CHILD_PARSER_ID VARCHAR(255) NOT NULL,
    PARSING_TEMPLATE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARSER_CONNECTOR_ID),
    INDEX idx_parser_conn_parent (PARENT_PARSER_ID),
    INDEX idx_parser_conn_child (CHILD_PARSER_ID),
    INDEX idx_parser_conn_template (PARSING_TEMPLATE_ID),
    FOREIGN KEY (PARENT_PARSER_ID) REFERENCES PARSER(PARSER_ID) ON DELETE CASCADE,
    FOREIGN KEY (CHILD_PARSER_ID) REFERENCES PARSER(PARSER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARSING_TEMPLATE_ID) REFERENCES PARSING_TEMPLATE(PARSING_TEMPLATE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSER_CONNECTOR_INPUT - Maps parser inputs to outputs through connectors
-- Entity: ParserConnectorInputEntity
CREATE TABLE IF NOT EXISTS PARSER_CONNECTOR_INPUT (
    PARSER_CONNECTOR_INPUT_ID VARCHAR(255) NOT NULL,
    PARSER_INPUT_ID VARCHAR(255) NOT NULL,
    PARSER_OUTPUT_ID VARCHAR(255),
    `VALUE` VARCHAR(255),
    PARSER_CONNECTOR_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARSER_CONNECTOR_INPUT_ID),
    INDEX idx_parser_conn_input_connector (PARSER_CONNECTOR_ID),
    INDEX idx_parser_conn_input_input (PARSER_INPUT_ID),
    INDEX idx_parser_conn_input_output (PARSER_OUTPUT_ID),
    FOREIGN KEY (PARSER_INPUT_ID) REFERENCES PARSER_IO(PARSER_IO_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARSER_OUTPUT_ID) REFERENCES PARSER_IO(PARSER_IO_ID) ON DELETE SET NULL,
    FOREIGN KEY (PARSER_CONNECTOR_ID) REFERENCES PARSER_CONNECTOR(PARSER_CONNECTOR_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PARSING_TEMPLATE_INPUT - Initial inputs for a parsing template
-- Entity: ParsingTemplateInputEntity
CREATE TABLE IF NOT EXISTS PARSING_TEMPLATE_INPUT (
    PARSING_TEMPLATE_INPUT_ID VARCHAR(255) NOT NULL,
    TARGET_PARSER_INPUT_ID VARCHAR(255) NOT NULL,
    APPLICATION_OUTPUT_NAME VARCHAR(255),
    `VALUE` VARCHAR(255),
    PARSING_TEMPLATE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (PARSING_TEMPLATE_INPUT_ID),
    INDEX idx_parsing_tmpl_input_template (PARSING_TEMPLATE_ID),
    INDEX idx_parsing_tmpl_input_target (TARGET_PARSER_INPUT_ID),
    FOREIGN KEY (TARGET_PARSER_INPUT_ID) REFERENCES PARSER_IO(PARSER_IO_ID) ON DELETE CASCADE,
    FOREIGN KEY (PARSING_TEMPLATE_ID) REFERENCES PARSING_TEMPLATE(PARSING_TEMPLATE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- GATEWAY_GROUPS
CREATE TABLE IF NOT EXISTS GATEWAY_GROUPS (
    GATEWAY_ID VARCHAR(255) NOT NULL,
    ADMINS_GROUP_ID VARCHAR(255),
    READ_ONLY_ADMINS_GROUP_ID VARCHAR(255),
    DEFAULT_GATEWAY_USERS_GROUP_ID VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- EXPERIMENT CATALOG ENTITIES
-- ============================================================================

-- PROJECT
CREATE TABLE IF NOT EXISTS PROJECT (
    PROJECT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255),
    PROJECT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_project_gateway_id ON PROJECT(GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_project_user_name ON PROJECT(USER_NAME);

-- PROJECT_USER
CREATE TABLE IF NOT EXISTS PROJECT_USER (
    PROJECT_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PROJECT_ID, USER_NAME),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- EXPERIMENT
CREATE TABLE IF NOT EXISTS EXPERIMENT (
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255),
    EXPERIMENT_TYPE VARCHAR(50),
    USER_NAME VARCHAR(255),
    EXPERIMENT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    EXECUTION_ID VARCHAR(255),
    GATEWAY_EXECUTION_ID VARCHAR(255),
    GATEWAY_INSTANCE_ID VARCHAR(255),
    ENABLE_EMAIL_NOTIFICATION BOOLEAN,
    EMAIL_ADDRESSES LONGTEXT,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EXPERIMENT_ID),
    INDEX idx_experiment_gateway (GATEWAY_ID),
    INDEX idx_experiment_user_gateway (USER_NAME, GATEWAY_ID),
    INDEX idx_experiment_project (PROJECT_ID),
    INDEX idx_experiment_creation_time (CREATION_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- USER_CONFIGURATION_DATA
CREATE TABLE IF NOT EXISTS USER_CONFIGURATION_DATA (
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    AIRAVATA_AUTO_SCHEDULE BOOLEAN,
    OVERRIDE_MANUAL_SCHEDULED_PARAMS BOOLEAN,
    SHARE_EXPERIMENT_PUBLICALLY BOOLEAN,
    THROTTLE_RESOURCES BOOLEAN,
    USER_DN VARCHAR(255),
    GENERATE_CERT BOOLEAN,
    RESOURCE_HOST_ID VARCHAR(255),
    TOTAL_CPU_COUNT INT,
    NODE_COUNT INT,
    NUMBER_OF_THREADS INT,
    QUEUE_NAME VARCHAR(255),
    WALL_TIME_LIMIT INT,
    TOTAL_PHYSICAL_MEMORY INT,
    STATIC_WORKING_DIR VARCHAR(255),
    OVERRIDE_LOGIN_USER_NAME VARCHAR(255),
    OVERRIDE_SCRATCH_LOCATION VARCHAR(255),
    OVERRIDE_ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    INPUT_STORAGE_RESOURCE_ID VARCHAR(255),
    OUTPUT_STORAGE_RESOURCE_ID VARCHAR(255),
    EXPERIMENT_DATA_DIR VARCHAR(512),
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255),
    IS_USE_USER_CR_PREF BOOLEAN,
    PRIMARY KEY (EXPERIMENT_ID),
    INDEX idx_user_config_resource_host (RESOURCE_HOST_ID),
    INDEX idx_user_config_group_profile (GROUP_RESOURCE_PROFILE_ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PROCESS
CREATE TABLE IF NOT EXISTS PROCESS (
    PROCESS_ID VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    PROCESS_DETAIL LONGTEXT,
    APPLICATION_INTERFACE_ID VARCHAR(255),
    APPLICATION_DEPLOYMENT_ID VARCHAR(255),
    COMPUTE_RESOURCE_ID VARCHAR(255),
    TASK_DAG LONGTEXT,
    GATEWAY_EXECUTION_ID VARCHAR(255),
    ENABLE_EMAIL_NOTIFICATION BOOLEAN,
    EMAIL_ADDRESSES LONGTEXT,
    INPUT_STORAGE_RESOURCE_ID VARCHAR(255),
    OUTPUT_STORAGE_RESOURCE_ID VARCHAR(255),
    USER_DN VARCHAR(255),
    GENERATE_CERT BOOLEAN,
    EXPERIMENT_DATA_DIR VARCHAR(512),
    USERNAME VARCHAR(255),
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255),
    USE_USER_CR_PREF BOOLEAN,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PROCESS_ID),
    INDEX idx_process_experiment (EXPERIMENT_ID),
    INDEX idx_process_app_interface (APPLICATION_INTERFACE_ID),
    INDEX idx_process_app_deployment (APPLICATION_DEPLOYMENT_ID),
    INDEX idx_process_compute_resource (COMPUTE_RESOURCE_ID),
    INDEX idx_process_creation_time (CREATION_TIME),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PROCESS_RESOURCE_SCHEDULE
CREATE TABLE IF NOT EXISTS PROCESS_RESOURCE_SCHEDULE (
    PROCESS_ID VARCHAR(255) NOT NULL,
    RESOURCE_HOST_ID VARCHAR(255),
    TOTAL_CPU_COUNT INT,
    NODE_COUNT INT,
    NUMBER_OF_THREADS INT,
    QUEUE_NAME VARCHAR(255),
    WALL_TIME_LIMIT INT,
    TOTAL_PHYSICAL_MEMORY INT,
    STATIC_WORKING_DIR VARCHAR(255),
    OVERRIDE_LOGIN_USER_NAME VARCHAR(255),
    OVERRIDE_SCRATCH_LOCATION VARCHAR(255),
    OVERRIDE_ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    PRIMARY KEY (PROCESS_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS(PROCESS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PROCESS_WORKFLOW
CREATE TABLE IF NOT EXISTS PROCESS_WORKFLOW (
    PROCESS_ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    PROCESS_TYPE VARCHAR(50),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PROCESS_ID, WORKFLOW_ID),
    FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS(PROCESS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- TASK
CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID VARCHAR(255) NOT NULL,
    PARENT_PROCESS_ID VARCHAR(255) NOT NULL,
    TASK_TYPE VARCHAR(50),
    TASK_DETAIL LONGTEXT,
    SUB_TASK_MODEL LONGBLOB,
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (TASK_ID),
    FOREIGN KEY (PARENT_PROCESS_ID) REFERENCES PROCESS(PROCESS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- JOB
CREATE TABLE IF NOT EXISTS JOB (
    JOB_ID VARCHAR(255) NOT NULL,
    TASK_ID VARCHAR(255) NOT NULL,
    PROCESS_ID VARCHAR(255),
    JOB_DESCRIPTION LONGTEXT NOT NULL,
    JOB_NAME VARCHAR(255),
    WORKING_DIR VARCHAR(255),
    STD_OUT LONGTEXT,
    STD_ERR LONGTEXT,
    EXIT_CODE INT,
    COMPUTE_RESOURCE_CONSUMED VARCHAR(255),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (JOB_ID, TASK_ID),
    FOREIGN KEY (TASK_ID) REFERENCES TASK(TASK_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- REPLICA CATALOG ENTITIES
-- ============================================================================

-- DATA_PRODUCT
CREATE TABLE IF NOT EXISTS DATA_PRODUCT (
    PRODUCT_URI VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255),
    PRODUCT_NAME LONGTEXT,
    PRODUCT_DESCRIPTION VARCHAR(255),
    OWNER_NAME VARCHAR(255),
    PARENT_PRODUCT_URI VARCHAR(255),
    PRODUCT_SIZE INT,
    PRODUCT_TYPE VARCHAR(50),
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PRODUCT_URI),
    INDEX idx_data_product_gateway (GATEWAY_ID),
    INDEX idx_data_product_owner (OWNER_NAME),
    INDEX idx_data_product_gateway_owner (GATEWAY_ID, OWNER_NAME),
    INDEX idx_data_product_type (PRODUCT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DATA_REPLICA_LOCATION
CREATE TABLE IF NOT EXISTS DATA_REPLICA_LOCATION (
    REPLICA_ID VARCHAR(255) NOT NULL,
    PRODUCT_URI VARCHAR(255) NOT NULL,
    REPLICA_NAME LONGTEXT,
    REPLICA_DESCRIPTION VARCHAR(255),
    STORAGE_RESOURCE_ID VARCHAR(255),
    FILE_PATH VARCHAR(255),
    REPLICA_LOCATION_CATEGORY VARCHAR(50),
    REPLICA_PERSISTENT_TYPE VARCHAR(50),
    VALID_UNTIL_TIME TIMESTAMP,
    CREATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (REPLICA_ID),
    FOREIGN KEY (PRODUCT_URI) REFERENCES DATA_PRODUCT(PRODUCT_URI) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- WORKFLOW CATALOG ENTITIES
-- ============================================================================

-- AIRAVATA_WORKFLOW
CREATE TABLE IF NOT EXISTS AIRAVATA_WORKFLOW (
    ID VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- WORKFLOW_APPLICATION
CREATE TABLE IF NOT EXISTS WORKFLOW_APPLICATION (
    ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    PROCESS_ID VARCHAR(255),
    APPLICATION_INTERFACE_ID VARCHAR(255),
    COMPUTE_RESOURCE_ID VARCHAR(255),
    QUEUE_NAME VARCHAR(255),
    NODE_COUNT INT,
    CORE_COUNT INT,
    WALL_TIME_LIMIT INT,
    PHYSICAL_MEMORY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, WORKFLOW_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- WORKFLOW_HANDLER
CREATE TABLE IF NOT EXISTS WORKFLOW_HANDLER (
    ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, WORKFLOW_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- WORKFLOW_CONNECTION
CREATE TABLE IF NOT EXISTS WORKFLOW_CONNECTION (
    ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    DATA_BLOCK_ID VARCHAR(255),
    FROM_TYPE VARCHAR(50),
    FROM_ID VARCHAR(255),
    FROM_OUTPUT_NAME VARCHAR(255),
    TO_TYPE VARCHAR(50),
    TO_ID VARCHAR(255),
    TO_INPUT_NAME VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, WORKFLOW_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- WORKFLOW_DATA_BLOCK
CREATE TABLE IF NOT EXISTS WORKFLOW_DATA_BLOCK (
    ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    VALUE LONGTEXT,
    TYPE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID, WORKFLOW_ID),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- SHARING REGISTRY ENTITIES
-- ============================================================================

-- USER_GROUP
CREATE TABLE IF NOT EXISTS USER_GROUP (
    GROUP_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    OWNER_ID VARCHAR(255) NOT NULL,
    GROUP_TYPE VARCHAR(255) NOT NULL,
    GROUP_CARDINALITY VARCHAR(255) NOT NULL,
    CREATED_TIME BIGINT NOT NULL,
    UPDATED_TIME BIGINT NOT NULL,
    PRIMARY KEY (GROUP_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_user_group_owner ON USER_GROUP(OWNER_ID);
CREATE INDEX IF NOT EXISTS idx_user_group_type ON USER_GROUP(GROUP_TYPE);

-- GROUP_ADMIN
-- Entity uses composite PK: (GROUP_ID, DOMAIN_ID, ADMIN_ID)
CREATE TABLE IF NOT EXISTS GROUP_ADMIN (
    GROUP_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    ADMIN_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (GROUP_ID(100), DOMAIN_ID(100), ADMIN_ID(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- GROUP_MEMBERSHIP
-- Entity uses composite PK: (PARENT_ID, CHILD_ID, DOMAIN_ID)
CREATE TABLE IF NOT EXISTS GROUP_MEMBERSHIP (
    PARENT_ID VARCHAR(255) NOT NULL,
    CHILD_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    CHILD_TYPE VARCHAR(255) NOT NULL,
    CREATED_TIME BIGINT NOT NULL,
    UPDATED_TIME BIGINT NOT NULL,
    PRIMARY KEY (PARENT_ID(100), CHILD_ID(100), DOMAIN_ID(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ENTITY_TYPE
CREATE TABLE IF NOT EXISTS ENTITY_TYPE (
    ENTITY_TYPE_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_TIME BIGINT NOT NULL,
    UPDATED_TIME BIGINT NOT NULL,
    PRIMARY KEY (ENTITY_TYPE_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- PERMISSION_TYPE
CREATE TABLE IF NOT EXISTS PERMISSION_TYPE (
    PERMISSION_TYPE_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_TIME BIGINT NOT NULL,
    UPDATED_TIME BIGINT NOT NULL,
    PRIMARY KEY (PERMISSION_TYPE_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ENTITY
CREATE TABLE IF NOT EXISTS ENTITY (
    ENTITY_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    ENTITY_TYPE_ID VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(255) NOT NULL,
    PARENT_ENTITY_ID VARCHAR(255),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    BINARY_DATA LONGBLOB,
    FULL_TEXT TEXT,
    ORIGINAL_ENTITY_CREATION_TIME BIGINT,
    SHARED_COUNT BIGINT,
    CREATED_TIME BIGINT,
    UPDATED_TIME BIGINT,
    PRIMARY KEY (ENTITY_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- SHARING
-- Entity uses composite PK: (PERMISSION_TYPE_ID, ENTITY_ID, GROUP_ID, INHERITED_PARENT_ID, DOMAIN_ID)
-- Note: Uses prefix lengths to fit within MySQL's 3072-byte key limit
CREATE TABLE IF NOT EXISTS SHARING (
    PERMISSION_TYPE_ID VARCHAR(255) NOT NULL,
    ENTITY_ID VARCHAR(255) NOT NULL,
    GROUP_ID VARCHAR(255) NOT NULL,
    INHERITED_PARENT_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    SHARING_TYPE VARCHAR(255) NOT NULL,
    CREATED_TIME BIGINT NOT NULL,
    UPDATED_TIME BIGINT NOT NULL,
    PRIMARY KEY (PERMISSION_TYPE_ID(60), ENTITY_ID(60), GROUP_ID(60), INHERITED_PARENT_ID(60), DOMAIN_ID(60))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- CREDENTIAL STORE ENTITIES
-- ============================================================================

-- CREDENTIALS - Stores SSH keys and other credentials
-- Entity uses composite PK: (GATEWAY_ID, TOKEN_ID)
-- The USER_ID field tracks who owns/created the credential
CREATE TABLE IF NOT EXISTS CREDENTIALS (
    GATEWAY_ID VARCHAR(256) NOT NULL,
    TOKEN_ID VARCHAR(256) NOT NULL,
    CREDENTIAL LONGBLOB NOT NULL,
    USER_ID VARCHAR(256) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TIME_PERSISTED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GATEWAY_ID(128), TOKEN_ID(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_credentials_user ON CREDENTIALS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_credentials_gateway ON CREDENTIALS(GATEWAY_ID);

-- RESOURCE_ACCESS - Explicit mapping of user/group to resource with credential
CREATE TABLE IF NOT EXISTS RESOURCE_ACCESS (
    ID BIGINT AUTO_INCREMENT,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(512) NOT NULL,
    OWNER_TYPE VARCHAR(50) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    CREDENTIAL_TOKEN VARCHAR(256) NOT NULL,
    LOGIN_USERNAME VARCHAR(255),
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    DESCRIPTION VARCHAR(500),
    CREATION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY uk_resource_access (RESOURCE_TYPE, RESOURCE_ID(100), OWNER_ID(200), OWNER_TYPE),
    INDEX idx_res_access_owner (OWNER_ID, OWNER_TYPE),
    INDEX idx_res_access_resource (RESOURCE_TYPE, RESOURCE_ID),
    INDEX idx_res_access_credential (CREDENTIAL_TOKEN),
    INDEX idx_res_access_gateway (GATEWAY_ID),
    INDEX idx_res_access_enabled (ENABLED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- ============================================================================
-- CONFIGURATION AND CUSTOMIZATION
-- ============================================================================

-- CONFIGURATION
CREATE TABLE IF NOT EXISTS CONFIGURATION (
    ID BIGINT AUTO_INCREMENT,
    CONFIG_KEY VARCHAR(255) NOT NULL,
    CONFIG_VAL VARCHAR(255) NOT NULL,
    CONFIG_DOMAIN VARCHAR(255) NOT NULL DEFAULT 'default',
    PRIMARY KEY (ID),
    UNIQUE KEY uk_configuration (CONFIG_KEY(100), CONFIG_VAL(100), CONFIG_DOMAIN(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS idx_configuration_domain ON CONFIGURATION(CONFIG_DOMAIN);

-- Note: CUSTOMIZED_DASHBOARD removed - UI preferences handled on frontend
-- Note: NSF_DEMOGRAPHICS removed - demographic data stored in Keycloak user attributes if needed

-- ============================================================================
-- FOREIGN KEY CONSTRAINTS FOR GATEWAY REFERENCES
-- Added after all tables to ensure referenced tables exist
-- ============================================================================

-- User to Gateway relationship
ALTER TABLE AIRAVATA_USER
    ADD CONSTRAINT fk_user_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Resource Profile to Gateway relationship
ALTER TABLE RESOURCE_PROFILE
    ADD CONSTRAINT fk_resource_profile_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Application Interface to Gateway relationship
ALTER TABLE APPLICATION_INTERFACE
    ADD CONSTRAINT fk_app_interface_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Application Deployment to Gateway relationship
ALTER TABLE APPLICATION_DEPLOYMENT
    ADD CONSTRAINT fk_app_deployment_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Parser to Gateway relationship
ALTER TABLE PARSER
    ADD CONSTRAINT fk_parser_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Parsing Template to Gateway relationship
ALTER TABLE PARSING_TEMPLATE
    ADD CONSTRAINT fk_parsing_template_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Gateway Groups to Gateway relationship (1-to-1)
ALTER TABLE GATEWAY_GROUPS
    ADD CONSTRAINT fk_gateway_groups_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Project to Gateway relationship
ALTER TABLE PROJECT
    ADD CONSTRAINT fk_project_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Experiment to Gateway relationship
ALTER TABLE EXPERIMENT
    ADD CONSTRAINT fk_experiment_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE SET NULL;

-- Data Product to Gateway relationship
ALTER TABLE DATA_PRODUCT
    ADD CONSTRAINT fk_data_product_gateway
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE SET NULL;

-- User Group domain references Gateway
ALTER TABLE USER_GROUP
    ADD CONSTRAINT fk_user_group_gateway
    FOREIGN KEY (DOMAIN_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Entity Type domain references Gateway
ALTER TABLE ENTITY_TYPE
    ADD CONSTRAINT fk_entity_type_gateway
    FOREIGN KEY (DOMAIN_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Permission Type domain references Gateway
ALTER TABLE PERMISSION_TYPE
    ADD CONSTRAINT fk_permission_type_gateway
    FOREIGN KEY (DOMAIN_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- Entity domain references Gateway
ALTER TABLE ENTITY
    ADD CONSTRAINT fk_entity_gateway
    FOREIGN KEY (DOMAIN_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE;

-- ============================================================================
-- VIEW FOR LATEST EXPERIMENT STATUS
-- ============================================================================

CREATE OR REPLACE VIEW LATEST_EXPERIMENT_STATUS AS
SELECT ES1.PARENT_ID AS EXPERIMENT_ID,
       ES1.STATE,
       ES1.TIME_OF_STATE_CHANGE,
       ES1.REASON
FROM STATUS ES1
WHERE ES1.PARENT_TYPE = 'EXPERIMENT'
  AND ES1.SEQUENCE_NUM = (
      SELECT MAX(ES2.SEQUENCE_NUM)
      FROM STATUS ES2
      WHERE ES2.PARENT_ID = ES1.PARENT_ID
        AND ES2.PARENT_TYPE = 'EXPERIMENT'
  );

-- ============================================================================
-- END OF BASELINE SCHEMA
-- ============================================================================
