-- Research Catalog Tables

-- Main catalog resource table
CREATE TABLE IF NOT EXISTS CATALOG_RESOURCE (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'NONE',
    PRIVACY VARCHAR(50) DEFAULT 'PRIVATE',
    GATEWAY_ID VARCHAR(255),
    OWNER_ID VARCHAR(255),
    HEADER_IMAGE VARCHAR(1024),
    NOTEBOOK_PATH VARCHAR(1024),
    JUPYTER_SERVER_URL VARCHAR(1024),
    DATASET_URL VARCHAR(1024),
    DATASET_SIZE BIGINT,
    DATASET_FORMAT VARCHAR(255),
    REPOSITORY_URL VARCHAR(1024),
    REPOSITORY_BRANCH VARCHAR(255),
    REPOSITORY_COMMIT VARCHAR(255),
    MODEL_URL VARCHAR(1024),
    APPLICATION_INTERFACE_ID VARCHAR(255),
    MODEL_FRAMEWORK VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    PRIMARY KEY (RESOURCE_ID)
);

-- Catalog resource authors (many-to-many)
CREATE TABLE IF NOT EXISTS CATALOG_RESOURCE_AUTHOR (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESOURCE_ID, AUTHOR),
    FOREIGN KEY (RESOURCE_ID) REFERENCES CATALOG_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
);

-- Catalog resource tags (many-to-many)
CREATE TABLE IF NOT EXISTS CATALOG_RESOURCE_TAG (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    TAG VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESOURCE_ID, TAG),
    FOREIGN KEY (RESOURCE_ID) REFERENCES CATALOG_RESOURCE(RESOURCE_ID) ON DELETE CASCADE
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_catalog_resource_privacy ON CATALOG_RESOURCE(PRIVACY);
CREATE INDEX IF NOT EXISTS idx_catalog_resource_type ON CATALOG_RESOURCE(RESOURCE_TYPE);
CREATE INDEX IF NOT EXISTS idx_catalog_resource_gateway ON CATALOG_RESOURCE(GATEWAY_ID);
CREATE INDEX IF NOT EXISTS idx_catalog_resource_owner ON CATALOG_RESOURCE(OWNER_ID);
CREATE INDEX IF NOT EXISTS idx_catalog_resource_created ON CATALOG_RESOURCE(CREATED_AT);
