# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-15 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_airavata_wagtail_base', '0011_auto_20180415_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankpage',
            name='show_footer',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text="Choose yes if you want the Footer to show on home page or no if you don't want to", max_length=5),
        ),
        migrations.AddField(
            model_name='navbar',
            name='logo_with_text',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Choose yes if you want to display the text next to the logo', max_length=5),
        ),
        migrations.AlterField(
            model_name='blankpage',
            name='show_nav_extra',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text="Choose yes if you want the secondary navbar to show on home page or no if you don't want to", max_length=5),
        ),
        migrations.AlterField(
            model_name='blankpage',
            name='show_navbar',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text="Choose yes if you want to display the navbar on home page and no if you don't want to.", max_length=5),
        ),
    ]
