/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * Apache Airavata - Unified Database Schema (V1 Baseline)
 *
 * Generated from JPA @Entity annotations in the codebase.
 * All persistence units share a single 'airavata' database.
 *
 * Requires: MariaDB 10.2+ or MySQL 5.7+
 */

-- ============================================================================
-- 1. EXPERIMENT CATALOG
-- ============================================================================

CREATE TABLE IF NOT EXISTS GATEWAY (
    GATEWAY_ID                          VARCHAR(255) NOT NULL,
    GATEWAY_NAME                        VARCHAR(255),
    DOMAIN                              VARCHAR(255),
    EMAIL_ADDRESS                       VARCHAR(255),
    GATEWAY_APPROVAL_STATUS             VARCHAR(255),
    GATEWAY_ACRONYM                     VARCHAR(255),
    GATEWAY_URL                         VARCHAR(255),
    GATEWAY_PUBLIC_ABSTRACT             VARCHAR(255),
    GATEWAY_REVIEW_PROPOSAL_DESCRIPTION VARCHAR(255),
    GATEWAY_ADMIN_FIRST_NAME            VARCHAR(255),
    GATEWAY_ADMIN_LAST_NAME             VARCHAR(255),
    GATEWAY_ADMIN_EMAIL                 VARCHAR(255),
    IDENTITY_SERVER_USERNAME            VARCHAR(255),
    IDENTITY_SERVER_PASSWORD_TOKEN      VARCHAR(255),
    DECLINED_REASON                     VARCHAR(255),
    OAUTH_CLIENT_ID                     VARCHAR(255),
    OAUTH_CLIENT_SECRET                 VARCHAR(255),
    REQUEST_CREATION_TIME               TIMESTAMP NULL,
    REQUESTER_USERNAME                  VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USERS (
    USER_NAME                   VARCHAR(255) NOT NULL,
    GATEWAY_ID                  VARCHAR(255) NOT NULL,
    AIRAVATA_INTERNAL_USER_ID   VARCHAR(255),
    PASSWORD                    VARCHAR(255),
    PRIMARY KEY (USER_NAME, GATEWAY_ID),
    CONSTRAINT FK_USERS_GATEWAY FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GATEWAY_WORKER (
    GATEWAY_ID  VARCHAR(255) NOT NULL,
    USER_NAME   VARCHAR(255) NOT NULL,
    PRIMARY KEY (GATEWAY_ID, USER_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GATEWAY_USAGE_REPORTING_COMMAND (
    GATEWAY_ID          VARCHAR(255) NOT NULL,
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    COMMAND             LONGTEXT,
    PRIMARY KEY (GATEWAY_ID, COMPUTE_RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID      VARCHAR(255) NOT NULL,
    GATEWAY_ID           VARCHAR(255),
    TITLE                VARCHAR(255),
    NOTIFICATION_MESSAGE VARCHAR(4096),
    CREATION_DATE        TIMESTAMP NULL,
    PUBLISHED_DATE       TIMESTAMP NULL,
    EXPIRATION_DATE      TIMESTAMP NULL,
    PRIORITY             VARCHAR(255),
    PRIMARY KEY (NOTIFICATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROJECT (
    PROJECT_ID      VARCHAR(255) NOT NULL,
    USER_NAME       VARCHAR(255),
    GATEWAY_ID      VARCHAR(255),
    PROJECT_NAME    VARCHAR(255),
    DESCRIPTION     VARCHAR(255),
    CREATION_TIME   TIMESTAMP NULL,
    PRIMARY KEY (PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROJECT_USER (
    PROJECT_ID  VARCHAR(255) NOT NULL,
    USER_NAME   VARCHAR(255) NOT NULL,
    PRIMARY KEY (PROJECT_ID, USER_NAME),
    CONSTRAINT FK_PROJECT_USER_USER FOREIGN KEY (USER_NAME) REFERENCES USERS (USER_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS QUEUE_STATUS (
    HOST_NAME       VARCHAR(255) NOT NULL,
    QUEUE_NAME      VARCHAR(255) NOT NULL,
    CREATED_TIME    BIGINT NOT NULL,
    QUEUE_UP        TINYINT(1) NOT NULL DEFAULT 0,
    RUNNING_JOBS    TINYINT(1) NOT NULL DEFAULT 0,
    QUEUED_JOBS     INT NOT NULL DEFAULT 0,
    PRIMARY KEY (HOST_NAME, QUEUE_NAME, CREATED_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT (
    EXPERIMENT_ID             VARCHAR(255) NOT NULL,
    PROJECT_ID                VARCHAR(255),
    GATEWAY_ID                VARCHAR(255),
    EXPERIMENT_TYPE           VARCHAR(255),
    CLEANUP_STRATEGY          VARCHAR(255),
    USER_NAME                 VARCHAR(255),
    EXPERIMENT_NAME           VARCHAR(255),
    CREATION_TIME             TIMESTAMP NULL,
    DESCRIPTION               VARCHAR(255),
    EXECUTION_ID              VARCHAR(255),
    GATEWAY_EXECUTION_ID      VARCHAR(255),
    GATEWAY_INSTANCE_ID       VARCHAR(255),
    ENABLE_EMAIL_NOTIFICATION TINYINT(1) NOT NULL DEFAULT 0,
    EMAIL_ADDRESSES           LONGTEXT,
    PRIMARY KEY (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT_SUMMARY (
    EXPERIMENT_ID        VARCHAR(255) NOT NULL,
    PROJECT_ID           VARCHAR(255),
    GATEWAY_ID           VARCHAR(255),
    CREATION_TIME        TIMESTAMP NULL,
    USER_NAME            VARCHAR(255),
    EXPERIMENT_NAME      VARCHAR(255),
    DESCRIPTION          VARCHAR(255),
    EXECUTION_ID         VARCHAR(255),
    STATE                VARCHAR(255),
    RESOURCE_HOST_ID     VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP NULL,
    PRIMARY KEY (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT_INPUT (
    EXPERIMENT_ID             VARCHAR(255) NOT NULL,
    INPUT_NAME                VARCHAR(255) NOT NULL,
    INPUT_VALUE               LONGTEXT,
    DATA_TYPE                 VARCHAR(255),
    APPLICATION_ARGUMENT      VARCHAR(255),
    STANDARD_INPUT            TINYINT(1) NOT NULL DEFAULT 0,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    METADATA                  VARCHAR(4096),
    INPUT_ORDER               INT NOT NULL DEFAULT 0,
    IS_REQUIRED               TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_CMD  TINYINT(1) NOT NULL DEFAULT 0,
    DATA_STAGED               TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID       VARCHAR(255),
    IS_READ_ONLY              TINYINT(1) NOT NULL DEFAULT 0,
    OVERRIDE_FILENAME         VARCHAR(255),
    PRIMARY KEY (EXPERIMENT_ID, INPUT_NAME),
    CONSTRAINT FK_EXP_INPUT_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT_OUTPUT (
    EXPERIMENT_ID            VARCHAR(255) NOT NULL,
    OUTPUT_NAME              VARCHAR(255) NOT NULL,
    OUTPUT_VALUE             LONGTEXT,
    DATA_TYPE                VARCHAR(255),
    APPLICATION_ARGUMENT     VARCHAR(255),
    IS_REQUIRED              TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_CMD TINYINT(1) NOT NULL DEFAULT 0,
    DATA_MOVEMENT            TINYINT(1) NOT NULL DEFAULT 0,
    LOCATION                 VARCHAR(255),
    SEARCH_QUERY             VARCHAR(255),
    OUTPUT_STREAMING         TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID      VARCHAR(255),
    METADATA                 VARCHAR(4096),
    PRIMARY KEY (EXPERIMENT_ID, OUTPUT_NAME),
    CONSTRAINT FK_EXP_OUTPUT_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT_STATUS (
    STATUS_ID            VARCHAR(255) NOT NULL,
    EXPERIMENT_ID        VARCHAR(255) NOT NULL,
    STATE                VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP NULL,
    REASON               LONGTEXT,
    PRIMARY KEY (STATUS_ID, EXPERIMENT_ID),
    CONSTRAINT FK_EXP_STATUS_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS EXPERIMENT_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    EXPERIMENT_ID            VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, EXPERIMENT_ID),
    CONSTRAINT FK_EXP_ERROR_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_CONFIGURATION_DATA (
    EXPERIMENT_ID                      VARCHAR(255) NOT NULL,
    AIRAVATA_AUTO_SCHEDULE             TINYINT(1) NOT NULL DEFAULT 0,
    OVERRIDE_MANUAL_SCHEDULED_PARAMS   TINYINT(1) NOT NULL DEFAULT 0,
    SHARE_EXPERIMENT_PUBLICALLY        TINYINT(1) NOT NULL DEFAULT 0,
    THROTTLE_RESOURCES                 TINYINT(1) NOT NULL DEFAULT 0,
    USER_DN                            VARCHAR(255),
    GENERATE_CERT                      TINYINT(1) NOT NULL DEFAULT 0,
    RESOURCE_HOST_ID                   VARCHAR(255),
    TOTAL_CPU_COUNT                    INT NOT NULL DEFAULT 0,
    NODE_COUNT                         INT NOT NULL DEFAULT 0,
    NUMBER_OF_THREADS                  INT NOT NULL DEFAULT 0,
    QUEUE_NAME                         VARCHAR(255),
    WALL_TIME_LIMIT                    INT NOT NULL DEFAULT 0,
    TOTAL_PHYSICAL_MEMORY              INT NOT NULL DEFAULT 0,
    STATIC_WORKING_DIR                 VARCHAR(255),
    OVERRIDE_LOGIN_USER_NAME           VARCHAR(255),
    OVERRIDE_SCRATCH_LOCATION          VARCHAR(255),
    OVERRIDE_ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    INPUT_STORAGE_RESOURCE_ID          VARCHAR(255),
    OUTPUT_STORAGE_RESOURCE_ID         VARCHAR(255),
    EXPERIMENT_DATA_DIR                VARCHAR(512),
    GROUP_RESOURCE_PROFILE_ID          VARCHAR(255),
    IS_USE_USER_CR_PREF                TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (EXPERIMENT_ID),
    CONSTRAINT FK_USER_CONF_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_SCHEDULING (
    EXPERIMENT_ID                      VARCHAR(255) NOT NULL,
    RESOURCE_HOST_ID                   VARCHAR(255) NOT NULL,
    QUEUE_NAME                         VARCHAR(255) NOT NULL,
    TOTAL_CPU_COUNT                    INT NOT NULL DEFAULT 0,
    NODE_COUNT                         INT NOT NULL DEFAULT 0,
    NUMBER_OF_THREADS                  INT NOT NULL DEFAULT 0,
    WALL_TIME_LIMIT                    INT NOT NULL DEFAULT 0,
    PARALLEL_GROUP_COUNT               INT NOT NULL DEFAULT 0,
    TOTAL_PHYSICAL_MEMORY              INT NOT NULL DEFAULT 0,
    STATIC_WORKING_DIR                 VARCHAR(255),
    OVERRIDE_LOGIN_USER_NAME           VARCHAR(255),
    OVERRIDE_SCRATCH_LOCATION          VARCHAR(255),
    OVERRIDE_ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    PRIMARY KEY (EXPERIMENT_ID, RESOURCE_HOST_ID, QUEUE_NAME),
    CONSTRAINT FK_COMP_SCHED_USER_CONF FOREIGN KEY (EXPERIMENT_ID) REFERENCES USER_CONFIGURATION_DATA (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS (
    PROCESS_ID                 VARCHAR(255) NOT NULL,
    EXPERIMENT_ID              VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NULL,
    LAST_UPDATE_TIME           TIMESTAMP NULL,
    PROCESS_DETAIL             LONGTEXT,
    APPLICATION_INTERFACE_ID   VARCHAR(255),
    APPLICATION_DEPLOYMENT_ID  VARCHAR(255),
    COMPUTE_RESOURCE_ID        VARCHAR(255),
    TASK_DAG                   LONGTEXT,
    GATEWAY_EXECUTION_ID       VARCHAR(255),
    ENABLE_EMAIL_NOTIFICATION  TINYINT(1) NOT NULL DEFAULT 0,
    EMAIL_ADDRESSES            LONGTEXT,
    INPUT_STORAGE_RESOURCE_ID  VARCHAR(255),
    OUTPUT_STORAGE_RESOURCE_ID VARCHAR(255),
    USER_DN                    VARCHAR(255),
    GENERATE_CERT              TINYINT(1) NOT NULL DEFAULT 0,
    EXPERIMENT_DATA_DIR        VARCHAR(512),
    USERNAME                   VARCHAR(255),
    GROUP_RESOURCE_PROFILE_ID  VARCHAR(255),
    USE_USER_CR_PREF           TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (PROCESS_ID),
    CONSTRAINT FK_PROCESS_EXPERIMENT FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_STATUS (
    STATUS_ID            VARCHAR(255) NOT NULL,
    PROCESS_ID           VARCHAR(255) NOT NULL,
    STATE                VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP NULL,
    REASON               LONGTEXT,
    PRIMARY KEY (STATUS_ID, PROCESS_ID),
    CONSTRAINT FK_PROC_STATUS_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    PROCESS_ID               VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, PROCESS_ID),
    CONSTRAINT FK_PROC_ERROR_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_INPUT (
    PROCESS_ID                VARCHAR(255) NOT NULL,
    INPUT_NAME                VARCHAR(255) NOT NULL,
    INPUT_VALUE               LONGTEXT,
    DATA_TYPE                 VARCHAR(255),
    APPLICATION_ARGUMENT      VARCHAR(255),
    STANDARD_INPUT            TINYINT(1) NOT NULL DEFAULT 0,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    METADATA                  VARCHAR(4096),
    INPUT_ORDER               INT NOT NULL DEFAULT 0,
    IS_REQUIRED               TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_CMD  TINYINT(1) NOT NULL DEFAULT 0,
    DATA_STAGED               TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID       VARCHAR(255),
    IS_READ_ONLY              TINYINT(1) NOT NULL DEFAULT 0,
    OVERRIDE_FILENAME         VARCHAR(255),
    PRIMARY KEY (PROCESS_ID, INPUT_NAME),
    CONSTRAINT FK_PROC_INPUT_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_OUTPUT (
    PROCESS_ID               VARCHAR(255) NOT NULL,
    OUTPUT_NAME              VARCHAR(255) NOT NULL,
    OUTPUT_VALUE             LONGTEXT,
    DATA_TYPE                VARCHAR(255),
    APPLICATION_ARGUMENT     VARCHAR(255),
    IS_REQUIRED              TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_CMD TINYINT(1) NOT NULL DEFAULT 0,
    DATA_MOVEMENT            TINYINT(1) NOT NULL DEFAULT 0,
    LOCATION                 VARCHAR(255),
    SEARCH_QUERY             VARCHAR(255),
    OUTPUT_STREAMING         TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID      VARCHAR(255),
    METADATA                 VARCHAR(4096),
    PRIMARY KEY (PROCESS_ID, OUTPUT_NAME),
    CONSTRAINT FK_PROC_OUTPUT_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_RESOURCE_SCHEDULE (
    PROCESS_ID                         VARCHAR(255) NOT NULL,
    RESOURCE_HOST_ID                   VARCHAR(255),
    TOTAL_CPU_COUNT                    INT NOT NULL DEFAULT 0,
    NODE_COUNT                         INT NOT NULL DEFAULT 0,
    NUMBER_OF_THREADS                  INT NOT NULL DEFAULT 0,
    QUEUE_NAME                         VARCHAR(255),
    WALL_TIME_LIMIT                    INT NOT NULL DEFAULT 0,
    TOTAL_PHYSICAL_MEMORY              INT NOT NULL DEFAULT 0,
    STATIC_WORKING_DIR                 VARCHAR(255),
    OVERRIDE_LOGIN_USER_NAME           VARCHAR(255),
    OVERRIDE_SCRATCH_LOCATION          VARCHAR(255),
    OVERRIDE_ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    PRIMARY KEY (PROCESS_ID),
    CONSTRAINT FK_PROC_RESCHED_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PROCESS_WORKFLOW (
    PROCESS_ID    VARCHAR(255) NOT NULL,
    WORKFLOW_ID   VARCHAR(255) NOT NULL,
    CREATION_TIME TIMESTAMP NULL,
    TYPE          VARCHAR(255),
    PRIMARY KEY (PROCESS_ID, WORKFLOW_ID),
    CONSTRAINT FK_PROC_WORKFLOW_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TASK (
    TASK_ID           VARCHAR(255) NOT NULL,
    TASK_TYPE         VARCHAR(255),
    PARENT_PROCESS_ID VARCHAR(255) NOT NULL,
    CREATION_TIME     TIMESTAMP NULL,
    LAST_UPDATE_TIME  TIMESTAMP NULL,
    TASK_DETAIL       LONGTEXT,
    SUB_TASK_MODEL    LONGBLOB,
    PRIMARY KEY (TASK_ID),
    CONSTRAINT FK_TASK_PROCESS FOREIGN KEY (PARENT_PROCESS_ID) REFERENCES PROCESS (PROCESS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TASK_STATUS (
    STATUS_ID            VARCHAR(255) NOT NULL,
    TASK_ID              VARCHAR(255) NOT NULL,
    STATE                VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP NULL,
    REASON               LONGTEXT,
    PRIMARY KEY (STATUS_ID, TASK_ID),
    CONSTRAINT FK_TASK_STATUS_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK (TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TASK_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    TASK_ID                  VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, TASK_ID),
    CONSTRAINT FK_TASK_ERROR_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK (TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS JOB (
    JOB_ID                    VARCHAR(255) NOT NULL,
    TASK_ID                   VARCHAR(255) NOT NULL,
    PROCESS_ID                VARCHAR(255),
    JOB_DESCRIPTION           LONGTEXT,
    CREATION_TIME             TIMESTAMP NULL,
    COMPUTE_RESOURCE_CONSUMED VARCHAR(255),
    JOB_NAME                  VARCHAR(255),
    WORKING_DIR               VARCHAR(255),
    STD_OUT                   LONGTEXT,
    STD_ERR                   LONGTEXT,
    EXIT_CODE                 INT NOT NULL DEFAULT 0,
    PRIMARY KEY (JOB_ID, TASK_ID),
    CONSTRAINT FK_JOB_TASK FOREIGN KEY (TASK_ID) REFERENCES TASK (TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS JOB_STATUS (
    STATUS_ID            VARCHAR(255) NOT NULL,
    JOB_ID               VARCHAR(255) NOT NULL,
    TASK_ID              VARCHAR(255) NOT NULL,
    STATE                VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP NULL,
    REASON               LONGTEXT,
    PRIMARY KEY (STATUS_ID, JOB_ID, TASK_ID),
    CONSTRAINT FK_JOB_STATUS_JOB FOREIGN KEY (JOB_ID, TASK_ID) REFERENCES JOB (JOB_ID, TASK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 2. APPLICATION CATALOG
-- ============================================================================

CREATE TABLE IF NOT EXISTS GATEWAY_GROUPS (
    GATEWAY_ID                     VARCHAR(255) NOT NULL,
    ADMINS_GROUP_ID                VARCHAR(255),
    READ_ONLY_ADMINS_GROUP_ID      VARCHAR(255),
    DEFAULT_GATEWAY_USERS_GROUP_ID VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GATEWAY_PROFILE (
    GATEWAY_ID                     VARCHAR(255) NOT NULL,
    CREATION_TIME                  TIMESTAMP NULL,
    CS_TOKEN                       VARCHAR(255),
    IDENTITY_SERVER_PWD_CRED_TOKEN VARCHAR(255),
    IDENTITY_SERVER_TENANT         VARCHAR(255),
    UPDATE_TIME                    TIMESTAMP NULL,
    PRIMARY KEY (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GROUP_RESOURCE_PROFILE (
    GROUP_RESOURCE_PROFILE_ID      VARCHAR(255) NOT NULL,
    GATEWAY_ID                     VARCHAR(255),
    GROUP_RESOURCE_PROFILE_NAME    VARCHAR(255),
    CREATION_TIME                  BIGINT,
    UPDATE_TIME                    BIGINT,
    DEFAULT_CREDENTIAL_STORE_TOKEN VARCHAR(255),
    PRIMARY KEY (GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE (
    RESOURCE_ID                   VARCHAR(255) NOT NULL,
    CREATION_TIME                 TIMESTAMP NULL,
    ENABLED                       SMALLINT,
    GATEWAY_USAGE_EXECUTABLE      VARCHAR(255),
    GATEWAY_USAGE_MODULE_LOAD_CMD VARCHAR(255),
    GATEWAY_USAGE_REPORTING       TINYINT(1),
    HOST_NAME                     VARCHAR(255),
    MAX_MEMORY_NODE               INT,
    RESOURCE_DESCRIPTION          VARCHAR(255),
    UPDATE_TIME                   TIMESTAMP NULL,
    CPUS_PER_NODE                 INT,
    DEFAULT_NODE_COUNT            INT,
    DEFAULT_CPU_COUNT             INT,
    DEFAULT_WALLTIME              INT,
    PRIMARY KEY (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_ALIAS (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    ALIAS       VARCHAR(255),
    CONSTRAINT FK_HOST_ALIAS_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HOST_IPADDRESS (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    IP_ADDRESS  VARCHAR(255),
    CONSTRAINT FK_HOST_IPADDRESS_RESOURCE FOREIGN KEY (RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_FILE_SYSTEM (
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    FILE_SYSTEM         VARCHAR(255) NOT NULL,
    PATH                VARCHAR(255),
    PRIMARY KEY (COMPUTE_RESOURCE_ID, FILE_SYSTEM),
    CONSTRAINT FK_CRFS_RESOURCE FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS RESOURCE_JOB_MANAGER (
    RESOURCE_JOB_MANAGER_ID   VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NOT NULL,
    JOB_MANAGER_BIN_PATH      VARCHAR(255),
    PUSH_MONITORING_ENDPOINT   VARCHAR(255),
    RESOURCE_JOB_MANAGER_TYPE  VARCHAR(255),
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS JOB_MANAGER_COMMAND (
    RESOURCE_JOB_MANAGER_ID VARCHAR(255) NOT NULL,
    COMMAND_TYPE            VARCHAR(255) NOT NULL,
    COMMAND                 VARCHAR(255),
    PRIMARY KEY (RESOURCE_JOB_MANAGER_ID, COMMAND_TYPE),
    CONSTRAINT FK_JMC_RJM FOREIGN KEY (RESOURCE_JOB_MANAGER_ID) REFERENCES RESOURCE_JOB_MANAGER (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARALLELISM_COMMAND (
    RESOURCE_JOB_MANAGER_ID VARCHAR(255) NOT NULL,
    COMMAND_TYPE            VARCHAR(255) NOT NULL,
    COMMAND                 VARCHAR(255),
    PRIMARY KEY (RESOURCE_JOB_MANAGER_ID, COMMAND_TYPE),
    CONSTRAINT FK_PC_RJM FOREIGN KEY (RESOURCE_JOB_MANAGER_ID) REFERENCES RESOURCE_JOB_MANAGER (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BATCH_QUEUE (
    COMPUTE_RESOURCE_ID   VARCHAR(255) NOT NULL,
    QUEUE_NAME            VARCHAR(255) NOT NULL,
    MAX_JOB_IN_QUEUE      INT,
    MAX_MEMORY            INT,
    MAX_NODES             INT,
    MAX_PROCESSORS        INT,
    MAX_RUNTIME           INT,
    QUEUE_DESCRIPTION     VARCHAR(255),
    CPU_PER_NODE          INT,
    DEFAULT_NODE_COUNT    INT,
    DEFAULT_CPU_COUNT     INT,
    DEFAULT_WALLTIME      INT,
    QUEUE_SPECIFIC_MACROS VARCHAR(255),
    IS_DEFAULT_QUEUE      TINYINT(1),
    PRIMARY KEY (COMPUTE_RESOURCE_ID, QUEUE_NAME),
    CONSTRAINT FK_BQ_RESOURCE FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS JOB_SUBMISSION_INTERFACE (
    COMPUTE_RESOURCE_ID         VARCHAR(255) NOT NULL,
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME               TIMESTAMP NULL,
    JOB_SUBMISSION_PROTOCOL     VARCHAR(255),
    PRIORITY_ORDER              INT,
    UPDATE_TIME                 TIMESTAMP NULL,
    PRIMARY KEY (COMPUTE_RESOURCE_ID, JOB_SUBMISSION_INTERFACE_ID),
    CONSTRAINT FK_JSI_RESOURCE FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_MOVEMENT_INTERFACE (
    COMPUTE_RESOURCE_ID        VARCHAR(255) NOT NULL,
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NULL,
    DATA_MOVEMENT_PROTOCOL     VARCHAR(255),
    PRIORITY_ORDER             INT,
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (COMPUTE_RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID),
    CONSTRAINT FK_DMI_RESOURCE FOREIGN KEY (COMPUTE_RESOURCE_ID) REFERENCES COMPUTE_RESOURCE (RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SSH_JOB_SUBMISSION (
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    RESOURCE_JOB_MANAGER_ID    VARCHAR(255) NOT NULL,
    ALTERNATIVE_SSH_HOSTNAME   VARCHAR(255),
    CREATION_TIME              TIMESTAMP NOT NULL,
    MONITOR_MODE               VARCHAR(255),
    SECURITY_PROTOCOL          VARCHAR(255),
    SSH_PORT                   INT,
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (JOB_SUBMISSION_INTERFACE_ID),
    CONSTRAINT FK_SJS_RJM FOREIGN KEY (RESOURCE_JOB_MANAGER_ID) REFERENCES RESOURCE_JOB_MANAGER (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LOCAL_SUBMISSION (
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME               TIMESTAMP NULL,
    UPDATE_TIME                 TIMESTAMP NULL,
    RESOURCE_JOB_MANAGER_ID    VARCHAR(255),
    SECURITY_PROTOCOL          VARCHAR(255),
    PRIMARY KEY (JOB_SUBMISSION_INTERFACE_ID),
    CONSTRAINT FK_LS_RJM FOREIGN KEY (RESOURCE_JOB_MANAGER_ID) REFERENCES RESOURCE_JOB_MANAGER (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GLOBUS_SUBMISSION (
    SUBMISSION_ID        VARCHAR(255) NOT NULL,
    RESOURCE_JOB_MANAGER VARCHAR(255),
    SECURITY_PROTOCAL    VARCHAR(255),
    PRIMARY KEY (SUBMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GLOBUS_GK_ENDPOINT (
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    ENDPOINT      VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, ENDPOINT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GSISSH_SUBMISSION (
    SUBMISSION_ID        VARCHAR(255) NOT NULL,
    INSTALLED_PATH       VARCHAR(255),
    MONITOR_MODE         VARCHAR(255),
    RESOURCE_JOB_MANAGER VARCHAR(255),
    SSH_PORT             INT,
    PRIMARY KEY (SUBMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GSISSH_EXPORT (
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    EXPORT        VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, EXPORT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GSISSH_POSTJOBCOMMAND (
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    COMMAND       VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, COMMAND)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GSISSH_PREJOBCOMMAND (
    SUBMISSION_ID VARCHAR(255) NOT NULL,
    COMMAND       VARCHAR(255) NOT NULL,
    PRIMARY KEY (SUBMISSION_ID, COMMAND)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UNICORE_SUBMISSION (
    SUBMISSION_ID        VARCHAR(255) NOT NULL,
    SECURITY_PROTOCAL    VARCHAR(255),
    UNICORE_ENDPOINT_URL VARCHAR(255),
    PRIMARY KEY (SUBMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CLOUD_JOB_SUBMISSION (
    JOB_SUBMISSION_INTERFACE_ID VARCHAR(255) NOT NULL,
    SECURITY_PROTOCOL           VARCHAR(255),
    NODE_ID                     VARCHAR(255),
    EXECUTABLE_TYPE             VARCHAR(255),
    PROVIDER_NAME               VARCHAR(255),
    USER_ACCOUNT_NAME           VARCHAR(255),
    PRIMARY KEY (JOB_SUBMISSION_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GRIDFTP_DATA_MOVEMENT (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NULL,
    SECURITY_PROTOCOL          VARCHAR(255),
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GRIDFTP_ENDPOINT (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    ENDPOINT                   VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NULL,
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID, ENDPOINT),
    CONSTRAINT FK_GE_DMI FOREIGN KEY (DATA_MOVEMENT_INTERFACE_ID) REFERENCES GRIDFTP_DATA_MOVEMENT (DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SCP_DATA_MOVEMENT (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    ALTERNATIVE_SCP_HOSTNAME   VARCHAR(255),
    CREATION_TIME              TIMESTAMP NULL,
    QUEUE_DESCRIPTION          VARCHAR(255),
    SECURITY_PROTOCOL          VARCHAR(255),
    SSH_PORT                   INT,
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LOCAL_DATA_MOVEMENT (
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (DATA_MOVEMENT_INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS UNICORE_DATAMOVEMENT (
    DATAMOVEMENT_ID      VARCHAR(255) NOT NULL,
    SECURITY_PROTOCAL    VARCHAR(255),
    UNICORE_ENDPOINT_URL VARCHAR(255),
    PRIMARY KEY (DATAMOVEMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS STORAGE_RESOURCE (
    STORAGE_RESOURCE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME       TIMESTAMP NULL,
    DESCRIPTION         VARCHAR(255),
    ENABLED             TINYINT(1),
    HOST_NAME           VARCHAR(255),
    UPDATE_TIME         TIMESTAMP NULL,
    PRIMARY KEY (STORAGE_RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS STORAGE_INTERFACE (
    STORAGE_RESOURCE_ID        VARCHAR(255) NOT NULL,
    DATA_MOVEMENT_INTERFACE_ID VARCHAR(255) NOT NULL,
    CREATION_TIME              TIMESTAMP NULL,
    DATA_MOVEMENT_PROTOCOL     VARCHAR(255),
    PRIORITY_ORDER             INT,
    UPDATE_TIME                TIMESTAMP NULL,
    PRIMARY KEY (STORAGE_RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID),
    CONSTRAINT FK_SI_SR FOREIGN KEY (STORAGE_RESOURCE_ID) REFERENCES STORAGE_RESOURCE (STORAGE_RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_PREFERENCE (
    GATEWAY_ID                              VARCHAR(255) NOT NULL,
    RESOURCE_ID                             VARCHAR(255) NOT NULL,
    ALLOCATION_PROJECT_NUMBER               VARCHAR(255),
    LOGIN_USERNAME                          VARCHAR(255),
    OVERRIDE_BY_AIRAVATA                    TINYINT(1),
    PREFERED_BATCH_QUEUE                    VARCHAR(255),
    PREFERED_DATA_MOVE_PROTOCOL             VARCHAR(255),
    PREFERED_JOB_SUB_PROTOCOL               VARCHAR(255),
    QUALITY_OF_SERVICE                      VARCHAR(255),
    RESERVATION                             VARCHAR(255),
    RESERVATION_END_TIME                    TIMESTAMP NULL,
    RESERVATION_START_TIME                  TIMESTAMP NULL,
    RESOURCE_CS_TOKEN                       VARCHAR(255),
    SCRATCH_LOCATION                        VARCHAR(255),
    USAGE_REPORTING_GATEWAY_ID              VARCHAR(255),
    SSH_ACCOUNT_PROVISIONER                 VARCHAR(255),
    SSH_ACCOUNT_PROVISIONER_ADDITIONAL_INFO VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID, RESOURCE_ID),
    CONSTRAINT FK_CRP_GP FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY_PROFILE (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SSH_ACCOUNT_PROVISIONER_CONFIG (
    GATEWAY_ID   VARCHAR(255) NOT NULL,
    RESOURCE_ID  VARCHAR(255) NOT NULL,
    CONFIG_NAME  VARCHAR(255) NOT NULL,
    CONFIG_VALUE VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID, RESOURCE_ID, CONFIG_NAME),
    CONSTRAINT FK_SAPC_CRP FOREIGN KEY (GATEWAY_ID, RESOURCE_ID)
        REFERENCES COMPUTE_RESOURCE_PREFERENCE (GATEWAY_ID, RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS STORAGE_PREFERENCE (
    GATEWAY_ID          VARCHAR(255) NOT NULL,
    STORAGE_RESOURCE_ID VARCHAR(255) NOT NULL,
    FS_ROOT_LOCATION    VARCHAR(255),
    LOGIN_USERNAME      VARCHAR(255),
    RESOURCE_CS_TOKEN   VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID, STORAGE_RESOURCE_ID),
    CONSTRAINT FK_SP_GP FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY_PROFILE (GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GROUP_COMPUTE_RESOURCE_PREFERENCE (
    RESOURCE_ID                 VARCHAR(255) NOT NULL,
    GROUP_RESOURCE_PROFILE_ID   VARCHAR(255) NOT NULL,
    RESOURCE_TYPE               VARCHAR(31) NOT NULL,
    LOGIN_USERNAME              VARCHAR(255),
    SCRATCH_LOCATION            VARCHAR(255),
    OVERRIDE_BY_AIRAVATA        SMALLINT,
    PREFERED_DATA_MOVE_PROTOCOL VARCHAR(255),
    PREFERED_JOB_SUB_PROTOCOL   VARCHAR(255),
    RESOURCE_CS_TOKEN           VARCHAR(255),
    PRIMARY KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID),
    CONSTRAINT FK_GCRP_GRP FOREIGN KEY (GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_RESOURCE_PROFILE (GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SLURM_GROUP_COMPUTE_RESOURCE_PREFERENCE (
    RESOURCE_ID                             VARCHAR(255) NOT NULL,
    GROUP_RESOURCE_PROFILE_ID               VARCHAR(255) NOT NULL,
    ALLOCATION_PROJECT_NUMBER               VARCHAR(255),
    PREFERED_BATCH_QUEUE                    VARCHAR(255),
    QUALITY_OF_SERVICE                      VARCHAR(255),
    USAGE_REPORTING_GATEWAY_ID              VARCHAR(255),
    SSH_ACCOUNT_PROVISIONER                 VARCHAR(255),
    SSH_ACCOUNT_PROVISIONER_ADDITIONAL_INFO VARCHAR(255),
    PRIMARY KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID),
    CONSTRAINT FK_SGCRP_GCRP FOREIGN KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_COMPUTE_RESOURCE_PREFERENCE (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AWS_GROUP_COMPUTE_RESOURCE_PREFERENCE (
    RESOURCE_ID               VARCHAR(255) NOT NULL,
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255) NOT NULL,
    AWS_REGION                VARCHAR(255) NOT NULL,
    PREFERRED_AMI_ID          VARCHAR(255) NOT NULL,
    PREFERRED_INSTANCE_TYPE   VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID),
    CONSTRAINT FK_AGCRP_GCRP FOREIGN KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_COMPUTE_RESOURCE_PREFERENCE (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GRP_SSH_ACC_PROV_CONFIG (
    RESOURCE_ID               VARCHAR(255) NOT NULL,
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255) NOT NULL,
    CONFIG_NAME               VARCHAR(255) NOT NULL,
    CONFIG_VALUE              VARCHAR(255),
    PRIMARY KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID, CONFIG_NAME),
    CONSTRAINT FK_GSAPC_GCRP FOREIGN KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_COMPUTE_RESOURCE_PREFERENCE (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_RESERVATION (
    RESERVATION_ID            VARCHAR(255) NOT NULL,
    RESERVATION_NAME          VARCHAR(255) NOT NULL,
    START_TIME                TIMESTAMP NOT NULL,
    END_TIME                  TIMESTAMP NOT NULL,
    RESOURCE_ID               VARCHAR(255) NOT NULL,
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESERVATION_ID),
    CONSTRAINT FK_CRR_GCRP FOREIGN KEY (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_COMPUTE_RESOURCE_PREFERENCE (RESOURCE_ID, GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_RESERVATION_QUEUE (
    RESERVATION_ID VARCHAR(255) NOT NULL,
    QUEUE_NAME     VARCHAR(255) NOT NULL,
    CONSTRAINT FK_CRRQ_CRR FOREIGN KEY (RESERVATION_ID) REFERENCES COMPUTE_RESOURCE_RESERVATION (RESERVATION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_POLICY (
    RESOURCE_POLICY_ID        VARCHAR(255) NOT NULL,
    COMPUTE_RESOURCE_ID       VARCHAR(255),
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESOURCE_POLICY_ID),
    CONSTRAINT FK_CRP2_GRP FOREIGN KEY (GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_RESOURCE_PROFILE (GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS COMPUTE_RESOURCE_POLICY_QUEUES (
    RESOURCE_POLICY_ID VARCHAR(255) NOT NULL,
    QUEUE_NAME         VARCHAR(255),
    CONSTRAINT FK_CRPQ_CRP FOREIGN KEY (RESOURCE_POLICY_ID) REFERENCES COMPUTE_RESOURCE_POLICY (RESOURCE_POLICY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS BATCH_QUEUE_RESOURCE_POLICY (
    RESOURCE_POLICY_ID        VARCHAR(255) NOT NULL,
    COMPUTE_RESOURCE_ID       VARCHAR(255),
    GROUP_RESOURCE_PROFILE_ID VARCHAR(255) NOT NULL,
    QUEUE_NAME                VARCHAR(255),
    MAX_ALLOWED_NODES         INT,
    MAX_ALLOWED_CORES         INT,
    MAX_ALLOWED_WALLTIME      INT,
    PRIMARY KEY (RESOURCE_POLICY_ID),
    CONSTRAINT FK_BQRP_GRP FOREIGN KEY (GROUP_RESOURCE_PROFILE_ID)
        REFERENCES GROUP_RESOURCE_PROFILE (GROUP_RESOURCE_PROFILE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_MODULE (
    MODULE_ID      VARCHAR(255) NOT NULL,
    CREATION_TIME  TIMESTAMP NOT NULL,
    GATEWAY_ID     VARCHAR(255) NOT NULL,
    MODULE_DESC    VARCHAR(255),
    MODULE_NAME    VARCHAR(255),
    MODULE_VERSION VARCHAR(255),
    UPDATE_TIME    TIMESTAMP NOT NULL,
    PRIMARY KEY (MODULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_INTERFACE (
    INTERFACE_ID              VARCHAR(255) NOT NULL,
    APPLICATION_DESCRIPTION   VARCHAR(255),
    APPLICATION_NAME          VARCHAR(255),
    ARCHIVE_WORKING_DIRECTORY TINYINT(1),
    CREATION_TIME             TIMESTAMP NOT NULL,
    GATEWAY_ID                VARCHAR(255) NOT NULL,
    UPDATE_TIME               TIMESTAMP NOT NULL,
    HAS_OPTIONAL_FILE_INPUTS  TINYINT(1),
    CLEAN_AFTER_STAGED        TINYINT(1),
    PRIMARY KEY (INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APP_MODULE_MAPPING (
    INTERFACE_ID VARCHAR(255) NOT NULL,
    MODULE_ID    VARCHAR(255) NOT NULL,
    PRIMARY KEY (INTERFACE_ID, MODULE_ID),
    CONSTRAINT FK_AMM_AI FOREIGN KEY (INTERFACE_ID) REFERENCES APPLICATION_INTERFACE (INTERFACE_ID),
    CONSTRAINT FK_AMM_AM FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (MODULE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_INPUT (
    INTERFACE_ID            VARCHAR(255) NOT NULL,
    INPUT_KEY               VARCHAR(255) NOT NULL,
    APP_ARGUMENT            VARCHAR(255),
    DATA_STAGED             TINYINT(1),
    DATA_TYPE               VARCHAR(255),
    INPUT_ORDER             INT,
    INPUT_VALUE             VARCHAR(255),
    IS_REQUIRED             TINYINT(1),
    METADATA                VARCHAR(4096),
    REQUIRED_TO_COMMANDLINE TINYINT(1),
    STANDARD_INPUT          TINYINT(1),
    USER_FRIENDLY_DESC      LONGTEXT,
    IS_READ_ONLY            TINYINT(1),
    OVERRIDE_FILENAME       VARCHAR(255),
    PRIMARY KEY (INTERFACE_ID, INPUT_KEY),
    CONSTRAINT FK_AI_AIF FOREIGN KEY (INTERFACE_ID) REFERENCES APPLICATION_INTERFACE (INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_OUTPUT (
    INTERFACE_ID            VARCHAR(255) NOT NULL,
    OUTPUT_KEY              VARCHAR(255) NOT NULL,
    APP_ARGUMENT            VARCHAR(255),
    DATA_MOVEMENT           TINYINT(1),
    DATA_NAME_LOCATION      VARCHAR(255),
    DATA_TYPE               VARCHAR(255),
    IS_REQUIRED             TINYINT(1),
    OUTPUT_STREAMING        TINYINT(1),
    OUTPUT_VALUE            VARCHAR(255),
    REQUIRED_TO_COMMANDLINE TINYINT(1),
    SEARCH_QUERY            VARCHAR(255),
    METADATA                VARCHAR(4096),
    PRIMARY KEY (INTERFACE_ID, OUTPUT_KEY),
    CONSTRAINT FK_AO_AIF FOREIGN KEY (INTERFACE_ID) REFERENCES APPLICATION_INTERFACE (INTERFACE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_DEPLOYMENT (
    DEPLOYMENT_ID       VARCHAR(255) NOT NULL,
    APPLICATION_DESC    VARCHAR(255),
    CREATION_TIME       TIMESTAMP NOT NULL,
    ENV_MODULE_LOAD_CMD VARCHAR(255),
    EXECUTABLE_PATH     VARCHAR(255),
    GATEWAY_ID          VARCHAR(255) NOT NULL,
    parallelism         VARCHAR(255),
    UPDATE_TIME         TIMESTAMP NOT NULL,
    COMPUTE_HOSTID      VARCHAR(255),
    APP_MODULE_ID       VARCHAR(255),
    DEFAULT_NODE_COUNT  INT,
    DEFAULT_CPU_COUNT   INT,
    DEFAULT_WALLTIME    INT,
    DEFAULT_QUEUE_NAME  VARCHAR(255),
    EDITABLE_BY_USER    TINYINT(1),
    PRIMARY KEY (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS MODULE_LOAD_CMD (
    APP_DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    CMD               VARCHAR(255) NOT NULL,
    COMMAND_ORDER     INT,
    PRIMARY KEY (APP_DEPLOYMENT_ID, CMD),
    CONSTRAINT FK_MLC_AD FOREIGN KEY (APP_DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APP_ENVIRONMENT (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME          VARCHAR(255) NOT NULL,
    VALUE         VARCHAR(255),
    ENV_ORDER     INT,
    PRIMARY KEY (DEPLOYMENT_ID, NAME),
    CONSTRAINT FK_AE_AD FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LIBRARY_PREPAND_PATH (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME          VARCHAR(255) NOT NULL,
    VALUE         VARCHAR(255),
    PRIMARY KEY (DEPLOYMENT_ID, NAME),
    CONSTRAINT FK_LPP_AD FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS LIBRARY_APEND_PATH (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    NAME          VARCHAR(255) NOT NULL,
    VALUE         VARCHAR(255),
    PRIMARY KEY (DEPLOYMENT_ID, NAME),
    CONSTRAINT FK_LAP_AD FOREIGN KEY (DEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PREJOB_COMMAND (
    APPDEPLOYMENT_ID VARCHAR(255) NOT NULL,
    COMMAND          VARCHAR(255) NOT NULL,
    COMMAND_ORDER    INT,
    PRIMARY KEY (APPDEPLOYMENT_ID, COMMAND),
    CONSTRAINT FK_PC2_AD FOREIGN KEY (APPDEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS POSTJOB_COMMAND (
    APPDEPLOYMENT_ID VARCHAR(255) NOT NULL,
    COMMAND          VARCHAR(255) NOT NULL,
    COMMAND_ORDER    INT,
    PRIMARY KEY (APPDEPLOYMENT_ID, COMMAND),
    CONSTRAINT FK_POC_AD FOREIGN KEY (APPDEPLOYMENT_ID) REFERENCES APPLICATION_DEPLOYMENT (DEPLOYMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_RESOURCE_PROFILE (
    USER_ID                        VARCHAR(255) NOT NULL,
    GATEWAY_ID                     VARCHAR(255) NOT NULL,
    CS_TOKEN                       VARCHAR(255),
    IDENTITY_SERVER_PWD_CRED_TOKEN VARCHAR(255),
    IDENTITY_SERVER_TENANT         VARCHAR(255),
    CREATION_TIME                  TIMESTAMP NULL,
    UPDATE_TIME                    TIMESTAMP NULL,
    PRIMARY KEY (USER_ID, GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_COMPUTE_RESOURCE_PREFERENCE (
    RESOURCE_ID               VARCHAR(255) NOT NULL,
    USER_ID                   VARCHAR(255) NOT NULL,
    GATEWAY_ID                VARCHAR(255) NOT NULL,
    PREFERED_BATCH_QUEUE      VARCHAR(255),
    RESOURCE_CS_TOKEN         VARCHAR(255),
    LOGIN_USERNAME            VARCHAR(255),
    ALLOCATION_PROJECT_NUMBER VARCHAR(255),
    QUALITY_OF_SERVICE        VARCHAR(255),
    RESERVATION               VARCHAR(255),
    RESERVATION_START_TIME    TIMESTAMP NULL,
    RESERVATION_END_TIME      TIMESTAMP NULL,
    SCRATCH_LOCATION          VARCHAR(255),
    VALIDATED                 TINYINT(1),
    PRIMARY KEY (RESOURCE_ID, USER_ID, GATEWAY_ID),
    CONSTRAINT FK_UCRP_URP FOREIGN KEY (USER_ID, GATEWAY_ID)
        REFERENCES USER_RESOURCE_PROFILE (USER_ID, GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_STORAGE_PREFERENCE (
    STORAGE_RESOURCE_ID VARCHAR(255) NOT NULL,
    USER_ID             VARCHAR(255) NOT NULL,
    GATEWAY_ID          VARCHAR(255) NOT NULL,
    RESOURCE_CS_TOKEN   VARCHAR(255),
    FS_ROOT_LOCATION    VARCHAR(255),
    LOGIN_USERNAME      VARCHAR(255),
    PRIMARY KEY (STORAGE_RESOURCE_ID, USER_ID, GATEWAY_ID),
    CONSTRAINT FK_USP_URP FOREIGN KEY (USER_ID, GATEWAY_ID)
        REFERENCES USER_RESOURCE_PROFILE (USER_ID, GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSER (
    PARSER_ID         VARCHAR(255) NOT NULL,
    IMAGE_NAME        VARCHAR(255),
    OUTPUT_DIR_PATH   VARCHAR(255),
    INPUT_DIR_PATH    VARCHAR(255),
    EXECUTION_COMMAND VARCHAR(255),
    GATEWAY_ID        VARCHAR(255),
    PRIMARY KEY (PARSER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSER_INPUT (
    PARSER_INPUT_ID       VARCHAR(255) NOT NULL,
    PARSER_INPUT_NAME     VARCHAR(255),
    PARSER_INPUT_REQUIRED TINYINT(1),
    PARSER_ID             VARCHAR(255),
    INPUT_TYPE            VARCHAR(255),
    PRIMARY KEY (PARSER_INPUT_ID),
    CONSTRAINT FK_PI_P FOREIGN KEY (PARSER_ID) REFERENCES PARSER (PARSER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSER_OUTPUT (
    PARSER_OUTPUT_ID       VARCHAR(255) NOT NULL,
    PARSER_OUTPUT_NAME     VARCHAR(255),
    PARSER_OUTPUT_REQUIRED TINYINT(1),
    PARSER_ID              VARCHAR(255),
    OUTPUT_TYPE            VARCHAR(255),
    PRIMARY KEY (PARSER_OUTPUT_ID),
    CONSTRAINT FK_PO_P FOREIGN KEY (PARSER_ID) REFERENCES PARSER (PARSER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSING_TEMPLATE (
    PARSING_TEMPLATE_ID VARCHAR(255) NOT NULL,
    APP_INTERFACE_ID    VARCHAR(255),
    GATEWAY_ID          VARCHAR(255),
    PRIMARY KEY (PARSING_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSING_TEMPLATE_INPUT (
    PARSING_TEMPLATE_INPUT_ID VARCHAR(255) NOT NULL,
    TARGET_PARSER_INPUT_ID    VARCHAR(255),
    APPLICATION_OUTPUT_NAME   VARCHAR(255),
    VALUE                     VARCHAR(255),
    PARSING_TEMPLATE_ID       VARCHAR(255),
    PRIMARY KEY (PARSING_TEMPLATE_INPUT_ID),
    CONSTRAINT FK_PTI_PI FOREIGN KEY (TARGET_PARSER_INPUT_ID) REFERENCES PARSER_INPUT (PARSER_INPUT_ID),
    CONSTRAINT FK_PTI_PT FOREIGN KEY (PARSING_TEMPLATE_ID) REFERENCES PARSING_TEMPLATE (PARSING_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSER_CONNECTOR (
    PARSER_CONNECTOR_ID VARCHAR(255) NOT NULL,
    PARENT_PARSER_ID    VARCHAR(255),
    CHILD_PARSER_ID     VARCHAR(255),
    PARSING_TEMPLATE_ID VARCHAR(255),
    PRIMARY KEY (PARSER_CONNECTOR_ID),
    CONSTRAINT FK_PC3_PP FOREIGN KEY (PARENT_PARSER_ID) REFERENCES PARSER (PARSER_ID),
    CONSTRAINT FK_PC3_CP FOREIGN KEY (CHILD_PARSER_ID) REFERENCES PARSER (PARSER_ID),
    CONSTRAINT FK_PC3_PT FOREIGN KEY (PARSING_TEMPLATE_ID) REFERENCES PARSING_TEMPLATE (PARSING_TEMPLATE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PARSER_CONNECTOR_INPUT (
    PARSER_CONNECTOR_INPUT_ID VARCHAR(255) NOT NULL,
    PARSER_INPUT_ID           VARCHAR(255),
    PARSER_OUTPUT_ID          VARCHAR(255),
    VALUE                     VARCHAR(255),
    PARSER_CONNECTOR_ID       VARCHAR(255),
    PRIMARY KEY (PARSER_CONNECTOR_INPUT_ID),
    CONSTRAINT FK_PCI_PI FOREIGN KEY (PARSER_INPUT_ID) REFERENCES PARSER_INPUT (PARSER_INPUT_ID),
    CONSTRAINT FK_PCI_PO FOREIGN KEY (PARSER_OUTPUT_ID) REFERENCES PARSER_OUTPUT (PARSER_OUTPUT_ID),
    CONSTRAINT FK_PCI_PC FOREIGN KEY (PARSER_CONNECTOR_ID) REFERENCES PARSER_CONNECTOR (PARSER_CONNECTOR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 3. AIRAVATA WORKFLOW CATALOG
-- ============================================================================

CREATE TABLE IF NOT EXISTS AIRAVATA_WORKFLOW (
    ID            VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255),
    DESCRIPTION   VARCHAR(255),
    CREATED_AT    TIMESTAMP NULL,
    UPDATED_AT    TIMESTAMP NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AIRAVATA_WORKFLOW_STATUS (
    ID          VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    STATE       VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    UPDATED_AT  TIMESTAMP NULL,
    PRIMARY KEY (ID, WORKFLOW_ID),
    CONSTRAINT FK_AW_STATUS_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS AIRAVATA_WORKFLOW_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    WORKFLOW_ID              VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, WORKFLOW_ID),
    CONSTRAINT FK_AW_ERROR_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WORKFLOW_DATA_BLOCK (
    ID          VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255),
    VALUE       VARCHAR(255),
    DATA_TYPE   VARCHAR(255),
    CREATED_AT  TIMESTAMP NULL,
    UPDATED_AT  TIMESTAMP NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_DATA_BLOCK_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WORKFLOW_HANDLER (
    ID          VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    TYPE        VARCHAR(255),
    CREATED_AT  TIMESTAMP NULL,
    UPDATED_AT  TIMESTAMP NULL,
    PRIMARY KEY (ID, WORKFLOW_ID),
    CONSTRAINT FK_HANDLER_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WORKFLOW_APPLICATION (
    ID                       VARCHAR(255) NOT NULL,
    WORKFLOW_ID              VARCHAR(255) NOT NULL,
    PROCESS_ID               VARCHAR(255),
    APPLICATION_INTERFACE_ID VARCHAR(255),
    COMPUTE_RESOURCE_ID      VARCHAR(255),
    QUEUE_NAME               VARCHAR(255),
    NODE_COUNT               INT NOT NULL DEFAULT 0,
    CORE_COUNT               INT NOT NULL DEFAULT 0,
    WALL_TIME_LIMIT          INT NOT NULL DEFAULT 0,
    PHYSICAL_MEMORY          INT NOT NULL DEFAULT 0,
    CREATED_AT               TIMESTAMP NULL,
    UPDATED_AT               TIMESTAMP NULL,
    PRIMARY KEY (ID, WORKFLOW_ID),
    CONSTRAINT FK_APPLICATION_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS WORKFLOW_CONNECTION (
    ID               VARCHAR(255) NOT NULL,
    WORKFLOW_ID      VARCHAR(255) NOT NULL,
    DATA_BLOCK_ID    VARCHAR(255),
    FROM_TYPE        VARCHAR(255),
    FROM_ID          VARCHAR(255),
    FROM_OUTPUT_NAME VARCHAR(255),
    TO_TYPE          VARCHAR(255),
    TO_ID            VARCHAR(255),
    TO_INPUT_NAME    VARCHAR(255),
    CREATED_AT       TIMESTAMP NULL,
    UPDATED_AT       TIMESTAMP NULL,
    PRIMARY KEY (ID, WORKFLOW_ID),
    CONSTRAINT FK_CONNECTION_WORKFLOW FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW (ID),
    CONSTRAINT FK_CONNECTION_DATA_BLOCK FOREIGN KEY (DATA_BLOCK_ID) REFERENCES WORKFLOW_DATA_BLOCK (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_STATUS (
    ID             VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255) NOT NULL,
    STATE          VARCHAR(255),
    DESCRIPTION    VARCHAR(255),
    UPDATED_AT     TIMESTAMP NULL,
    PRIMARY KEY (ID, APPLICATION_ID),
    CONSTRAINT FK_APP_STATUS_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES WORKFLOW_APPLICATION (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS APPLICATION_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    APPLICATION_ID           VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, APPLICATION_ID),
    CONSTRAINT FK_APP_ERROR_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES WORKFLOW_APPLICATION (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HANDLER_STATUS (
    ID          VARCHAR(255) NOT NULL,
    HANDLER_ID  VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    STATE       VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    UPDATED_AT  TIMESTAMP NULL,
    PRIMARY KEY (ID, HANDLER_ID),
    CONSTRAINT FK_HANDLER_STATUS_HANDLER FOREIGN KEY (HANDLER_ID, WORKFLOW_ID)
        REFERENCES WORKFLOW_HANDLER (ID, WORKFLOW_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HANDLER_ERROR (
    ERROR_ID                 VARCHAR(255) NOT NULL,
    HANDLER_ID               VARCHAR(255) NOT NULL,
    WORKFLOW_ID              VARCHAR(255) NOT NULL,
    CREATION_TIME            TIMESTAMP NULL,
    ACTUAL_ERROR_MESSAGE     LONGTEXT,
    USER_FRIENDLY_MESSAGE    LONGTEXT,
    TRANSIENT_OR_PERSISTENT  TINYINT(1) NOT NULL DEFAULT 0,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID, HANDLER_ID),
    CONSTRAINT FK_HANDLER_ERROR_HANDLER FOREIGN KEY (HANDLER_ID, WORKFLOW_ID)
        REFERENCES WORKFLOW_HANDLER (ID, WORKFLOW_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HANDLER_INPUT (
    HANDLER_ID                        VARCHAR(255) NOT NULL,
    NAME                              VARCHAR(255) NOT NULL,
    WORKFLOW_ID                       VARCHAR(255) NOT NULL,
    VALUE                             LONGTEXT,
    TYPE                              VARCHAR(255),
    APPLICATION_ARGUMENT              VARCHAR(255),
    STANDARD_INPUT                    TINYINT(1) NOT NULL DEFAULT 0,
    USER_FRIENDLY_DESCRIPTION         VARCHAR(255),
    METADATA                          VARCHAR(4096),
    INPUT_ORDER                       INT NOT NULL DEFAULT 0,
    IS_REQUIRED                       TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_COMMAND_LINE TINYINT(1) NOT NULL DEFAULT 0,
    DATA_STAGED                       TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID               VARCHAR(255),
    IS_READ_ONLY                      TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (HANDLER_ID, NAME),
    CONSTRAINT FK_HANDLER_INPUT_HANDLER FOREIGN KEY (HANDLER_ID, WORKFLOW_ID)
        REFERENCES WORKFLOW_HANDLER (ID, WORKFLOW_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS HANDLER_OUTPUT (
    HANDLER_ID                        VARCHAR(255) NOT NULL,
    NAME                              VARCHAR(255) NOT NULL,
    WORKFLOW_ID                       VARCHAR(255) NOT NULL,
    VALUE                             LONGTEXT,
    TYPE                              VARCHAR(255),
    APPLICATION_ARGUMENT              VARCHAR(255),
    IS_REQUIRED                       TINYINT(1) NOT NULL DEFAULT 0,
    REQUIRED_TO_ADDED_TO_COMMAND_LINE TINYINT(1) NOT NULL DEFAULT 0,
    DATA_MOVEMENT                     TINYINT(1) NOT NULL DEFAULT 0,
    LOCATION                          VARCHAR(255),
    SEARCH_QUERY                      VARCHAR(255),
    OUTPUT_STREAMING                  TINYINT(1) NOT NULL DEFAULT 0,
    STORAGE_RESOURCE_ID               VARCHAR(255),
    PRIMARY KEY (HANDLER_ID, NAME),
    CONSTRAINT FK_HANDLER_OUTPUT_HANDLER FOREIGN KEY (HANDLER_ID, WORKFLOW_ID)
        REFERENCES WORKFLOW_HANDLER (ID, WORKFLOW_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 4. REPLICA CATALOG
-- ============================================================================

CREATE TABLE IF NOT EXISTS CONFIGURATION (
    CONFIG_KEY VARCHAR(255) NOT NULL,
    CONFIG_VAL VARCHAR(255) NOT NULL,
    PRIMARY KEY (CONFIG_KEY, CONFIG_VAL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_PRODUCT (
    PRODUCT_URI        VARCHAR(255) NOT NULL,
    GATEWAY_ID         VARCHAR(255),
    PRODUCT_NAME       LONGTEXT,
    PRODUCT_DESCRIPTION VARCHAR(255),
    OWNER_NAME         VARCHAR(255),
    PARENT_PRODUCT_URI VARCHAR(255),
    PRODUCT_SIZE       INT NOT NULL DEFAULT 0,
    CREATION_TIME      TIMESTAMP NULL,
    LAST_MODIFIED_TIME TIMESTAMP NULL,
    PRODUCT_TYPE       VARCHAR(255),
    PRIMARY KEY (PRODUCT_URI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_PRODUCT_METADATA (
    PRODUCT_URI    VARCHAR(255) NOT NULL,
    METADATA_KEY   VARCHAR(255) NOT NULL,
    METADATA_VALUE VARCHAR(255),
    PRIMARY KEY (PRODUCT_URI, METADATA_KEY),
    CONSTRAINT FK_DATA_PRODUCT_METADATA_PRODUCT FOREIGN KEY (PRODUCT_URI) REFERENCES DATA_PRODUCT (PRODUCT_URI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_REPLICA_LOCATION (
    REPLICA_ID                VARCHAR(255) NOT NULL,
    PRODUCT_URI               VARCHAR(255) NOT NULL,
    REPLICA_NAME              LONGTEXT,
    REPLICA_DESCRIPTION       VARCHAR(255),
    STORAGE_RESOURCE_ID       VARCHAR(255),
    FILE_PATH                 VARCHAR(255),
    CREATION_TIME             TIMESTAMP NULL,
    LAST_MODIFIED_TIME        TIMESTAMP NULL,
    VALID_UNTIL_TIME          TIMESTAMP NULL,
    REPLICA_LOCATION_CATEGORY VARCHAR(255),
    REPLICA_PERSISTENT_TYPE   VARCHAR(255),
    PRIMARY KEY (REPLICA_ID),
    CONSTRAINT FK_DATA_REPLICA_PRODUCT FOREIGN KEY (PRODUCT_URI) REFERENCES DATA_PRODUCT (PRODUCT_URI)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_REPLICA_METADATA (
    REPLICA_ID     VARCHAR(255) NOT NULL,
    METADATA_KEY   VARCHAR(255) NOT NULL,
    METADATA_VALUE VARCHAR(255),
    PRIMARY KEY (REPLICA_ID, METADATA_KEY),
    CONSTRAINT FK_DATA_REPLICA_METADATA_REPLICA FOREIGN KEY (REPLICA_ID) REFERENCES DATA_REPLICA_LOCATION (REPLICA_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 5. SHARING REGISTRY
-- ============================================================================

CREATE TABLE IF NOT EXISTS DOMAIN (
    DOMAIN_ID             VARCHAR(255) NOT NULL,
    NAME                  VARCHAR(255),
    DESCRIPTION           VARCHAR(255),
    CREATED_TIME          BIGINT,
    UPDATED_TIME          BIGINT,
    INITIAL_USER_GROUP_ID VARCHAR(255),
    PRIMARY KEY (DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHARING_USER (
    USER_ID      VARCHAR(255) NOT NULL,
    DOMAIN_ID    VARCHAR(255) NOT NULL,
    USER_NAME    VARCHAR(255),
    FIRST_NAME   VARCHAR(255),
    LAST_NAME    VARCHAR(255),
    EMAIL        VARCHAR(255),
    ICON         LONGBLOB,
    CREATED_TIME BIGINT,
    UPDATED_TIME BIGINT,
    PRIMARY KEY (USER_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_GROUP (
    GROUP_ID          VARCHAR(255) NOT NULL,
    DOMAIN_ID         VARCHAR(255) NOT NULL,
    NAME              VARCHAR(255),
    DESCRIPTION       VARCHAR(255),
    OWNER_ID          VARCHAR(255),
    GROUP_TYPE        VARCHAR(255),
    GROUP_CARDINALITY VARCHAR(255),
    CREATED_TIME      BIGINT,
    UPDATED_TIME      BIGINT,
    PRIMARY KEY (GROUP_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GROUP_ADMIN (
    GROUP_ID  VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255) NOT NULL,
    ADMIN_ID  VARCHAR(255) NOT NULL,
    PRIMARY KEY (GROUP_ID, DOMAIN_ID, ADMIN_ID),
    CONSTRAINT FK_GROUP_ADMIN_USER_GROUP FOREIGN KEY (GROUP_ID, DOMAIN_ID)
        REFERENCES USER_GROUP (GROUP_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS GROUP_MEMBERSHIP (
    PARENT_ID    VARCHAR(255) NOT NULL,
    CHILD_ID     VARCHAR(255) NOT NULL,
    DOMAIN_ID    VARCHAR(255) NOT NULL,
    CHILD_TYPE   VARCHAR(255),
    CREATED_TIME BIGINT,
    UPDATED_TIME BIGINT,
    PRIMARY KEY (PARENT_ID, CHILD_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ENTITY_TYPE (
    ENTITY_TYPE_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID      VARCHAR(255) NOT NULL,
    NAME           VARCHAR(255),
    DESCRIPTION    VARCHAR(255),
    CREATED_TIME   BIGINT,
    UPDATED_TIME   BIGINT,
    PRIMARY KEY (ENTITY_TYPE_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PERMISSION_TYPE (
    PERMISSION_TYPE_ID VARCHAR(255) NOT NULL,
    DOMAIN_ID          VARCHAR(255) NOT NULL,
    NAME               VARCHAR(255),
    DESCRIPTION        VARCHAR(255),
    CREATED_TIME       BIGINT,
    UPDATED_TIME       BIGINT,
    PRIMARY KEY (PERMISSION_TYPE_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ENTITY (
    ENTITY_ID                     VARCHAR(255) NOT NULL,
    DOMAIN_ID                     VARCHAR(255) NOT NULL,
    ENTITY_TYPE_ID                VARCHAR(255),
    OWNER_ID                      VARCHAR(255),
    PARENT_ENTITY_ID              VARCHAR(255),
    NAME                          VARCHAR(255),
    DESCRIPTION                   VARCHAR(255),
    BINARY_DATA                   LONGBLOB,
    FULL_TEXT                     VARCHAR(255),
    ORIGINAL_ENTITY_CREATION_TIME BIGINT,
    SHARED_COUNT                  BIGINT,
    CREATED_TIME                  BIGINT,
    UPDATED_TIME                  BIGINT,
    PRIMARY KEY (ENTITY_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SHARING (
    PERMISSION_TYPE_ID  VARCHAR(152) NOT NULL,
    ENTITY_ID           VARCHAR(152) NOT NULL,
    GROUP_ID            VARCHAR(152) NOT NULL,
    INHERITED_PARENT_ID VARCHAR(152) NOT NULL,
    DOMAIN_ID           VARCHAR(152) NOT NULL,
    SHARING_TYPE        VARCHAR(255),
    CREATED_TIME        BIGINT,
    UPDATED_TIME        BIGINT,
    PRIMARY KEY (PERMISSION_TYPE_ID, ENTITY_ID, GROUP_ID, INHERITED_PARENT_ID, DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 6. PROFILE SERVICE
-- ============================================================================

CREATE TABLE IF NOT EXISTS TENANT_GATEWAY (
    AIRAVATA_INTERNAL_GATEWAY_ID        VARCHAR(255) NOT NULL,
    GATEWAY_ID                          VARCHAR(255),
    GATEWAY_NAME                        VARCHAR(255),
    GATEWAY_DOMAIN                      VARCHAR(255),
    EMAIL_ADDRESS                       VARCHAR(255),
    GATEWAY_APPROVAL_STATUS             VARCHAR(255),
    GATEWAY_ACRONYM                     VARCHAR(255),
    GATEWAY_URL                         VARCHAR(255),
    GATEWAY_PUBLIC_ABSTRACT             VARCHAR(255),
    GATEWAY_REVIEW_PROPOSAL_DESCRIPTION VARCHAR(255),
    GATEWAY_ADMIN_FIRST_NAME            VARCHAR(255),
    GATEWAY_ADMIN_LAST_NAME             VARCHAR(255),
    GATEWAY_ADMIN_EMAIL                 VARCHAR(255),
    IDENTITY_SERVER_USERNAME            VARCHAR(255),
    IDENTITY_SERVER_PASSWORD_TOKEN      VARCHAR(255),
    DECLINED_REASON                     VARCHAR(255),
    OAUTH_CLIENT_ID                     VARCHAR(255),
    OAUTH_CLIENT_SECRET                 VARCHAR(255),
    REQUEST_CREATION_TIME               BIGINT NOT NULL DEFAULT 0,
    REQUESTER_USERNAME                  VARCHAR(255),
    PRIMARY KEY (AIRAVATA_INTERNAL_GATEWAY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    USER_ID                   VARCHAR(255),
    GATEWAY_ID                VARCHAR(255),
    USER_MODEL_VERSION        VARCHAR(255),
    FIRST_NAME                VARCHAR(255),
    LAST_NAME                 VARCHAR(255),
    MIDDLE_NAME               VARCHAR(255),
    NAME_PREFIX               VARCHAR(255),
    NAME_SUFFIX               VARCHAR(255),
    ORCID_ID                  VARCHAR(255),
    COUNTRY                   VARCHAR(255),
    HOME_ORGANIZATION         VARCHAR(255),
    ORIGINATION_AFFILIATION   VARCHAR(255),
    CREATION_TIME             DATETIME NULL,
    LAST_ACCESS_TIME          DATETIME NULL,
    VALID_UNTIL               DATETIME NULL,
    STATE                     VARCHAR(255),
    COMMENTS                  LONGTEXT,
    GPG_KEY                   LONGTEXT,
    TIME_ZONE                 VARCHAR(255),
    PRIMARY KEY (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE_EMAIL (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    EMAIL                     VARCHAR(255),
    CONSTRAINT FK_USER_PROFILE_EMAIL FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE_PHONE (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    PHONE                     VARCHAR(255),
    CONSTRAINT FK_USER_PROFILE_PHONE FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE_NATIONALITY (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    NATIONALITY               VARCHAR(255),
    CONSTRAINT FK_USER_PROFILE_NATIONALITY FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS USER_PROFILE_LABELED_URI (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    LABELED_URI               VARCHAR(255),
    CONSTRAINT FK_USER_PROFILE_LABELED_URI FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    GENDER                    VARCHAR(255),
    PRIMARY KEY (AIRAVATA_INTERNAL_USER_ID),
    CONSTRAINT FK_NSF_DEMOGRAPHIC_USER_PROFILE FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_ETHNICITY (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    ETHNICITY                 VARCHAR(255),
    CONSTRAINT FK_NSF_ETHNICITY FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES NSF_DEMOGRAPHIC (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_RACE (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    RACE                      VARCHAR(255),
    CONSTRAINT FK_NSF_RACE FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES NSF_DEMOGRAPHIC (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NSF_DEMOGRAPHIC_DISABILITY (
    AIRAVATA_INTERNAL_USER_ID VARCHAR(255) NOT NULL,
    DISABILITY                VARCHAR(255),
    CONSTRAINT FK_NSF_DISABILITY FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES NSF_DEMOGRAPHIC (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS CUSTOMIZED_DASHBOARD (
    AIRAVATA_INTERNAL_USER_ID  VARCHAR(255) NOT NULL,
    ENABLED_EXPERIMENT_ID      VARCHAR(255),
    ENABLED_NAME               VARCHAR(255),
    ENABLED_DESCRIPTION        VARCHAR(255),
    ENABLED_PROJECT            VARCHAR(255),
    ENABLED_OWNER              VARCHAR(255),
    ENABLED_APPLICATION        VARCHAR(255),
    ENABLED_COMPUTE_RESOURCE   VARCHAR(255),
    ENABLED_JOB_NAME           VARCHAR(255),
    ENABLED_JOB_ID             VARCHAR(255),
    ENABLED_JOB_STATUS         VARCHAR(255),
    ENABLED_JOB_CREATION_TIME  VARCHAR(255),
    ENABLED_NOTIFICATIONS_TO   VARCHAR(255),
    ENABLED_WORKING_DIR        VARCHAR(255),
    ENABLED_JOB_DESCRIPTION    VARCHAR(255),
    ENABLED_CREATION_TIME      VARCHAR(255),
    ENABLED_LAST_MODIFIED_TIME VARCHAR(255),
    ENABLED_WALL_TIME          VARCHAR(255),
    ENABLED_CPU_COUNT          VARCHAR(255),
    ENABLED_NODE_COUNT         VARCHAR(255),
    ENABLED_QUEUE              VARCHAR(255),
    ENABLED_INPUTS             VARCHAR(255),
    ENABLED_OUTPUTS            VARCHAR(255),
    ENABLED_STORAGE_DIR        VARCHAR(255),
    ENABLED_ERRORS             VARCHAR(255),
    PRIMARY KEY (AIRAVATA_INTERNAL_USER_ID),
    CONSTRAINT FK_CUSTOMIZED_DASHBOARD_USER_PROFILE FOREIGN KEY (AIRAVATA_INTERNAL_USER_ID)
        REFERENCES USER_PROFILE (AIRAVATA_INTERNAL_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 7. RESEARCH SERVICE
-- ============================================================================

CREATE TABLE IF NOT EXISTS resource (
    id           VARCHAR(48) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  TEXT NOT NULL,
    header_image VARCHAR(255) NOT NULL,
    status       VARCHAR(255) NOT NULL,
    state        VARCHAR(255) NOT NULL,
    privacy      VARCHAR(255) NOT NULL,
    created_at   DATETIME(6) NOT NULL,
    updated_at   DATETIME(6) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resource_authors (
    resource_id VARCHAR(48) NOT NULL,
    author_id   VARCHAR(255),
    CONSTRAINT FK_resource_authors_resource FOREIGN KEY (resource_id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tag (
    id    VARCHAR(48) NOT NULL,
    value VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resource_tags (
    resource_id VARCHAR(48) NOT NULL,
    tag_id      VARCHAR(48) NOT NULL,
    PRIMARY KEY (resource_id, tag_id),
    CONSTRAINT FK_resource_tags_resource FOREIGN KEY (resource_id) REFERENCES resource (id),
    CONSTRAINT FK_resource_tags_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS repository_resource (
    id            VARCHAR(48) NOT NULL,
    repository_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_repository_resource_base FOREIGN KEY (id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dataset_resource (
    id         VARCHAR(48) NOT NULL,
    dataset_url VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_dataset_resource_base FOREIGN KEY (id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS model_resource (
    id                     VARCHAR(48) NOT NULL,
    application_interface_id VARCHAR(255) NOT NULL,
    version                VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_model_resource_base FOREIGN KEY (id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS notebook_resource (
    id           VARCHAR(48) NOT NULL,
    notebook_path VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_notebook_resource_base FOREIGN KEY (id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS resource_star (
    id          VARCHAR(48) NOT NULL,
    user_id     VARCHAR(255) NOT NULL,
    resource_id VARCHAR(48) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_resource_star_resource FOREIGN KEY (resource_id) REFERENCES resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS research_project (
    id                     VARCHAR(48) NOT NULL,
    name                   VARCHAR(255) NOT NULL,
    owner_id               VARCHAR(255) NOT NULL,
    repository_resource_id VARCHAR(48) NOT NULL,
    created_at             DATETIME(6) NOT NULL,
    updated_at             DATETIME(6) NOT NULL,
    state                  VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_research_project_repository FOREIGN KEY (repository_resource_id) REFERENCES repository_resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_dataset (
    project_id          VARCHAR(48) NOT NULL,
    dataset_resource_id VARCHAR(48) NOT NULL,
    PRIMARY KEY (project_id, dataset_resource_id),
    CONSTRAINT FK_project_dataset_project FOREIGN KEY (project_id) REFERENCES research_project (id),
    CONSTRAINT FK_project_dataset_dataset FOREIGN KEY (dataset_resource_id) REFERENCES dataset_resource (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS session (
    id          VARCHAR(48) NOT NULL,
    session_name VARCHAR(255) NOT NULL,
    user_id      VARCHAR(255) NOT NULL,
    project_id   VARCHAR(48) NOT NULL,
    created_at   DATETIME(6) NOT NULL,
    updated_at   DATETIME(6) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_session_project FOREIGN KEY (project_id) REFERENCES research_project (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- 8. AGENT SERVICE
-- ============================================================================

CREATE TABLE IF NOT EXISTS agent_deployment_info (
    agent_deployment_info_id VARCHAR(255) NOT NULL,
    user_frinedly_name       VARCHAR(255),
    compute_resource_id      VARCHAR(255),
    agent_application_id     VARCHAR(255),
    PRIMARY KEY (agent_deployment_info_id),
    UNIQUE KEY uq_agent_deployment_user_friendly_name (user_frinedly_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_execution (
    agent_execution_id     VARCHAR(255) NOT NULL,
    agent_id               VARCHAR(255),
    airavata_experiment_id VARCHAR(255),
    PRIMARY KEY (agent_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_execution_status (
    agent_execution_status_id              VARCHAR(255) NOT NULL,
    agent_execution_agent_execution_id     VARCHAR(255),
    updated_time                           BIGINT NOT NULL,
    status                                 TINYINT,
    additional_info                        VARCHAR(2000),
    PRIMARY KEY (agent_execution_status_id),
    CONSTRAINT FK_agent_exec_status_execution FOREIGN KEY (agent_execution_agent_execution_id)
        REFERENCES agent_execution (agent_execution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plan (
    plan_id    VARCHAR(255) NOT NULL,
    user_id    VARCHAR(255) NOT NULL,
    gateway_id VARCHAR(255) NOT NULL,
    data       TEXT,
    PRIMARY KEY (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- END OF BASELINE SCHEMA
-- ============================================================================
