/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * Apache Airavata - Unified Database Schema (V1 Baseline)
 *
 * Design principles:
 *   - Unified resource table (compute + storage in one)
 *   - Single credential table with token-based VARCHAR PK
 *   - Application with embedded I/O definitions and scripts
 *   - Experiment I/O as proper entity tables (not JSON blobs)
 *   - Experiment state as direct column (mutated by process cascade)
 *   - Events generalized with parent_id + parent_type discriminator
 *   - Research artifact JOINED inheritance hierarchy
 *   - All table names use UPPER_CASE
 *
 * Requires: MariaDB 10.2+; database must exist (run create-database.sql first).
 */

-- ============================================================================
-- 1. GATEWAY - Tenant/domain configuration
-- ============================================================================

CREATE TABLE IF NOT EXISTS GATEWAY (
    GATEWAY_ID VARCHAR(255) NOT NULL,
    GATEWAY_NAME VARCHAR(255) NOT NULL,
    GATEWAY_DOMAIN VARCHAR(255),
    EMAIL_ADDRESS VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INITIAL_USER_GROUP_ID VARCHAR(255),
    ADMINS_GROUP_ID VARCHAR(255),
    READ_ONLY_ADMINS_GROUP_ID VARCHAR(255),
    DEFAULT_GATEWAY_USERS_GROUP_ID VARCHAR(255),
    PRIMARY KEY (GATEWAY_ID),
    UNIQUE KEY UK_GATEWAY_NAME (GATEWAY_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 2. USER - Identity (OIDC subject linked to a gateway)
-- ============================================================================

CREATE TABLE IF NOT EXISTS `USER` (
    USER_ID VARCHAR(512) NOT NULL,
    SUB VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    PERSONAL_GROUP_ID VARCHAR(512),
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID),
    INDEX IDX_USER_SUB (SUB),
    INDEX IDX_USER_GATEWAY_ID (GATEWAY_ID),
    INDEX IDX_USER_SUB_GATEWAY (SUB, GATEWAY_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 3. NOTIFICATION - User-facing messages
-- ============================================================================

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    NOTIFICATION_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255),
    TITLE VARCHAR(255),
    NOTIFICATION_MESSAGE VARCHAR(4096) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PUBLISHED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIORITY VARCHAR(50),
    PRIMARY KEY (NOTIFICATION_ID),
    INDEX IDX_NOTIFICATION_GATEWAY (GATEWAY_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 4. TAG - Artifact tags
-- ============================================================================

CREATE TABLE IF NOT EXISTS TAG (
    ID VARCHAR(48) NOT NULL,
    VALUE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 5. RESOURCE - Unified compute and storage resources
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESOURCE (
    RESOURCE_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    HOST_NAME VARCHAR(255) NOT NULL,
    PORT INT DEFAULT 22,
    DESCRIPTION TEXT,
    RESOURCE_TYPE VARCHAR(20) NOT NULL DEFAULT 'COMPUTE',
    CAPABILITIES JSON NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RESOURCE_ID),
    INDEX IDX_RESOURCE_GATEWAY (GATEWAY_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 6. CREDENTIAL - SSH keys, passwords, and certificates
-- ============================================================================

CREATE TABLE IF NOT EXISTS CREDENTIAL (
    CREDENTIAL_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CREDENTIAL_DATA LONGBLOB NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CREDENTIAL_ID),
    INDEX IDX_CREDENTIAL_GATEWAY (GATEWAY_ID),
    INDEX IDX_CREDENTIAL_USER (USER_ID),
    INDEX IDX_CREDENTIAL_GATEWAY_USER (GATEWAY_ID, USER_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 7. RESOURCE_BINDING - Maps a credential to a resource with runtime metadata
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESOURCE_BINDING (
    BINDING_ID VARCHAR(255) NOT NULL,
    CREDENTIAL_ID VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    LOGIN_USERNAME VARCHAR(255) NOT NULL,
    METADATA JSON,
    ENABLED BOOLEAN DEFAULT TRUE,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (BINDING_ID),
    UNIQUE KEY UK_BINDING_CRED_RESOURCE_USER (CREDENTIAL_ID, RESOURCE_ID, LOGIN_USERNAME),
    INDEX IDX_BINDING_CREDENTIAL (CREDENTIAL_ID),
    INDEX IDX_BINDING_RESOURCE (RESOURCE_ID),
    INDEX IDX_BINDING_GATEWAY (GATEWAY_ID),
    FOREIGN KEY (CREDENTIAL_ID) REFERENCES CREDENTIAL(CREDENTIAL_ID) ON DELETE CASCADE,
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(RESOURCE_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 8. APPLICATION - Consolidated app catalog
-- ============================================================================

CREATE TABLE IF NOT EXISTS APPLICATION (
    APPLICATION_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    OWNER_NAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(100),
    DESCRIPTION TEXT,
    INPUTS JSON,
    OUTPUTS JSON,
    INSTALL_SCRIPT MEDIUMTEXT,
    RUN_SCRIPT MEDIUMTEXT,
    SCOPE VARCHAR(50) DEFAULT 'GATEWAY',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (APPLICATION_ID),
    INDEX IDX_APPLICATION_GATEWAY (GATEWAY_ID),
    INDEX IDX_APPLICATION_OWNER (OWNER_NAME),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 9. APPLICATION_INSTALLATION - Tracks install state per (app, resource, user)
-- ============================================================================

CREATE TABLE IF NOT EXISTS APPLICATION_INSTALLATION (
    INSTALLATION_ID VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    LOGIN_USERNAME VARCHAR(255) NOT NULL,
    INSTALL_PATH VARCHAR(500),
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    INSTALLED_AT TIMESTAMP NULL,
    ERROR_MESSAGE TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (INSTALLATION_ID),
    UNIQUE KEY UK_INSTALLATION (APPLICATION_ID, RESOURCE_ID, LOGIN_USERNAME),
    INDEX IDX_INSTALLATION_APP (APPLICATION_ID),
    INDEX IDX_INSTALLATION_RESOURCE (RESOURCE_ID),
    FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID) ON DELETE CASCADE,
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(RESOURCE_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 10. ALLOCATION_PROJECT - HPC allocation projects per resource
-- ============================================================================

CREATE TABLE IF NOT EXISTS ALLOCATION_PROJECT (
    ALLOCATION_PROJECT_ID VARCHAR(255) NOT NULL,
    PROJECT_CODE VARCHAR(255) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ALLOCATION_PROJECT_ID),
    UNIQUE KEY UK_ALLOC_PROJECT (PROJECT_CODE, RESOURCE_ID),
    INDEX IDX_ALLOC_PROJECT_RESOURCE (RESOURCE_ID),
    INDEX IDX_ALLOC_PROJECT_GATEWAY (GATEWAY_ID),
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(RESOURCE_ID) ON DELETE CASCADE,
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 11. CREDENTIAL_ALLOCATION_PROJECT - Links credentials to allocation projects
-- ============================================================================

CREATE TABLE IF NOT EXISTS CREDENTIAL_ALLOCATION_PROJECT (
    CREDENTIAL_ID VARCHAR(255) NOT NULL,
    ALLOCATION_PROJECT_ID VARCHAR(255) NOT NULL,
    BINDING_ID VARCHAR(255) NOT NULL,
    PRIMARY KEY (CREDENTIAL_ID, ALLOCATION_PROJECT_ID),
    FOREIGN KEY (ALLOCATION_PROJECT_ID) REFERENCES ALLOCATION_PROJECT(ALLOCATION_PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (BINDING_ID) REFERENCES RESOURCE_BINDING(BINDING_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 12. RESEARCH_ARTIFACT - JOINED inheritance root for all artifact types
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_ARTIFACT (
    ID VARCHAR(48) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    HEADER_IMAGE VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    PRIVACY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 13. RESEARCH_MODEL_ARTIFACT - Model artifacts (extends RESEARCH_ARTIFACT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_MODEL_ARTIFACT (
    ID VARCHAR(48) NOT NULL,
    APPLICATION_INTERFACE_ID VARCHAR(255) NOT NULL,
    VERSION VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 14. RESEARCH_NOTEBOOK_ARTIFACT - Notebook artifacts (extends RESEARCH_ARTIFACT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_NOTEBOOK_ARTIFACT (
    ID VARCHAR(48) NOT NULL,
    NOTEBOOK_PATH VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 15. RESEARCH_REPOSITORY_ARTIFACT - Repository artifacts (extends RESEARCH_ARTIFACT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_REPOSITORY_ARTIFACT (
    ID VARCHAR(48) NOT NULL,
    REPOSITORY_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 16. RESEARCH_DATASET_ARTIFACT - Dataset artifacts (extends RESEARCH_ARTIFACT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_DATASET_ARTIFACT (
    ID VARCHAR(48) NOT NULL,
    DATASET_URL VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 17. RESEARCH_ARTIFACT_AUTHORS - @ElementCollection for artifact authors
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_ARTIFACT_AUTHORS (
    ARTIFACT_ID VARCHAR(48) NOT NULL,
    AUTHOR_ID VARCHAR(255) NOT NULL,
    FOREIGN KEY (ARTIFACT_ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 18. RESEARCH_ARTIFACT_TAGS - @ManyToMany join table for artifact <-> tag
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_ARTIFACT_TAGS (
    ARTIFACT_ID VARCHAR(48) NOT NULL,
    TAG_ID VARCHAR(48) NOT NULL,
    PRIMARY KEY (ARTIFACT_ID, TAG_ID),
    FOREIGN KEY (ARTIFACT_ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE,
    FOREIGN KEY (TAG_ID) REFERENCES TAG(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 19. ARTIFACT_STAR - User stars on artifacts
-- ============================================================================

CREATE TABLE IF NOT EXISTS ARTIFACT_STAR (
    ID VARCHAR(48) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    ARTIFACT_ID VARCHAR(48) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ARTIFACT_ID) REFERENCES RESEARCH_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 20. PROJECT - Research project (primary organizational unit)
-- ============================================================================

CREATE TABLE IF NOT EXISTS PROJECT (
    PROJECT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATE VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    REPOSITORY_ARTIFACT_ID VARCHAR(48),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PROJECT_ID),
    INDEX IDX_PROJECT_GATEWAY (GATEWAY_ID),
    INDEX IDX_PROJECT_OWNER (OWNER_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE,
    FOREIGN KEY (REPOSITORY_ARTIFACT_ID) REFERENCES RESEARCH_REPOSITORY_ARTIFACT(ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 21. RESEARCH_PROJECT - Research-domain project linked to a repository artifact
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_PROJECT (
    ID VARCHAR(48) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    OWNER_ID VARCHAR(255) NOT NULL,
    REPOSITORY_ARTIFACT_ID VARCHAR(48) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (REPOSITORY_ARTIFACT_ID) REFERENCES RESEARCH_REPOSITORY_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 22. RESEARCH_PROJECT_DATASET - @ManyToMany join table
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_PROJECT_DATASET (
    PROJECT_ID VARCHAR(48) NOT NULL,
    DATASET_ARTIFACT_ID VARCHAR(48) NOT NULL,
    PRIMARY KEY (PROJECT_ID, DATASET_ARTIFACT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES RESEARCH_PROJECT(ID) ON DELETE CASCADE,
    FOREIGN KEY (DATASET_ARTIFACT_ID) REFERENCES RESEARCH_DATASET_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 23. PROJECT_DATASET - @ManyToMany join table (PROJECT <-> RESEARCH_DATASET_ARTIFACT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS PROJECT_DATASET (
    PROJECT_ID VARCHAR(255) NOT NULL,
    DATASET_ARTIFACT_ID VARCHAR(48) NOT NULL,
    PRIMARY KEY (PROJECT_ID, DATASET_ARTIFACT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE CASCADE,
    FOREIGN KEY (DATASET_ARTIFACT_ID) REFERENCES RESEARCH_DATASET_ARTIFACT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 24. EXPERIMENT
-- ============================================================================

CREATE TABLE IF NOT EXISTS EXPERIMENT (
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255),
    GATEWAY_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    EXPERIMENT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    APPLICATION_ID VARCHAR(255) NOT NULL,
    BINDING_ID VARCHAR(255) NOT NULL,
    STATE VARCHAR(50) NOT NULL DEFAULT 'CREATED',
    SCHEDULING JSON,
    PARENT_EXPERIMENT_ID VARCHAR(255),
    TAGS JSON,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (EXPERIMENT_ID),
    INDEX IDX_EXPERIMENT_PROJECT (PROJECT_ID),
    INDEX IDX_EXPERIMENT_GATEWAY (GATEWAY_ID),
    INDEX IDX_EXPERIMENT_USER (USER_NAME),
    INDEX IDX_EXPERIMENT_APP (APPLICATION_ID),
    INDEX IDX_EXPERIMENT_BINDING (BINDING_ID),
    INDEX IDX_EXPERIMENT_STATE (STATE),
    INDEX IDX_EXPERIMENT_CREATED_AT (CREATED_AT),
    INDEX IDX_EXPERIMENT_PARENT (PARENT_EXPERIMENT_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID) ON DELETE SET NULL,
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE,
    FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID) ON DELETE RESTRICT,
    FOREIGN KEY (BINDING_ID) REFERENCES RESOURCE_BINDING(BINDING_ID) ON DELETE RESTRICT,
    FOREIGN KEY (PARENT_EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 25. EXPERIMENT_INPUT - Structured experiment inputs
-- ============================================================================

CREATE TABLE IF NOT EXISTS EXPERIMENT_INPUT (
    INPUT_ID VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    ARTIFACT_ID VARCHAR(48),
    VALUE TEXT,
    COMMAND_LINE_ARG VARCHAR(255),
    REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD_TO_COMMAND_LINE BOOLEAN NOT NULL DEFAULT TRUE,
    ORDER_INDEX INT NOT NULL DEFAULT 0,
    DESCRIPTION TEXT,
    PRIMARY KEY (INPUT_ID),
    INDEX IDX_EXP_INPUT_EXPERIMENT (EXPERIMENT_ID),
    INDEX IDX_EXP_INPUT_ARTIFACT (ARTIFACT_ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 26. EXPERIMENT_OUTPUT - Structured experiment outputs
-- ============================================================================

CREATE TABLE IF NOT EXISTS EXPERIMENT_OUTPUT (
    OUTPUT_ID VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    ARTIFACT_ID VARCHAR(48),
    VALUE TEXT,
    COMMAND_LINE_ARG VARCHAR(255),
    REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
    DATA_MOVEMENT BOOLEAN NOT NULL DEFAULT FALSE,
    ORDER_INDEX INT NOT NULL DEFAULT 0,
    DESCRIPTION TEXT,
    LOCATION VARCHAR(1024),
    PRIMARY KEY (OUTPUT_ID),
    INDEX IDX_EXP_OUTPUT_EXPERIMENT (EXPERIMENT_ID),
    INDEX IDX_EXP_OUTPUT_ARTIFACT (ARTIFACT_ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 27. PROCESS - Execution unit; inherits context from experiment
-- ============================================================================

CREATE TABLE IF NOT EXISTS PROCESS (
    PROCESS_ID VARCHAR(255) NOT NULL,
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    APPLICATION_ID VARCHAR(255),
    RESOURCE_ID VARCHAR(255),
    BINDING_ID VARCHAR(255),
    PROVIDER_CONTEXT JSON,
    RESOURCE_SCHEDULE JSON,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (PROCESS_ID),
    INDEX IDX_PROCESS_EXPERIMENT (EXPERIMENT_ID),
    FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT(EXPERIMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE(RESOURCE_ID) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 28. EVENT - Generalized audit trail (status changes + errors)
-- ============================================================================

CREATE TABLE IF NOT EXISTS EVENT (
    EVENT_ID VARCHAR(255) NOT NULL,
    PARENT_ID VARCHAR(255) NOT NULL,
    PARENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'PROCESS',
    EVENT_KIND VARCHAR(20) NOT NULL,
    EVENT_TIME TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    SEQUENCE_NUM BIGINT NOT NULL DEFAULT 0,
    STATE VARCHAR(255),
    REASON MEDIUMTEXT,
    ACTUAL_ERROR_MESSAGE MEDIUMTEXT,
    USER_FRIENDLY_MESSAGE MEDIUMTEXT,
    TRANSIENT_OR_PERSISTENT BOOLEAN,
    ROOT_CAUSE_ERROR_ID_LIST MEDIUMTEXT,
    PRIMARY KEY (EVENT_ID),
    INDEX IDX_EVENT_PARENT (PARENT_ID),
    INDEX IDX_EVENT_KIND (EVENT_KIND),
    INDEX IDX_EVENT_PARENT_TYPE_KIND_SEQ (PARENT_ID, PARENT_TYPE, EVENT_KIND, SEQUENCE_NUM DESC),
    INDEX IDX_EVENT_TIME (EVENT_TIME),
    CONSTRAINT CHK_EVENT_KIND CHECK (EVENT_KIND IN ('STATUS', 'ERROR'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 29. JOB - HPC/fork job tracking
-- ============================================================================

CREATE TABLE IF NOT EXISTS JOB (
    JOB_ID VARCHAR(255) NOT NULL,
    PROCESS_ID VARCHAR(255) NOT NULL,
    JOB_NAME VARCHAR(255),
    WORKING_DIR MEDIUMTEXT,
    JOB_DESCRIPTION MEDIUMTEXT,
    STD_OUT MEDIUMTEXT,
    STD_ERR MEDIUMTEXT,
    EXIT_CODE INT DEFAULT 0,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    COMPUTE_RESOURCE_CONSUMED VARCHAR(255),
    PRIMARY KEY (JOB_ID),
    INDEX IDX_JOB_PROCESS_ID (PROCESS_ID),
    INDEX IDX_JOB_NAME (JOB_NAME),
    FOREIGN KEY (PROCESS_ID) REFERENCES PROCESS(PROCESS_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 30. RESEARCH_SESSION - User sessions within research projects
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESEARCH_SESSION (
    ID VARCHAR(48) NOT NULL,
    SESSION_NAME VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(48) NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES RESEARCH_PROJECT(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 31. USER_GROUP - Sharing groups
-- ============================================================================

CREATE TABLE IF NOT EXISTS USER_GROUP (
    GROUP_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    OWNER_ID VARCHAR(255) NOT NULL,
    GROUP_TYPE VARCHAR(255) NOT NULL,
    GROUP_CARDINALITY VARCHAR(255) NOT NULL,
    IS_PERSONAL_GROUP BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (GROUP_ID, GATEWAY_ID),
    FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(GATEWAY_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IF NOT EXISTS IDX_USER_GROUP_OWNER ON USER_GROUP(OWNER_ID);
CREATE INDEX IF NOT EXISTS IDX_USER_GROUP_TYPE ON USER_GROUP(GROUP_TYPE);
CREATE INDEX IF NOT EXISTS IDX_PERSONAL_GROUP ON USER_GROUP(IS_PERSONAL_GROUP, OWNER_ID(255));

-- ============================================================================
-- 32. GROUP_MEMBERSHIP - Group member records
-- ============================================================================

CREATE TABLE IF NOT EXISTS GROUP_MEMBERSHIP (
    MEMBERSHIP_ID VARCHAR(512) NOT NULL,
    GROUP_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50),
    DOMAIN_ID VARCHAR(255),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MEMBERSHIP_ID),
    UNIQUE KEY UK_GROUP_USER (GROUP_ID, USER_ID, DOMAIN_ID),
    INDEX IDX_GM_GROUP (GROUP_ID),
    INDEX IDX_GM_USER (USER_ID),
    INDEX IDX_GM_DOMAIN (DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 33. SHARING_PERMISSION - Resource-level sharing permissions
-- ============================================================================

CREATE TABLE IF NOT EXISTS SHARING_PERMISSION (
    PERMISSION_ID VARCHAR(512) NOT NULL,
    RESOURCE_TYPE VARCHAR(50) NOT NULL,
    RESOURCE_ID VARCHAR(255) NOT NULL,
    GRANTEE_TYPE VARCHAR(20) NOT NULL,
    GRANTEE_ID VARCHAR(255) NOT NULL,
    PERMISSION VARCHAR(255) NOT NULL,
    DOMAIN_ID VARCHAR(255),
    METADATA JSON,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (PERMISSION_ID),
    UNIQUE KEY UK_SHARING_PERM (RESOURCE_TYPE, RESOURCE_ID, GRANTEE_TYPE, GRANTEE_ID, PERMISSION, DOMAIN_ID),
    INDEX IDX_SP_RESOURCE (RESOURCE_TYPE, RESOURCE_ID),
    INDEX IDX_SP_GRANTEE (GRANTEE_TYPE, GRANTEE_ID),
    INDEX IDX_SP_DOMAIN (DOMAIN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 34. RESOURCE_PREFERENCE - Multi-level preference overrides
-- ============================================================================

CREATE TABLE IF NOT EXISTS RESOURCE_PREFERENCE (
    PREFERENCE_ID BIGINT NOT NULL AUTO_INCREMENT,
    RESOURCE_TYPE VARCHAR(64) NOT NULL,
    RESOURCE_ID VARCHAR(512) NOT NULL,
    OWNER_ID VARCHAR(512) NOT NULL,
    PREFERENCE_LEVEL VARCHAR(32) NOT NULL,
    PREF_KEY VARCHAR(255) NOT NULL,
    PREF_VALUE MEDIUMTEXT,
    VALUE_TYPE VARCHAR(32),
    ENFORCED BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (PREFERENCE_ID),
    INDEX IDX_RP_RESOURCE (RESOURCE_TYPE, RESOURCE_ID(255)),
    INDEX IDX_RP_OWNER (OWNER_ID(255)),
    INDEX IDX_RP_KEY (PREF_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 35. WORKFLOW + WORKFLOW_RUN - User-level DAG workflow definitions and runs
-- ============================================================================

CREATE TABLE IF NOT EXISTS WORKFLOW (
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    WORKFLOW_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STEPS JSON,
    EDGES JSON,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (WORKFLOW_ID),
    INDEX IDX_WORKFLOW_PROJECT (PROJECT_ID, GATEWAY_ID),
    INDEX IDX_WORKFLOW_USER (USER_NAME, GATEWAY_ID),
    FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS WORKFLOW_RUN (
    RUN_ID VARCHAR(255) NOT NULL,
    WORKFLOW_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'CREATED',
    STEP_STATES JSON,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (RUN_ID),
    INDEX IDX_WORKFLOW_RUN_WORKFLOW (WORKFLOW_ID),
    INDEX IDX_WORKFLOW_RUN_USER (USER_NAME),
    FOREIGN KEY (WORKFLOW_ID) REFERENCES WORKFLOW(WORKFLOW_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 36. COMPUTE_SUBMISSION_TRACKING - Rate-limiting guard per resource
-- ============================================================================

CREATE TABLE IF NOT EXISTS COMPUTE_SUBMISSION_TRACKING (
    COMPUTE_RESOURCE_ID VARCHAR(255) NOT NULL,
    LAST_SUBMISSION_TIME BIGINT NOT NULL,
    PRIMARY KEY (COMPUTE_RESOURCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- 37. EXPERIMENT_SUMMARY - Denormalized experiment summary table
-- ============================================================================

CREATE TABLE IF NOT EXISTS EXPERIMENT_SUMMARY (
    EXPERIMENT_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255),
    GATEWAY_ID VARCHAR(255),
    CREATED_AT TIMESTAMP,
    USER_NAME VARCHAR(255),
    EXPERIMENT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    STATE VARCHAR(255),
    TIME_OF_STATE_CHANGE TIMESTAMP,
    PRIMARY KEY (EXPERIMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- END OF BASELINE SCHEMA
-- ============================================================================
