--
--
-- Licensed to the Apache Software Foundation (ASF) under one
-- or more contributor license agreements.  See the NOTICE file
-- distributed with this work for additional information
-- regarding copyright ownership.  The ASF licenses this file
-- to you under the Apache License, Version 2.0 (the
-- "License"); you may not use this file except in compliance
-- with the License.  You may obtain a copy of the License at
--
--   http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied.  See the License for the
-- specific language governing permissions and limitations
-- under the License.
--

use profile_service;

alter database profile_service character set = 'latin1';

-- AIRAVATA-2938: bring database schema into sync with registry-refactoring DB init scripts
set FOREIGN_KEY_CHECKS=0;
ALTER TABLE `NSF_DEMOGRAPHIC_RACE` CHANGE COLUMN IF EXISTS RACES RACE varchar(255) NOT NULL;
ALTER TABLE `NSF_DEMOGRAPHIC_DISABILITY` CHANGE COLUMN IF EXISTS DISABILITIES DISABILITY varchar(255) NOT NULL;
ALTER TABLE `USER_PROFILE_PHONE` CHANGE COLUMN IF EXISTS PHONES PHONE varchar(255) NOT NULL;
ALTER TABLE `USER_PROFILE_EMAIL` CHANGE COLUMN IF EXISTS EMAILS EMAIL varchar(255) NOT NULL;
ALTER TABLE `NSF_DEMOGRAPHIC_ETHNICITY` CHANGE COLUMN IF EXISTS ETHNICITIES ETHNICITY varchar(255) NOT NULL;
ALTER TABLE `NSF_DEMOGRAPHIC_DISABILITY` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`DISABILITY`);
ALTER TABLE `NSF_DEMOGRAPHIC_DISABILITY` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `NSF_DEMOGRAPHIC_ETHNICITY` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`ETHNICITY`);
ALTER TABLE `NSF_DEMOGRAPHIC_ETHNICITY` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `NSF_DEMOGRAPHIC_RACE` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`RACE`);
ALTER TABLE `NSF_DEMOGRAPHIC_RACE` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `USER_PROFILE_EMAIL` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`EMAIL`);
ALTER TABLE `USER_PROFILE_EMAIL` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `USER_PROFILE_LABELED_URI` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`LABELED_URI`);
ALTER TABLE `USER_PROFILE_LABELED_URI` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `USER_PROFILE_NATIONALITY` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`NATIONALITY`);
ALTER TABLE `USER_PROFILE_NATIONALITY` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
ALTER TABLE `USER_PROFILE_PHONE` ADD PRIMARY KEY IF NOT EXISTS (`AIRAVATA_INTERNAL_USER_ID`,`PHONE`);
ALTER TABLE `USER_PROFILE_PHONE` DROP INDEX IF EXISTS `AIRAVATA_INTERNAL_USER_ID`;
set FOREIGN_KEY_CHECKS=1;
