/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

-- Main workflow table
CREATE TABLE AIRAVATA_WORKFLOW
(
        ID VARCHAR(255) NOT NULL,
        EXPERIMENT_ID VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow applications
CREATE TABLE WORKFLOW_APPLICATION
(
        ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        PROCESS_ID VARCHAR(255),
        APPLICATION_INTERFACE_ID VARCHAR(255),
        COMPUTE_RESOURCE_ID VARCHAR(255),
        QUEUE_NAME VARCHAR(255),
        NODE_COUNT INTEGER,
        CORE_COUNT INTEGER,
        WALL_TIME_LIMIT INTEGER,
        PHYSICAL_MEMORY INTEGER,
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, WORKFLOW_ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow handlers
CREATE TABLE WORKFLOW_HANDLER
(
        ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        TYPE VARCHAR(255),
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, WORKFLOW_ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow data blocks
CREATE TABLE WORKFLOW_DATA_BLOCK
(
        ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        `VALUE` LONGTEXT,
        DATA_TYPE VARCHAR(255),
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow connections
CREATE TABLE WORKFLOW_CONNECTION
(
        ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        DATA_BLOCK_ID VARCHAR(255),
        FROM_TYPE VARCHAR(255),
        FROM_ID VARCHAR(255),
        FROM_OUTPUT_NAME VARCHAR(255),
        TO_TYPE VARCHAR(255),
        TO_ID VARCHAR(255),
        TO_INPUT_NAME VARCHAR(255),
        CREATED_AT TIMESTAMP,
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, WORKFLOW_ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE,
        FOREIGN KEY (DATA_BLOCK_ID) REFERENCES WORKFLOW_DATA_BLOCK(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow status
CREATE TABLE AIRAVATA_WORKFLOW_STATUS
(
        ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        STATE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, WORKFLOW_ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Workflow errors
CREATE TABLE AIRAVATA_WORKFLOW_ERROR
(
        ERROR_ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        CREATION_TIME TIMESTAMP NOT NULL,
        ACTUAL_ERROR_MESSAGE LONGTEXT,
        USER_FRIENDLY_MESSAGE LONGTEXT,
        TRANSIENT_OR_PERSISTENT TINYINT(1),
        ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
        PRIMARY KEY (ERROR_ID, WORKFLOW_ID),
        FOREIGN KEY (WORKFLOW_ID) REFERENCES AIRAVATA_WORKFLOW(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Application status
CREATE TABLE APPLICATION_STATUS
(
        ID VARCHAR(255) NOT NULL,
        APPLICATION_ID VARCHAR(255) NOT NULL,
        STATE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, APPLICATION_ID),
        FOREIGN KEY (APPLICATION_ID) REFERENCES WORKFLOW_APPLICATION(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Application errors
CREATE TABLE APPLICATION_ERROR
(
        ERROR_ID VARCHAR(255) NOT NULL,
        APPLICATION_ID VARCHAR(255) NOT NULL,
        CREATION_TIME TIMESTAMP NOT NULL,
        ACTUAL_ERROR_MESSAGE LONGTEXT,
        USER_FRIENDLY_MESSAGE LONGTEXT,
        TRANSIENT_OR_PERSISTENT TINYINT(1),
        ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
        PRIMARY KEY (ERROR_ID, APPLICATION_ID),
        FOREIGN KEY (APPLICATION_ID) REFERENCES WORKFLOW_APPLICATION(ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Handler status
CREATE TABLE HANDLER_STATUS
(
        ID VARCHAR(255) NOT NULL,
        HANDLER_ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        STATE VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        UPDATED_AT TIMESTAMP,
        PRIMARY KEY (ID, HANDLER_ID),
        FOREIGN KEY (HANDLER_ID, WORKFLOW_ID) REFERENCES WORKFLOW_HANDLER(ID, WORKFLOW_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Handler errors
CREATE TABLE HANDLER_ERROR
(
        ERROR_ID VARCHAR(255) NOT NULL,
        HANDLER_ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        CREATION_TIME TIMESTAMP NOT NULL,
        ACTUAL_ERROR_MESSAGE LONGTEXT,
        USER_FRIENDLY_MESSAGE LONGTEXT,
        TRANSIENT_OR_PERSISTENT TINYINT(1),
        ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
        PRIMARY KEY (ERROR_ID, HANDLER_ID),
        FOREIGN KEY (HANDLER_ID, WORKFLOW_ID) REFERENCES WORKFLOW_HANDLER(ID, WORKFLOW_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Handler inputs
CREATE TABLE HANDLER_INPUT
(
        HANDLER_ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        `VALUE` LONGTEXT,
        TYPE VARCHAR(255),
        APPLICATION_ARGUMENT VARCHAR(255),
        STANDARD_INPUT TINYINT(1),
        USER_FRIENDLY_DESCRIPTION VARCHAR(255),
        METADATA VARCHAR(4096),
        INPUT_ORDER INTEGER,
        IS_REQUIRED TINYINT(1),
        REQUIRED_TO_ADDED_TO_COMMAND_LINE TINYINT(1),
        DATA_STAGED TINYINT(1),
        STORAGE_RESOURCE_ID VARCHAR(255),
        IS_READ_ONLY TINYINT(1),
        PRIMARY KEY (HANDLER_ID, NAME),
        FOREIGN KEY (HANDLER_ID, WORKFLOW_ID) REFERENCES WORKFLOW_HANDLER(ID, WORKFLOW_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Handler outputs
CREATE TABLE HANDLER_OUTPUT
(
        HANDLER_ID VARCHAR(255) NOT NULL,
        WORKFLOW_ID VARCHAR(255) NOT NULL,
        NAME VARCHAR(255) NOT NULL,
        `VALUE` LONGTEXT,
        TYPE VARCHAR(255),
        APPLICATION_ARGUMENT VARCHAR(255),
        IS_REQUIRED TINYINT(1),
        REQUIRED_TO_ADDED_TO_COMMAND_LINE TINYINT(1),
        DATA_MOVEMENT TINYINT(1),
        LOCATION VARCHAR(255),
        SEARCH_QUERY VARCHAR(255),
        OUTPUT_STREAMING TINYINT(1),
        STORAGE_RESOURCE_ID VARCHAR(255),
        PRIMARY KEY (HANDLER_ID, NAME),
        FOREIGN KEY (HANDLER_ID, WORKFLOW_ID) REFERENCES WORKFLOW_HANDLER(ID, WORKFLOW_ID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
