#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements.  See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

agent.grpc.server.host=localhost
agent.grpc.server.port=19900
agent.grpc.server.max-inbound-message-size=20971520

agent.server.port=18880
agent.server.address=0.0.0.0

agent.spring.servlet.multipart.max-file-size=200MB
agent.spring.servlet.multipart.max-request-size=200MB
agent.spring.datasource.url=jdbc:mariadb://localhost:13306/app_catalog
agent.spring.datasource.username=airavata
agent.spring.datasource.password=123456
agent.spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
agent.spring.datasource.hikari.pool-name=AppCatalogPool
agent.spring.datasource.hikari.leak-detection-threshold=20000
agent.spring.jpa.hibernate.ddl-auto=validate
agent.spring.jpa.open-in-view=false

airavata.server.url=localhost
airavata.server.secure=false
airavata.storageResourceId=localhost_77116e91-f042-4d3a-ab9c-3e7b4ebcd5bd
airavata.storagePath=/tmp
airavata.cluster.applicationInterfaceId=AiravataAgent_f4313e4d-20c2-4bf6-bff1-8aa0f0b0c1d6
airavata.tunnel.serverHost=localhost
airavata.tunnel.serverPort=17000
airavata.tunnel.serverToken=airavata
airavata.tunnel.serverApiUrl=http://localhost:8000
