/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef airavataAPI_CONSTANTS_H
#define airavataAPI_CONSTANTS_H

#include "airavataAPI_types.h"

namespace apache { namespace airavata { namespace api {

class airavataAPIConstants {
 public:
  airavataAPIConstants();

  std::string AIRAVATA_API_VERSION;
};

extern const airavataAPIConstants g_airavataAPI_constants;

}}} // namespace

#endif
