use sharing_catalog;

-- FIXME: IF NOT EXISTS syntax only works with MariaDB
ALTER TABLE DOMAIN ADD COLUMN INITIAL_USER_GROUP_ID varchar(255);
ALTER TABLE DOMAIN ADD CONSTRAINT `DOMAIN_INITIAL_USER_GROUP_ID_FK` FOREIGN KEY (INITIAL_USER_GROUP_ID, DOMAIN_ID) REFERENCES USER_GROUP(GROUP_ID, DOMAIN_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
