use experiment_catalog;

ALTER TABLE EXPERIMENT_INPUT ADD COLUMN IF NOT EXISTS OVERRIDE_FILENAME VARCHAR(255);
ALTER TABLE PROCESS_INPUT ADD COLUMN IF NOT EXISTS OVERRIDE_FILENAME VARCHAR(255);

CREATE TABLE IF NOT EXISTS GATEWAY_USAGE_REPORTING_COMMAND (
    GATEWAY_ID VARCHAR(255) NOT NULL,
    COMMAND LONGTEXT NOT NULL,
    PRIMARY KEY (GATEWAY_ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;