ALTER TABLE EXPERIMENT ADD COLUMN SWEEP_COUNT INT DEFAULT 1;
ALTER TABLE EXPERIMENT ADD COLUMN EXECUTION_TYPE VARCHAR(50) DEFAULT 'one_pass';

CREATE TABLE EXPERIMENT_OUTPUT_VALUE
(
        EXPERIMENT_ID varchar(255) NOT NULL,
        OUTPUT_NAME varchar(255),
        OUTPUT_VALUE varchar(2048),
        PRIMARY KEY(EXPERIMENT_ID,OUTPUT_NAME,OUTPUT_VALUE),
        FOREIGN KEY (EXPERIMENT_ID,OUTPUT_NAME) REFERENCES EXPERIMENT_OUTPUT(EXPERIMENT_ID,OUTPUT_NAME) ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=latin1;