# Airavata API Configuration
GATEWAY_ID = 'default'
AIRAVATA_API_HOST = 'localhost'
AIRAVATA_API_PORT = 9930
AIRAVATA_API_SECURE = True
GATEWAY_DATA_STORE_RESOURCE_ID = 'airavata.host_77116e91-f042-4d3a-ab9c-3e7b4ebcd5bd'
GATEWAY_DATA_STORE_DIR = '/tmp'
GATEWAY_DATA_STORE_HOSTNAME = 'localhost'
FILE_UPLOAD_TEMP_DIR = '/tmp'

# Profile Service Configuration
PROFILE_SERVICE_HOST = AIRAVATA_API_HOST
PROFILE_SERVICE_PORT = 8962
PROFILE_SERVICE_SECURE = False

# Sharing API Configuration
SHARING_API_HOST = AIRAVATA_API_HOST
SHARING_API_PORT = 7878
SHARING_API_SECURE = False

THRIFT_CLIENT_POOL_KEEPALIVE = True
