/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

namespace java org.apache.airavata.model.experiment
namespace php Airavata.Model.Experiment

/*
 * This file describes the definitions of the Airavata Experiment Data Structures. Each of the
 *   language specific Airavata Client SDK's will translate this neutral data model into an
 *   appropriate form for passing to the Airavata Server Execution API Calls.
 * 
 * The Experiment data model is divided into 6 categories: experiment metadata, experiment configuration
 *   data, experiment generated data, experiment monitoring data, provenance data and error handling data.
 *
 *   Experiment Metadata:
 *     this structure holds the owner of the experiment, name, description, creation and last update times,
 *     last known status, and if is private to the user or shared publicly. 
 *    FIXME: To start with, we will not define this but populate it inferring data from other structures. This
 *    structure needs revisiting once the API gets used.
 * 
 *  Experiment Configuration Data:
 *     this structure will contain all user provided configuration data.
 * 
 *  Experiment Generated Data:
 *     this structure describes all intermediate and output data generated by executing the experiment.
 * 
 *  Experiment Monitoring Data:
 *     this structure contains fine grained experiment status information.
 *
 *  Experiment Summary Data: 
 *     this is derived information from all experiment objects to provide a quick summary.
 *
*/

enum ExperimentStatus {
    CREATED,
    VALIDATED,
    SCHEDULED,
    LAUNCHED,
    EXECUTING,
    CANCELED,
    COMPLETED,
    FAILED,
    UNKNOWN
}

enum WorkflowNodeStatus {
    INVOKED,
    EXECUTING,
    CANCELED,
    COMPLETED,
    FAILED,
    UNKNOWN
}

enum ExecutionStatus {
    AUTHENTICATED,
    PRE_PROCESSING,
    CONFIGURING_WORKSPACE,
    INPUT_DATA_STAGING,
    OUTPUT_DATA_STAGING,
    POST_PROCESSING,
    CANCELED,
    COMPLETED,
    FAILED,
    UNKNOWN
}

enum JobStatus {
    SUBMITTED,
    QUEUED,
    ACTIVE,
    COMPLETE,
    CANCELED,
    FAILED,
    HELD,
    SUSPENDED,
    UNKNOWN
}

enum TransferStatus {
    SUBMITTED,
    QUEUED,
    ACTIVE,
    COMPLETE,
    CANCELED,
    FAILED,
    HELD,
    SUSPENDED,
    UNKNOWN
}

enum ActionableGroup {
    RESOURCE_ADMINS,
    AIRAVATA_ADMINS,
    GATEWAYS_ADMINS,
    USER,
    CANNOT_BE_DETERMINED
}

enum ErrorCategory {
    FILE_SYSTEM_FAILURE,
    APPLICATION_FAILURE,
    RESOURCE_NODE_FAILURE,
    DISK_FULL,
    INSUFFICIENT_ALLOCATION,
    SYSTEM_MAINTENANCE,
    AIRAVATA_INTERNAL_ERROR,
    CANNOT_BE_DETERMINED
}

enum CorrectiveAction {
    RETRY_SUBMISSION,
    CONTACT_SUPPORT,
    CANNOT_BE_DETERMINED
}

/**
* A structure  hold experiment input output
*
*/
struct DataObjectType {
    1: required string key,
    2: optional string type,
    3: optional string value
}

/**
 * A structure holding the Computational Resource Scheduling.
 *
*/
struct ComputationalResourceScheduling {
    1: optional string resourceHostId,
    2: optional i32 totalCPUCount,
    3: optional i32 nodeCount,
    4: optional i32 numberOfThreads,
    5: optional string queueName,
    6: optional i32 wallTimeLimit,
    7: optional i32 jobStartTime,
    8: optional i32 totalPhysicalMemory,
    9: optional string ComputationalProjectAccount
}

/**
 * A structure holding specified input data handling.
 *
*/
struct AdvancedInputDataHandling {
    1: optional bool stageInputFilesToWorkingDir = 0,
    2: optional string parentWorkingDirectory,
    3: optional string uniqueWorkingDirectory,
    4: optional bool cleanUpWorkingDirAfterJob = 0
}

/**
 * A structure holding specified output data handling.
 *
*/
struct AdvancedOutputDataHandling {
    2: optional string outputDataDir,
    3: optional string dataRegistryURL,
    4: optional bool persistOutputData = 1
}

/**
 * A structure holding Quality of Service Parameters.
 *
*/
struct QualityOfServiceParams {
    1: optional string startExecutionAt,
    2: optional string executeBefore,
    3: optional i32 numberofRetries
}

/**
 * A structure holding the experiment configuration.
 *
 *
*/
struct UserConfigurationData {
    1: required bool airavataAutoSchedule = 0,
    2: required bool overrideManualScheduledParams = 0,
    3: optional bool shareExperimentPublicly = 0,
    4: optional ComputationalResourceScheduling computationalResourceScheduling,
    5: optional AdvancedInputDataHandling advanceInputDataHandling,
    6: optional AdvancedOutputDataHandling advanceOutputDataHandling,
    7: optional QualityOfServiceParams qosParams
}

struct ErrorDetails {
    1: optional string actualErrorMessage,
    2: optional bool transientOrPersistant = 0,
    3: optional CorrectiveAction correctiveAction,
    4: optional ActionableGroup actionableGroup,
    5: optional string userFriendlyMessage,
    6: optional ErrorCategory errorCategory
}

struct JobDetails {
    1: required string jobID,
    2: required string jobDescription,
    3: optional JobStatus jobStatus,
    4: optional i64 lastUpdateTime,
    5: optional string applicationStatus,
    6: optional i64 applicationLastUpdateTime,
    7: optional list<ErrorDetails> errors
}

struct DataTransferDetails {
    1: required string transferID,
    2: required string transferDescription,
    3: optional TransferStatus transferStatus,
    4: optional i64 lastUpdateTime
}

/**
 * A structure holding the actual execution context decided based on user provided configuration data or system inferred
 *   information from scheduling and QoS parameters .
 *
*/
struct AiravataExecutionDetails {
    1: required string executionID
    2: optional string applicationId,
    3: optional string applicationVersion,
    4: optional list<DataObjectType> applicationInputs,
    5: optional list<DataObjectType> applicationOoutputs,
    6: optional ComputationalResourceScheduling executionScheduling,
    7: optional AdvancedInputDataHandling advancedInputDataHandling,
    8: optional AdvancedOutputDataHandling advancedOutputDataHandling,
    9: optional i64 creationTime,
    10: optional ExecutionStatus executionStatus,
    11: optional i64 lastUpdateTime,
    12: optional list<JobDetails> jobDetailsList,
    13: optional list<DataTransferDetails> dataTransferDetailsList,
    14: optional list<ErrorDetails> errors
}

/**
* A structure holding the node data.
* nodeInstanceId - unique node identifier for each run
*/
struct WorkflowNodeDetails {
    1: required string nodeInstanceId = "DO_NOT_SET",
    2: required string nodeName = "SIMPLE_APP_NODE",
    3: optional list<DataObjectType> nodeInputs,
    4: optional list<DataObjectType> nodeOutputs,
    5: optional i64 startTime,
    6: optional WorkflowNodeStatus workflowNodeStatus,
    7: optional i64 lastUpdateTime,
    8: optional list<AiravataExecutionDetails> executionDetailsList
    9: optional list<ErrorDetails> errors
}

/**
 * A structure holding the experiment metadata and its child models.
 *
 * userName:
 *   The user name of the targeted gateway end user on whose behalf the experiment is being created.
 *     the associated gateway identity can only be inferred from the security hand-shake so as to avoid
 *     authorized Airavata Clients mimicking an unauthorized request. If a gateway is not registered with
 *     Airavata, an authorization exception is thrown.
 *
 * experimentName:
 *   The name of the experiment as defined by the user. The name need not be unique as uniqueness is enforced
 *      by the generated experiment id.
 *
 * experimentDescription:
 *    The verbose description of the experiment. This is an optional parameter.
*/

struct Experiment {
    1: required string experimentID = "DO_NOT_SET"
    2: required string projectID = "DEFAULT",
    3: optional i64 creationTime,
    4: required string userName,
    5: required string experimentName,
    6: optional string experimentDescription,
    7: optional string applicationId,
    8: optional string applicationVersion,
    9: optional string workflowTemplateId,
    10: optional string workflowTemplateVersion,
    11: optional string workflowExecutionInstanceId,
    12: optional list<DataObjectType> experimentInputs,
    13: optional list<DataObjectType> experimentOutputs,
    14: optional ExecutionStatus experimentStatus,
    15: optional i64 lastUpdateTime,
    16: optional list<WorkflowNodeDetails> workflowNodeDetailsList,
    17: optional list<ErrorDetails> errors
}