FROM python:3.12-slim

USER root
WORKDIR /home/jovyan

RUN pip install jupyterlab airavata-magics
RUN git clone https://github.com/cyber-shuttle/jupyter-notebook-examples examples

EXPOSE 8888
COPY data/* .

ENTRYPOINT [
    "jupyter", "lab",
    "--ip=0.0.0.0",
    "--port=8888",
    "--no-browser",
    "--allow-root",
    "--NotebookApp.exec_lines='import airavata_magics'",
    "--NotebookApp.token=''"
]
