USE replica_catalog;

-- AIRAVATA-3697: Support file names that have UTF8 characters and that are long
SET
  FOREIGN_KEY_CHECKS = 0;

ALTER DATABASE replica_catalog CHARACTER SET = utf8 COLLATE = utf8_bin;

ALTER TABLE
  DATA_PRODUCT CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE
  DATA_REPLICA_LOCATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE
  DATA_PRODUCT_METADATA CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE
  DATA_REPLICA_METADATA CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE
  CONFIGURATION CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;

SET
  FOREIGN_KEY_CHECKS = 1;

ALTER TABLE
  DATA_REPLICA_LOCATION
MODIFY
  REPLICA_NAME text;

ALTER TABLE
  DATA_PRODUCT
MODIFY
  PRODUCT_NAME text;
