USE replica_catalog;

-- AIRAVATA-3697: Support file names that have UTF8 characters and that are long
ALTER TABLE
  DATA_PRODUCT
MODIFY
  PRODUCT_NAME text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

ALTER TABLE
  DATA_PRODUCT
MODIFY
  PRODUCT_DESCRIPTION varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

ALTER TABLE
  DATA_REPLICA_LOCATION
MODIFY
  REPLICA_NAME text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

ALTER TABLE
  DATA_REPLICA_LOCATION
MODIFY
  REPLICA_DESCRIPTION varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

ALTER TABLE
  DATA_REPLICA_LOCATION
MODIFY
  FILE_PATH varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
