-- Baseline schema, captured verbatim from a real MariaDB run of AutoMigrate against
-- the entity model in internal/db/migrate.go (see Entities()). It is the schema every
-- fresh production database should start from before any versioned migration runs.
--
-- Do not hand-edit this file once it has run anywhere outside development: a change
-- to a table's shape belongs in a new migration (0002_..., 0003_..., ...), the same
-- way ddl-auto never narrows a column and this framework never rewrites history.

CREATE TABLE `users` (`user_id` varchar(255),`auth_method` varchar(32),`email` varchar(255),`first_name` varchar(255),`last_name` varchar(255),`status` varchar(32),`created_at` bigint NOT NULL,PRIMARY KEY (`user_id`));

CREATE TABLE `ssh_keys` (`ssh_key_id` varchar(36),`ssh_key_name` varchar(255) NOT NULL,`public_key` longtext NOT NULL,`private_key` longtext NOT NULL,`passphrase` varchar(255),PRIMARY KEY (`ssh_key_id`));

CREATE TABLE `clusters` (`cluster_id` varchar(36),`cluster_name` varchar(255) NOT NULL,`cluster_description` varchar(1024),`host_name` varchar(255) NOT NULL,`slurm_home` varchar(1024) NOT NULL,PRIMARY KEY (`cluster_id`));

CREATE TABLE `application_templates` (`template_id` varchar(36),`template_name` varchar(255),`template_description` varchar(2048),PRIMARY KEY (`template_id`));

CREATE TABLE `batch_job_configs` (`batch_job_config_id` varchar(36),`cpus` int,`mem` varchar(64),`mem_per_cpu` varchar(64),`ntasks_per_node` int,`cpus_per_task` int,`nodes` int,`ntasks` int,`gres` varchar(255),`gpus` int,`mem_per_gpu` varchar(64),`cpus_per_gpu` varchar(64),`gpus_per_node` int,`wall_time_minutes` bigint NOT NULL,`constraints` varchar(255),`allocation` varchar(255) NOT NULL,PRIMARY KEY (`batch_job_config_id`));

CREATE TABLE `user_roles` (`user_id` varchar(255),`role` varchar(32),PRIMARY KEY (`user_id`,`role`),CONSTRAINT `fk_users_roles` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `ssh_user_credentials` (`ssh_credential_id` varchar(36),`username` varchar(255) NOT NULL,`ssh_key_id` varchar(36),PRIMARY KEY (`ssh_credential_id`),INDEX `idx_ssh_user_credentials_ssh_key_id` (`ssh_key_id`),CONSTRAINT `fk_ssh_user_credentials_ssh_key` FOREIGN KEY (`ssh_key_id`) REFERENCES `ssh_keys`(`ssh_key_id`) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE `cluster_partitions` (`partition_id` varchar(36),`cluster_id` varchar(36),`name` varchar(255) NOT NULL,`description` varchar(1024),`max_run_time` int,`max_nodes` int,`max_processors` int,`max_jobs_in_queue` int,`max_memory` bigint,`cpu_per_node` int,`default_node_count` int,`default_cpu_count` int,`default_walltime` bigint,`gres` varchar(1024),`nodes` varchar(4096),`is_default_queue` boolean,`is_checkpointable` boolean,PRIMARY KEY (`partition_id`),INDEX `idx_cluster_partitions_cluster_id` (`cluster_id`),CONSTRAINT `fk_clusters_partitions` FOREIGN KEY (`cluster_id`) REFERENCES `clusters`(`cluster_id`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `application_template_inputs` (`input_id` varchar(36),`template_id` varchar(36),`input_name` varchar(255),`display_name` varchar(255),`input_description` varchar(2048),`input_type` varchar(32),`is_required` boolean NOT NULL,`default_value` longtext,PRIMARY KEY (`input_id`),UNIQUE INDEX `uk_template_input_name` (`template_id`,`input_name`),CONSTRAINT `fk_application_templates_inputs` FOREIGN KEY (`template_id`) REFERENCES `application_templates`(`template_id`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `application_template_outputs` (`output_id` varchar(36),`template_id` varchar(36),`output_type` varchar(32),`output_name` varchar(255),`display_name` varchar(255),`output_description` varchar(2048),PRIMARY KEY (`output_id`),INDEX `idx_application_template_outputs_template_id` (`template_id`),CONSTRAINT `fk_application_templates_outputs` FOREIGN KEY (`template_id`) REFERENCES `application_templates`(`template_id`) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE `cluster_credentials` (`cluster_credential_id` varchar(36),`cluster_id` varchar(36),`ssh_credential_id` varchar(36),`user_id` varchar(255),PRIMARY KEY (`cluster_credential_id`),INDEX `idx_cluster_credentials_cluster_id` (`cluster_id`),INDEX `idx_cluster_credentials_ssh_credential_id` (`ssh_credential_id`),INDEX `idx_cluster_credentials_owner_id` (`user_id`),CONSTRAINT `fk_cluster_credentials_cluster` FOREIGN KEY (`cluster_id`) REFERENCES `clusters`(`cluster_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_cluster_credentials_ssh_credential` FOREIGN KEY (`ssh_credential_id`) REFERENCES `ssh_user_credentials`(`ssh_credential_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_cluster_credentials_owner` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE `batch_application_deployments` (`deployment_id` varchar(36),`cluster_id` varchar(36),`template_id` varchar(36),`slurm_run_section` longtext NOT NULL,`batch_job_config_id` varchar(36) NOT NULL,`default_submission_credential_id` varchar(36) NOT NULL,`work_dir` varchar(1024),`partition` varchar(255),PRIMARY KEY (`deployment_id`),INDEX `idx_batch_application_deployments_cluster_id` (`cluster_id`),INDEX `idx_batch_application_deployments_template_id` (`template_id`),UNIQUE INDEX `idx_batch_application_deployments_batch_job_config_id` (`batch_job_config_id`),INDEX `idx_batch_application_deployments_default_submission_cre850dbe93` (`default_submission_credential_id`),CONSTRAINT `fk_batch_application_deployments_cluster` FOREIGN KEY (`cluster_id`) REFERENCES `clusters`(`cluster_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_batch_application_deployments_template` FOREIGN KEY (`template_id`) REFERENCES `application_templates`(`template_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_batch_application_deployments_batch_job_config` FOREIGN KEY (`batch_job_config_id`) REFERENCES `batch_job_configs`(`batch_job_config_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_batch_application_deployments_default_submission_credential` FOREIGN KEY (`default_submission_credential_id`) REFERENCES `cluster_credentials`(`cluster_credential_id`) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE `scp_data` (`data_id` varchar(36),`data_name` varchar(255),`data_description` varchar(2048),`is_file` varchar(16),`path` varchar(2048),`slurm_cluster_credential_id` varchar(36),`provision_status` varchar(32),`user_id` varchar(255),PRIMARY KEY (`data_id`),INDEX `idx_scp_data_cluster_credential_id` (`slurm_cluster_credential_id`),INDEX `idx_scp_data_owner_id` (`user_id`),CONSTRAINT `fk_scp_data_cluster_credential` FOREIGN KEY (`slurm_cluster_credential_id`) REFERENCES `cluster_credentials`(`cluster_credential_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_scp_data_owner` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE `batch_job_processes` (`process_id` varchar(36),`deployment_id` varchar(36),`user_id` varchar(255),`batch_job_config_id` varchar(36) NOT NULL,PRIMARY KEY (`process_id`),INDEX `idx_batch_job_processes_deployment_id` (`deployment_id`),INDEX `idx_batch_job_processes_owner_id` (`user_id`),UNIQUE INDEX `idx_batch_job_processes_batch_job_config_id` (`batch_job_config_id`),CONSTRAINT `fk_batch_job_processes_deployment` FOREIGN KEY (`deployment_id`) REFERENCES `batch_application_deployments`(`deployment_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_batch_job_processes_owner` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE RESTRICT ON UPDATE CASCADE,CONSTRAINT `fk_batch_job_processes_batch_job_config` FOREIGN KEY (`batch_job_config_id`) REFERENCES `batch_job_configs`(`batch_job_config_id`) ON DELETE RESTRICT ON UPDATE CASCADE);
