/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */
CREATE TABLE GATEWAY
(
        GATEWAY_NAME VARCHAR(255),
	      OWNER VARCHAR(255),
        PRIMARY KEY (GATEWAY_NAME)
);

CREATE TABLE CONFIGURATION
(
        CONFIG_KEY VARCHAR(255),
        CONFIG_VAL VARCHAR(255),
        EXPIRE_DATE TIMESTAMP DEFAULT '0000-00-00 00:00:00',
        CATEGORY_ID VARCHAR (255),
        PRIMARY KEY(CONFIG_KEY, CONFIG_VAL, CATEGORY_ID)
);

INSERT INTO CONFIGURATION (CONFIG_KEY, CONFIG_VAL, EXPIRE_DATE, CATEGORY_ID) VALUES('registry.version', '0.12', CURRENT_TIMESTAMP ,'SYSTEM');

CREATE TABLE USERS
(
        USER_NAME VARCHAR(255),
        PASSWORD VARCHAR(255),
        PRIMARY KEY(USER_NAME)
);

CREATE TABLE GATEWAY_WORKER
(
        GATEWAY_NAME VARCHAR(255),
        USER_NAME VARCHAR(255),
        PRIMARY KEY (GATEWAY_NAME, USER_NAME),
        FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
        FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE PROJECT
(
         GATEWAY_NAME VARCHAR(255),
         USER_NAME VARCHAR(255),
         PROJECT_NAME VARCHAR(255),
         PRIMARY KEY (PROJECT_NAME),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (USER_NAME) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE PUBLISHED_WORKFLOW
(
         GATEWAY_NAME VARCHAR(255),
         CREATED_USER VARCHAR(255),
         PUBLISH_WORKFLOW_NAME VARCHAR(255),
         VERSION VARCHAR(255),
         PUBLISHED_DATE TIMESTAMP DEFAULT '0000-00-00 00:00:00',
         PATH VARCHAR (255),
         WORKFLOW_CONTENT BLOB,
         PRIMARY KEY(GATEWAY_NAME, PUBLISH_WORKFLOW_NAME),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (CREATED_USER) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE USER_WORKFLOW
(
         GATEWAY_NAME VARCHAR(255),
         OWNER VARCHAR(255),
         TEMPLATE_NAME VARCHAR(255),
         LAST_UPDATED_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
         PATH VARCHAR (255),
         WORKFLOW_GRAPH BLOB,
         PRIMARY KEY(GATEWAY_NAME, OWNER, TEMPLATE_NAME),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (OWNER) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE HOST_DESCRIPTOR
(
         GATEWAY_NAME VARCHAR(255),
         UPDATED_USER VARCHAR(255),
         HOST_DESCRIPTOR_ID VARCHAR(255),
         HOST_DESCRIPTOR_XML BLOB,
         PRIMARY KEY(GATEWAY_NAME, HOST_DESCRIPTOR_ID),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (UPDATED_USER) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE SERVICE_DESCRIPTOR
(
         GATEWAY_NAME VARCHAR(255),
         UPDATED_USER VARCHAR(255),
         SERVICE_DESCRIPTOR_ID VARCHAR(255),
         SERVICE_DESCRIPTOR_XML BLOB,
         PRIMARY KEY(GATEWAY_NAME,SERVICE_DESCRIPTOR_ID),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (UPDATED_USER) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE APPLICATION_DESCRIPTOR
(
         GATEWAY_NAME VARCHAR(255),
         UPDATED_USER VARCHAR(255),
         APPLICATION_DESCRIPTOR_ID VARCHAR(255),
         HOST_DESCRIPTOR_ID VARCHAR(255),
         SERVICE_DESCRIPTOR_ID VARCHAR(255),
         APPLICATION_DESCRIPTOR_XML BLOB,
         PRIMARY KEY(GATEWAY_NAME,APPLICATION_DESCRIPTOR_ID),
         FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
         FOREIGN KEY (UPDATED_USER) REFERENCES USERS(USER_NAME) ON DELETE CASCADE
);

CREATE TABLE EXPERIMENT_METADATA
(
          EXPERIMENT_ID VARCHAR(255) NOT NULL,
          EXPERIMENT_NAME VARCHAR(255) NOT NULL,
          DESCRIPTION VARCHAR(255),
          SUBMITTED_DATE TIMESTAMP DEFAULT CURRENT TIMESTAMP,
          EXECUTION_USER VARCHAR(255),
          GATEWAY_NAME VARCHAR(255),
          PROJECT_NAME VARCHAR(255),
          SHARE_EXPERIMENT SMALLINT,
          PRIMARY KEY (EXPERIMENT_ID),
          FOREIGN KEY (GATEWAY_NAME) REFERENCES GATEWAY(GATEWAY_NAME) ON DELETE CASCADE,
          FOREIGN KEY (PROJECT_NAME) REFERENCES PROJECT(PROJECT_NAME) ON DELETE CASCADE
);

CREATE TABLE EXPERIMENT_SUMMARY
(
          EXPERIMENT_ID VARCHAR(255) NOT NULL,
          STATUS VARCHAR(255),
          LAST_UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          PRIMARY KEY(EXPERIMENT_ID),
          FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE EXPERIMENT_CONFIGURATION_DATA
(
          EXPERIMENT_ID VARCHAR(255) NOT NULL,
          RESOURCE_HOST_ID VARCHAR (255),
          TOTAL_CPU_COUNT INTEGER,
          NODE_COUNT INTEGER,
          NUMBER_OF_THREADS INTEGER,
          QUEUE_NAME VARCHAR (255),
          WALLTIME_LIMIT INTEGER,
          JOB_START_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
          TOTAL_PHYSICAL_MEMORY INTEGER,
          COMPUTATIONAL_PROJECT_ACCOUNT VARCHAR(255),
          AIRAVATA_AUTO_SCHEDULE SMALLINT,
          OVERRIDE_MANUAL_SCHEDULE_PARAMS SMALLINT,
          WORKING_DIR VARCHAR(255),
          STAGE_INPUT_FILES_TO_WORKING_DIR SMALLINT,
          OUTPUT_DATA_DIR VARCHAR(255),
          DATA_REG_URL VARCHAR (255),
          PERSIST_OUTPUT_DATA SMALLINT,
          CLEAN_AFTER_JOB SMALLINT,
          EXPERIMENT_CONFIG_DATA BLOB,
          PRIMARY KEY (EXPERIMENT_ID),
          FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE EXPERIMENT_INPUT
(
        EXPERIMENT_ID VARCHAR(255) NOT NULL,
        EX_KEY VARCHAR (255) NOT NULL,
        VALUE VARCHAR (255),
        PRIMARY KEY (EXPERIMENT_ID, EX_KEY),
        FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE EXPERIMENT_OUTPUT
(
        EXPERIMENT_ID VARCHAR(255) NOT NULL,
        EX_KEY VARCHAR (255) NOT NULL,
        VALUE VARCHAR (255),
        PRIMARY KEY (EXPERIMENT_ID, EX_KEY),
        FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE WORKFLOW_DATA
(
       EXPERIMENT_ID VARCHAR(255),
       WORKFLOW_INSTANCE_ID VARCHAR(255),
       TEMPLATE_NAME VARCHAR(255),
       STATUS VARCHAR(255),
       START_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
       LAST_UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       PRIMARY KEY(WORKFLOW_INSTANCE_ID),
       FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE NODE_DATA
(
       WORKFLOW_INSTANCE_ID VARCHAR(255),
       NODE_ID VARCHAR(255),
       NODE_TYPE VARCHAR(255),
       INPUTS BLOB,
       OUTPUTS BLOB,
       STATUS VARCHAR(255),
       START_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
       LAST_UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       EXECUTION_INDEX INTEGER NOT NULL,
       PRIMARY KEY(WORKFLOW_INSTANCE_ID, NODE_ID, EXECUTION_INDEX),
       FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_DATA(WORKFLOW_INSTANCE_ID) ON DELETE CASCADE
);

-- need to remove this in future
CREATE TABLE GRAM_DATA
(
       WORKFLOW_INSTANCE_ID VARCHAR(255),
       NODE_ID VARCHAR(255),
       RSL BLOB,
       INVOKED_HOST VARCHAR(255),
       LOCAL_JOB_ID VARCHAR(255),
       PRIMARY KEY(WORKFLOW_INSTANCE_ID, NODE_ID),
       FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_DATA(WORKFLOW_INSTANCE_ID) ON DELETE CASCADE
);

CREATE TABLE GFAC_JOB_DATA
(
       EXPERIMENT_ID VARCHAR(255),
       WORKFLOW_INSTANCE_ID VARCHAR(255),
       NODE_ID VARCHAR(255),
       APPLICATION_DESC_ID VARCHAR(255),
       HOST_DESC_ID VARCHAR(255),
       SERVICE_DESC_ID VARCHAR(255),
       JOB_DATA CLOB,
       LOCAL_JOB_ID VARCHAR(255) NOT NULL,
       SUBMITTED_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
       STATUS_UPDATE_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
       STATUS VARCHAR(255),
       METADATA CLOB,
       PRIMARY KEY(LOCAL_JOB_ID),
       FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID),
       FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_DATA(WORKFLOW_INSTANCE_ID)
);

CREATE TABLE GFAC_JOB_STATUS
(
       LOCAL_JOB_ID VARCHAR(255) NOT NULL,
       STATUS_UPDATE_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
       STATUS VARCHAR(255),
       FOREIGN KEY (LOCAL_JOB_ID) REFERENCES GFAC_JOB_DATA(LOCAL_JOB_ID)
);


CREATE TABLE COMMUNITY_USER
(
        GATEWAY_NAME VARCHAR(256) NOT NULL,
        COMMUNITY_USER_NAME VARCHAR(256) NOT NULL,
        TOKEN_ID VARCHAR(256) NOT NULL,
        COMMUNITY_USER_EMAIL VARCHAR(256) NOT NULL,
        PRIMARY KEY (GATEWAY_NAME, COMMUNITY_USER_NAME, TOKEN_ID)
);


CREATE TABLE CREDENTIALS
(
        GATEWAY_ID VARCHAR(256) NOT NULL,
        TOKEN_ID VARCHAR(256) NOT NULL,
        CREDENTIAL BLOB NOT NULL,
        PORTAL_USER_ID VARCHAR(256) NOT NULL,
        TIME_PERSISTED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (GATEWAY_ID, TOKEN_ID)
);

CREATE TABLE EXECUTION_ERROR
(
       ERROR_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
       EXPERIMENT_ID VARCHAR(255),
       WORKFLOW_INSTANCE_ID VARCHAR(255),
       NODE_ID VARCHAR(255),
       GFAC_JOB_ID VARCHAR(255),
       SOURCE_TYPE VARCHAR(255),
       ERROR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       ERROR_MSG CLOB,
       ERROR_DESC CLOB,
       ERROR_CODE VARCHAR(255),
       ERROR_REPORTER VARCHAR(255),
       ERROR_LOCATION VARCHAR(255),
       ACTION_TAKEN VARCHAR(255),
       ERROR_REFERENCE INTEGER,
       PRIMARY KEY(ERROR_ID),
       FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WORKFLOW_DATA(WORKFLOW_INSTANCE_ID) ON DELETE CASCADE,
       FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);

CREATE TABLE ORCHESTRATOR
(
        EXPERIMENT_ID VARCHAR(255) NOT NULL,
        USERNAME VARCHAR(255),
        STATUS VARCHAR(255),
        STATE VARCHAR(255),
        GFAC_EPR VARCHAR(255),
        APPLICATION_NAME VARCHAR(255),
        JOBREQUEST CLOB,
        SUBMITTED_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
        STATUS_UPDATE_TIME TIMESTAMP DEFAULT '0000-00-00 00:00:00',
        PRIMARY KEY (EXPERIMENT_ID),
        FOREIGN KEY (EXPERIMENT_ID) REFERENCES EXPERIMENT_METADATA(EXPERIMENT_ID) ON DELETE CASCADE
);


