[commands]
upgrade_type = security
random_sleep = 360
network_online_timeout = 60
download_updates = yes
apply_updates = yes

[emitters]
emit_via = stdio,email
system_name = None

[email]
email_from = root@localhost
email_to = root
email_host = localhost

[base]
debuglevel = -2

[command_alias]
upgrade_type = security
