[commands]
update_cmd = security
update_messages = yes
download_updates = yes
apply_updates = yes
random_sleep = 360

[emitters]
system_name = None
emit_via = stdio,email
output_width = 80

[email]
email_from = root@localhost
email_to = root
email_host = localhost

[base]
debuglevel = -2
mdpolicy = group:main

[groups]
group_list = None
group_package_types = mandatory, default
