/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 * Apache Airavata - Unified Database Schema (V1 Baseline)
 *
 * Authoritative baseline generated from the live JPA @Entity-derived schema.
 * Applied to a fresh database via MariaDB's /docker-entrypoint-initdb.d before
 * the server starts; the server then runs Hibernate ddl-auto=validate against it.
 * All persistence units share a single 'airavata' database.
 *
 * Requires: MariaDB 10.2+ or MySQL 5.7+
 */

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `app_io_param` (
  `PARAM_ID` varchar(255) NOT NULL,
  `APPLICATION_ARGUMENT` varchar(255) DEFAULT NULL,
  `DATA_MOVEMENT` bit(1) DEFAULT NULL,
  `DATA_STAGED` bit(1) DEFAULT NULL,
  `DIRECTION` varchar(255) NOT NULL,
  `INPUT_ORDER` int(11) DEFAULT NULL,
  `INTERFACE_ID` varchar(255) DEFAULT NULL,
  `IS_READ_ONLY` bit(1) DEFAULT NULL,
  `IS_REQUIRED` bit(1) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `METADATA` varchar(4096) DEFAULT NULL,
  `PARAM_NAME` varchar(255) DEFAULT NULL,
  `OUTPUT_STREAMING` bit(1) DEFAULT NULL,
  `OVERRIDE_FILENAME` varchar(255) DEFAULT NULL,
  `REQUIRED_TO_ADDED_TO_CMD` bit(1) DEFAULT NULL,
  `SEARCH_QUERY` varchar(255) DEFAULT NULL,
  `STANDARD_INPUT` bit(1) DEFAULT NULL,
  `DATA_TYPE` enum('DATA_TYPE_UNKNOWN','FLOAT','INTEGER','STDERR','STDOUT','STRING','UNRECOGNIZED','URI','URI_COLLECTION') DEFAULT NULL,
  `USER_FRIENDLY_DESCRIPTION` tinytext DEFAULT NULL,
  `PARAM_VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PARAM_ID`),
  KEY `FKmnhp1v0al1og8hylmavmnuj7v` (`INTERFACE_ID`),
  CONSTRAINT `FKmnhp1v0al1og8hylmavmnuj7v` FOREIGN KEY (`INTERFACE_ID`) REFERENCES `application_interface` (`INTERFACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `app_module_mapping` (
  `INTERFACE_ID` varchar(255) NOT NULL,
  `MODULE_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`INTERFACE_ID`,`MODULE_ID`),
  KEY `FKg27d33ww77k0iu9wftb8g87o2` (`MODULE_ID`),
  CONSTRAINT `FK10rd30oxbrkhnxsw22p86r5d0` FOREIGN KEY (`INTERFACE_ID`) REFERENCES `application_interface` (`INTERFACE_ID`),
  CONSTRAINT `FKg27d33ww77k0iu9wftb8g87o2` FOREIGN KEY (`MODULE_ID`) REFERENCES `application_module` (`MODULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `application_deployment` (
  `DEPLOYMENT_ID` varchar(255) NOT NULL,
  `APPLICATION_DESC` varchar(255) DEFAULT NULL,
  `APP_MODULE_ID` varchar(255) DEFAULT NULL,
  `COMPUTE_HOSTID` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime(6) NOT NULL,
  `DEFAULT_CPU_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_NODE_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_QUEUE_NAME` varchar(255) DEFAULT NULL,
  `DEFAULT_WALLTIME` int(11) DEFAULT NULL,
  `EDITABLE_BY_USER` bit(1) DEFAULT NULL,
  `ENV_MODULE_LOAD_CMD` varchar(255) DEFAULT NULL,
  `EXECUTABLE_PATH` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `LIB_APPEND_PATHS_JSON` tinytext DEFAULT NULL,
  `LIB_PREPEND_PATHS_JSON` tinytext DEFAULT NULL,
  `MODULE_LOAD_CMDS_JSON` tinytext DEFAULT NULL,
  `parallelism` enum('APPLICATION_PARALLELISM_TYPE_UNKNOWN','CCM','CRAY_MPI','MPI','OPENMP','OPENMP_MPI','SERIAL','UNRECOGNIZED') DEFAULT NULL,
  `POSTJOB_CMDS_JSON` tinytext DEFAULT NULL,
  `PREJOB_CMDS_JSON` tinytext DEFAULT NULL,
  `SET_ENVIRONMENT_JSON` tinytext DEFAULT NULL,
  `UPDATE_TIME` datetime(6) NOT NULL,
  PRIMARY KEY (`DEPLOYMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `application_interface` (
  `INTERFACE_ID` varchar(255) NOT NULL,
  `APPLICATION_DESCRIPTION` varchar(255) DEFAULT NULL,
  `APPLICATION_NAME` varchar(255) DEFAULT NULL,
  `ARCHIVE_WORKING_DIRECTORY` bit(1) DEFAULT NULL,
  `CLEAN_AFTER_STAGED` bit(1) DEFAULT NULL,
  `CREATION_TIME` datetime(6) NOT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `HAS_OPTIONAL_FILE_INPUTS` bit(1) DEFAULT NULL,
  `UPDATE_TIME` datetime(6) NOT NULL,
  PRIMARY KEY (`INTERFACE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `application_module` (
  `MODULE_ID` varchar(255) NOT NULL,
  `MODULE_DESC` varchar(255) DEFAULT NULL,
  `MODULE_NAME` varchar(255) DEFAULT NULL,
  `MODULE_VERSION` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime(6) NOT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `UPDATE_TIME` datetime(6) NOT NULL,
  PRIMARY KEY (`MODULE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `aws_group_compute_resource_preference` (
  `PREFERRED_AMI_ID` varchar(255) NOT NULL,
  `PREFERRED_INSTANCE_TYPE` varchar(255) NOT NULL,
  `AWS_REGION` varchar(255) NOT NULL,
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`RESOURCE_ID`,`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKl1teceda8xl3835al51ygnj6n` FOREIGN KEY (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_compute_resource_preference` (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `batch_queue` (
  `COMPUTE_RESOURCE_ID` varchar(255) NOT NULL,
  `QUEUE_NAME` varchar(255) NOT NULL,
  `CPU_PER_NODE` int(11) DEFAULT NULL,
  `DEFAULT_CPU_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_NODE_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_WALLTIME` int(11) DEFAULT NULL,
  `IS_DEFAULT_QUEUE` bit(1) DEFAULT NULL,
  `MAX_JOB_IN_QUEUE` int(11) DEFAULT NULL,
  `MAX_MEMORY` int(11) DEFAULT NULL,
  `MAX_NODES` int(11) DEFAULT NULL,
  `MAX_PROCESSORS` int(11) DEFAULT NULL,
  `MAX_RUNTIME` int(11) DEFAULT NULL,
  `QUEUE_DESCRIPTION` varchar(255) DEFAULT NULL,
  `QUEUE_SPECIFIC_MACROS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`COMPUTE_RESOURCE_ID`,`QUEUE_NAME`),
  CONSTRAINT `FKjsfen3qgsv2vhdo1dx32kdv6j` FOREIGN KEY (`COMPUTE_RESOURCE_ID`) REFERENCES `compute_resource` (`RESOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `batch_queue_resource_policy` (
  `RESOURCE_POLICY_ID` varchar(255) NOT NULL,
  `COMPUTE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) DEFAULT NULL,
  `MAX_ALLOWED_CORES` int(11) DEFAULT NULL,
  `MAX_ALLOWED_NODES` int(11) DEFAULT NULL,
  `MAX_ALLOWED_WALLTIME` int(11) DEFAULT NULL,
  `QUEUE_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_POLICY_ID`),
  KEY `FKqoj2b02j8v7wtedckv1qwms8t` (`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKqoj2b02j8v7wtedckv1qwms8t` FOREIGN KEY (`GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_resource_profile` (`GROUP_RESOURCE_PROFILE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `community_user` (
  `COMMUNITY_USER_NAME` varchar(256) NOT NULL,
  `GATEWAY_ID` varchar(256) NOT NULL,
  `TOKEN_ID` varchar(256) NOT NULL,
  `COMMUNITY_USER_EMAIL` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`COMMUNITY_USER_NAME`,`GATEWAY_ID`,`TOKEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource` (
  `RESOURCE_ID` varchar(255) NOT NULL,
  `CPUS_PER_NODE` int(11) DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `DEFAULT_CPU_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_NODE_COUNT` int(11) DEFAULT NULL,
  `DEFAULT_WALLTIME` int(11) DEFAULT NULL,
  `ENABLED` smallint(6) DEFAULT NULL,
  `FILE_SYSTEMS_JSON` tinytext DEFAULT NULL,
  `GATEWAY_USAGE_EXECUTABLE` varchar(255) DEFAULT NULL,
  `GATEWAY_USAGE_MODULE_LOAD_CMD` varchar(255) DEFAULT NULL,
  `GATEWAY_USAGE_REPORTING` bit(1) DEFAULT NULL,
  `HOST_NAME` varchar(255) DEFAULT NULL,
  `MAX_MEMORY_NODE` int(11) DEFAULT NULL,
  `RESOURCE_DESCRIPTION` varchar(255) DEFAULT NULL,
  `SSH_PORT` int(11) DEFAULT NULL,
  `UPDATE_TIME` datetime(6) DEFAULT NULL,
  `RESOURCE_JOB_MANAGER_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_ID`),
  KEY `FKpow67mcwfge4lv1c4g5biwpbn` (`RESOURCE_JOB_MANAGER_ID`),
  CONSTRAINT `FKpow67mcwfge4lv1c4g5biwpbn` FOREIGN KEY (`RESOURCE_JOB_MANAGER_ID`) REFERENCES `resource_job_manager` (`RESOURCE_JOB_MANAGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_policy` (
  `RESOURCE_POLICY_ID` varchar(255) NOT NULL,
  `COMPUTE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_POLICY_ID`),
  KEY `FKg0vb4wl5pi4qt8kxkb721hgbu` (`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKg0vb4wl5pi4qt8kxkb721hgbu` FOREIGN KEY (`GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_resource_profile` (`GROUP_RESOURCE_PROFILE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_policy_queues` (
  `RESOURCE_POLICY_ID` varchar(255) NOT NULL,
  `QUEUE_NAME` varchar(255) DEFAULT NULL,
  KEY `FKbjmiv9eyslmrnm2lscy917meg` (`RESOURCE_POLICY_ID`),
  CONSTRAINT `FKbjmiv9eyslmrnm2lscy917meg` FOREIGN KEY (`RESOURCE_POLICY_ID`) REFERENCES `compute_resource_policy` (`RESOURCE_POLICY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_preference` (
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `LOGIN_USERNAME` varchar(255) DEFAULT NULL,
  `OVERRIDE_BY_AIRAVATA` bit(1) DEFAULT NULL,
  `PREFERED_BATCH_QUEUE` varchar(255) DEFAULT NULL,
  `QUALITY_OF_SERVICE` varchar(255) DEFAULT NULL,
  `RESERVATION` varchar(255) DEFAULT NULL,
  `RESERVATION_END_TIME` datetime(6) DEFAULT NULL,
  `RESERVATION_START_TIME` datetime(6) DEFAULT NULL,
  `RESOURCE_CS_TOKEN` varchar(255) DEFAULT NULL,
  `SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  `SSH_ACCOUNT_PROVISIONER` varchar(255) DEFAULT NULL,
  `SSH_ACCOUNT_PROVISIONER_ADDITIONAL_INFO` varchar(255) DEFAULT NULL,
  `SSH_PROVISIONER_CONFIG_JSON` tinytext DEFAULT NULL,
  `USAGE_REPORTING_GATEWAY_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_ID`,`GATEWAY_ID`),
  KEY `FKt6yt7iocqf4a3bsnmnys28xd0` (`GATEWAY_ID`),
  CONSTRAINT `FKt6yt7iocqf4a3bsnmnys28xd0` FOREIGN KEY (`GATEWAY_ID`) REFERENCES `gateway_profile` (`GATEWAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_reservation` (
  `RESERVATION_ID` varchar(255) NOT NULL,
  `END_TIME` datetime(6) NOT NULL,
  `RESERVATION_NAME` varchar(255) NOT NULL,
  `START_TIME` datetime(6) NOT NULL,
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`RESERVATION_ID`),
  KEY `FKld174n2uyahxjlbb6qh38dqbp` (`RESOURCE_ID`,`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKld174n2uyahxjlbb6qh38dqbp` FOREIGN KEY (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_compute_resource_preference` (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_reservation_queue` (
  `RESERVATION_ID` varchar(255) NOT NULL,
  `QUEUE_NAME` varchar(255) NOT NULL,
  KEY `FKs0tq5ggdqtb21j0964puf9trk` (`RESERVATION_ID`),
  CONSTRAINT `FKs0tq5ggdqtb21j0964puf9trk` FOREIGN KEY (`RESERVATION_ID`) REFERENCES `compute_resource_reservation` (`RESERVATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `compute_resource_scheduling` (
  `EXPERIMENT_ID` varchar(255) NOT NULL,
  `QUEUE_NAME` varchar(255) NOT NULL,
  `RESOURCE_HOST_ID` varchar(255) NOT NULL,
  `PARALLEL_GROUP_COUNT` int(11) DEFAULT NULL,
  `NODE_COUNT` int(11) DEFAULT NULL,
  `NUMBER_OF_THREADS` int(11) DEFAULT NULL,
  `OVERRIDE_ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `OVERRIDE_LOGIN_USER_NAME` varchar(255) DEFAULT NULL,
  `OVERRIDE_SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  `STATIC_WORKING_DIR` varchar(255) DEFAULT NULL,
  `TOTAL_CPU_COUNT` int(11) DEFAULT NULL,
  `TOTAL_PHYSICAL_MEMORY` int(11) DEFAULT NULL,
  `WALL_TIME_LIMIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`EXPERIMENT_ID`,`QUEUE_NAME`,`RESOURCE_HOST_ID`),
  CONSTRAINT `FKny42mr4l3v517wmi204d17njl` FOREIGN KEY (`EXPERIMENT_ID`) REFERENCES `user_configuration_data` (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `credentials` (
  `GATEWAY_ID` varchar(256) NOT NULL,
  `TOKEN_ID` varchar(256) NOT NULL,
  `CREDENTIAL` mediumblob NOT NULL,
  `DESCRIPTION` varchar(500) DEFAULT NULL,
  `PORTAL_USER_ID` varchar(256) NOT NULL,
  `TIME_PERSISTED` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`,`TOKEN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `data_product` (
  `PRODUCT_URI` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `PRODUCT_TYPE` enum('COLLECTION','DATA_PRODUCT_TYPE_UNKNOWN','FILE','UNRECOGNIZED') DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_TIME` datetime(6) DEFAULT NULL,
  `OWNER_NAME` varchar(255) DEFAULT NULL,
  `PARENT_PRODUCT_URI` varchar(255) DEFAULT NULL,
  `PRODUCT_DESCRIPTION` varchar(255) DEFAULT NULL,
  `PRODUCT_NAME` tinytext DEFAULT NULL,
  `PRODUCT_SIZE` int(11) DEFAULT NULL,
  PRIMARY KEY (`PRODUCT_URI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `data_product_metadata` (
  `PRODUCT_URI` varchar(255) NOT NULL,
  `METADATA_VALUE` varchar(255) DEFAULT NULL,
  `METADATA_KEY` varchar(255) NOT NULL,
  PRIMARY KEY (`PRODUCT_URI`,`METADATA_KEY`),
  CONSTRAINT `FKnoadto82rrks0d3w1mwqmo1ag` FOREIGN KEY (`PRODUCT_URI`) REFERENCES `data_product` (`PRODUCT_URI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `data_replica_location` (
  `REPLICA_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `FILE_PATH` varchar(255) DEFAULT NULL,
  `LAST_MODIFIED_TIME` datetime(6) DEFAULT NULL,
  `PRODUCT_URI` varchar(255) DEFAULT NULL,
  `REPLICA_DESCRIPTION` varchar(255) DEFAULT NULL,
  `REPLICA_LOCATION_CATEGORY` enum('COMPUTE_RESOURCE','GATEWAY_DATA_STORE','LONG_TERM_STORAGE_RESOURCE','OTHER','REPLICA_LOCATION_CATEGORY_UNKNOWN','UNRECOGNIZED') DEFAULT NULL,
  `REPLICA_NAME` tinytext DEFAULT NULL,
  `REPLICA_PERSISTENT_TYPE` enum('PERSISTENT','REPLICA_PERSISTENT_TYPE_UNKNOWN','TRANSIENT','UNRECOGNIZED') DEFAULT NULL,
  `STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `VALID_UNTIL_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`REPLICA_ID`),
  KEY `IDX_DATA_REPLICA_FILE_PATH` (`FILE_PATH`),
  KEY `FKje98y39ubc23jt9tebdp6jw2k` (`PRODUCT_URI`),
  CONSTRAINT `FKje98y39ubc23jt9tebdp6jw2k` FOREIGN KEY (`PRODUCT_URI`) REFERENCES `data_product` (`PRODUCT_URI`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `data_replica_metadata` (
  `REPLICA_ID` varchar(255) NOT NULL,
  `METADATA_VALUE` varchar(255) DEFAULT NULL,
  `METADATA_KEY` varchar(255) NOT NULL,
  PRIMARY KEY (`REPLICA_ID`,`METADATA_KEY`),
  CONSTRAINT `FKoh6a7508g8b8fsq9yj4v60d7r` FOREIGN KEY (`REPLICA_ID`) REFERENCES `data_replica_location` (`REPLICA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `dataset_resource` (
  `datasetUrl` varchar(255) NOT NULL,
  `id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FKd326uuj5yxo3v3fskpwbfm820` FOREIGN KEY (`id`) REFERENCES `resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `domain` (
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INITIAL_USER_GROUP_ID` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `entity` (
  `ENTITY_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `BINARY_DATA` tinyblob DEFAULT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `ENTITY_TYPE_ID` varchar(255) DEFAULT NULL,
  `FULL_TEXT` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORIGINAL_ENTITY_CREATION_TIME` bigint(20) DEFAULT NULL,
  `OWNER_ID` varchar(255) DEFAULT NULL,
  `PARENT_ENTITY_ID` varchar(255) DEFAULT NULL,
  `SHARED_COUNT` bigint(20) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`ENTITY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `entity_type` (
  `ENTITY_TYPE_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`ENTITY_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `exec_error` (
  `ERROR_ID` varchar(255) NOT NULL,
  `ACTUAL_ERROR_MESSAGE` tinytext DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `ENTITY_ID` varchar(255) DEFAULT NULL,
  `ENTITY_TYPE` varchar(255) NOT NULL,
  `ROOT_CAUSE_ERROR_ID_LIST` tinytext DEFAULT NULL,
  `TRANSIENT_OR_PERSISTENT` bit(1) DEFAULT NULL,
  `USER_FRIENDLY_MESSAGE` tinytext DEFAULT NULL,
  PRIMARY KEY (`ERROR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `exec_io_param` (
  `PARAM_ID` varchar(255) NOT NULL,
  `APPLICATION_ARGUMENT` varchar(255) DEFAULT NULL,
  `DATA_MOVEMENT` bit(1) DEFAULT NULL,
  `DATA_STAGED` bit(1) DEFAULT NULL,
  `DIRECTION` varchar(255) NOT NULL,
  `ENTITY_ID` varchar(255) DEFAULT NULL,
  `INPUT_ORDER` int(11) DEFAULT NULL,
  `IS_READ_ONLY` bit(1) DEFAULT NULL,
  `IS_REQUIRED` bit(1) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `METADATA` varchar(4096) DEFAULT NULL,
  `PARAM_NAME` varchar(255) DEFAULT NULL,
  `OUTPUT_STREAMING` bit(1) DEFAULT NULL,
  `OVERRIDE_FILENAME` varchar(255) DEFAULT NULL,
  `REQUIRED_TO_ADDED_TO_CMD` bit(1) DEFAULT NULL,
  `SEARCH_QUERY` varchar(255) DEFAULT NULL,
  `STANDARD_INPUT` bit(1) DEFAULT NULL,
  `STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `DATA_TYPE` enum('DATA_TYPE_UNKNOWN','FLOAT','INTEGER','STDERR','STDOUT','STRING','UNRECOGNIZED','URI','URI_COLLECTION') DEFAULT NULL,
  `USER_FRIENDLY_DESCRIPTION` tinytext DEFAULT NULL,
  `PARAM_VALUE` tinytext DEFAULT NULL,
  PRIMARY KEY (`PARAM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `exec_status` (
  `STATUS_ID` varchar(255) NOT NULL,
  `ENTITY_ID` varchar(255) DEFAULT NULL,
  `ENTITY_TYPE` varchar(255) NOT NULL,
  `REASON` longtext DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `TIME_OF_STATE_CHANGE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `experiment` (
  `EXPERIMENT_ID` varchar(255) NOT NULL,
  `CLEANUP_STRATEGY` enum('ALWAYS','EXPERIMENT_CLEANUP_STRATEGY_UNKNOWN','NONE','ONLY_COMPLETED','ONLY_FAILED','UNRECOGNIZED') DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESSES` tinytext DEFAULT NULL,
  `ENABLE_EMAIL_NOTIFICATION` bit(1) DEFAULT NULL,
  `EXECUTION_ID` varchar(255) DEFAULT NULL,
  `EXPERIMENT_NAME` varchar(255) DEFAULT NULL,
  `EXPERIMENT_TYPE` enum('EXPERIMENT_TYPE_UNKNOWN','SINGLE_APPLICATION','UNRECOGNIZED','WORKFLOW') DEFAULT NULL,
  `GATEWAY_EXECUTION_ID` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `GATEWAY_INSTANCE_ID` varchar(255) DEFAULT NULL,
  `PROJECT_ID` varchar(255) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `experiment_error` (
  `ERROR_ID` varchar(255) NOT NULL,
  `EXPERIMENT_ID` varchar(255) NOT NULL,
  `ACTUAL_ERROR_MESSAGE` tinytext DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `ROOT_CAUSE_ERROR_ID_LIST` tinytext DEFAULT NULL,
  `TRANSIENT_OR_PERSISTENT` bit(1) DEFAULT NULL,
  `USER_FRIENDLY_MESSAGE` tinytext DEFAULT NULL,
  PRIMARY KEY (`ERROR_ID`,`EXPERIMENT_ID`),
  KEY `FKjb00cq721880djot1j746iisj` (`EXPERIMENT_ID`),
  CONSTRAINT `FKjb00cq721880djot1j746iisj` FOREIGN KEY (`EXPERIMENT_ID`) REFERENCES `experiment` (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `experiment_status` (
  `EXPERIMENT_ID` varchar(255) NOT NULL,
  `STATUS_ID` varchar(255) NOT NULL,
  `REASON` tinytext DEFAULT NULL,
  `STATE` enum('EXPERIMENT_STATE_CANCELED','EXPERIMENT_STATE_CANCELING','EXPERIMENT_STATE_COMPLETED','EXPERIMENT_STATE_CREATED','EXPERIMENT_STATE_EXECUTING','EXPERIMENT_STATE_FAILED','EXPERIMENT_STATE_LAUNCHED','EXPERIMENT_STATE_SCHEDULED','EXPERIMENT_STATE_UNKNOWN','EXPERIMENT_STATE_VALIDATED','UNRECOGNIZED') DEFAULT NULL,
  `TIME_OF_STATE_CHANGE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`EXPERIMENT_ID`,`STATUS_ID`),
  CONSTRAINT `FKqb1ls1tvg4m68xf586giee9qw` FOREIGN KEY (`EXPERIMENT_ID`) REFERENCES `experiment` (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `gateway` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `AIRAVATA_INTERNAL_GATEWAY_ID` varchar(255) DEFAULT NULL,
  `DECLINED_REASON` varchar(255) DEFAULT NULL,
  `DOMAIN` varchar(255) DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `GATEWAY_ACRONYM` varchar(255) DEFAULT NULL,
  `GATEWAY_ADMIN_EMAIL` varchar(255) DEFAULT NULL,
  `GATEWAY_ADMIN_FIRST_NAME` varchar(255) DEFAULT NULL,
  `GATEWAY_ADMIN_LAST_NAME` varchar(255) DEFAULT NULL,
  `GATEWAY_APPROVAL_STATUS` enum('ACTIVE','APPROVED','CANCELLED','CREATED','DEACTIVATED','DENIED','DEPLOYED','GATEWAY_APPROVAL_STATUS_UNKNOWN','REQUESTED','UNRECOGNIZED') DEFAULT NULL,
  `GATEWAY_NAME` varchar(255) DEFAULT NULL,
  `GATEWAY_PUBLIC_ABSTRACT` varchar(255) DEFAULT NULL,
  `GATEWAY_URL` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_PASSWORD_TOKEN` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_USERNAME` varchar(255) DEFAULT NULL,
  `OAUTH_CLIENT_ID` varchar(255) DEFAULT NULL,
  `OAUTH_CLIENT_SECRET` varchar(255) DEFAULT NULL,
  `REQUEST_CREATION_TIME` datetime(6) DEFAULT NULL,
  `REQUESTER_USERNAME` varchar(255) DEFAULT NULL,
  `GATEWAY_REVIEW_PROPOSAL_DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `gateway_groups` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `ADMINS_GROUP_ID` varchar(255) DEFAULT NULL,
  `DEFAULT_GATEWAY_USERS_GROUP_ID` varchar(255) DEFAULT NULL,
  `READ_ONLY_ADMINS_GROUP_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `gateway_profile` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `CS_TOKEN` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_PWD_CRED_TOKEN` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_TENANT` varchar(255) DEFAULT NULL,
  `UPDATE_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `gateway_usage_reporting_command` (
  `COMPUTE_RESOURCE_ID` varchar(255) NOT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `COMMAND` tinytext DEFAULT NULL,
  PRIMARY KEY (`COMPUTE_RESOURCE_ID`,`GATEWAY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `group_admin` (
  `GROUP_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `ADMIN_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`ADMIN_ID`,`DOMAIN_ID`,`GROUP_ID`),
  KEY `FK3g2whle70xqsodrh70u47b9b3` (`DOMAIN_ID`,`GROUP_ID`),
  CONSTRAINT `FK3g2whle70xqsodrh70u47b9b3` FOREIGN KEY (`DOMAIN_ID`, `GROUP_ID`) REFERENCES `user_group` (`DOMAIN_ID`, `GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `group_compute_resource_preference` (
  `RESOURCE_TYPE` varchar(31) NOT NULL,
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) NOT NULL,
  `LOGIN_USERNAME` varchar(255) DEFAULT NULL,
  `OVERRIDE_BY_AIRAVATA` smallint(6) DEFAULT NULL,
  `RESOURCE_CS_TOKEN` varchar(255) DEFAULT NULL,
  `SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_ID`,`GROUP_RESOURCE_PROFILE_ID`),
  KEY `FKo3ta37cwp6pyoidbhpan9vjyi` (`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKo3ta37cwp6pyoidbhpan9vjyi` FOREIGN KEY (`GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_resource_profile` (`GROUP_RESOURCE_PROFILE_ID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `group_membership` (
  `PARENT_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CHILD_ID` varchar(255) NOT NULL,
  `CHILD_TYPE` varchar(255) DEFAULT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CHILD_ID`,`DOMAIN_ID`,`PARENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `group_resource_profile` (
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) NOT NULL,
  `CREATION_TIME` bigint(20) DEFAULT NULL,
  `DEFAULT_CREDENTIAL_STORE_TOKEN` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `GROUP_RESOURCE_PROFILE_NAME` varchar(255) DEFAULT NULL,
  `UPDATE_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`GROUP_RESOURCE_PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `host_alias` (
  `RESOURCE_ID` varchar(255) NOT NULL,
  `ALIAS` varchar(255) DEFAULT NULL,
  KEY `FK67jbe78q5ysni5uf8vchi1y2s` (`RESOURCE_ID`),
  CONSTRAINT `FK67jbe78q5ysni5uf8vchi1y2s` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `compute_resource` (`RESOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `host_ipaddress` (
  `RESOURCE_ID` varchar(255) NOT NULL,
  `IP_ADDRESS` varchar(255) DEFAULT NULL,
  KEY `FKn4wrohbtppwo350622odfp11p` (`RESOURCE_ID`),
  CONSTRAINT `FKn4wrohbtppwo350622odfp11p` FOREIGN KEY (`RESOURCE_ID`) REFERENCES `compute_resource` (`RESOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `job` (
  `JOB_ID` varchar(255) NOT NULL,
  `TASK_ID` varchar(255) NOT NULL,
  `COMPUTE_RESOURCE_CONSUMED` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `EXIT_CODE` int(11) DEFAULT NULL,
  `JOB_DESCRIPTION` longtext DEFAULT NULL,
  `JOB_NAME` varchar(255) DEFAULT NULL,
  `PROCESS_ID` varchar(255) DEFAULT NULL,
  `STD_ERR` longtext DEFAULT NULL,
  `STD_OUT` longtext DEFAULT NULL,
  `WORKING_DIR` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`JOB_ID`,`TASK_ID`),
  KEY `FK9740e6755simbv531btch12qx` (`TASK_ID`),
  CONSTRAINT `FK9740e6755simbv531btch12qx` FOREIGN KEY (`TASK_ID`) REFERENCES `task` (`TASK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `job_manager_command` (
  `COMMAND_TYPE` enum('CHECK_JOB','DELETION','JOB_MANAGER_COMMAND_UNKNOWN','JOB_MONITORING','SHOW_CLUSTER_INFO','SHOW_NO_OF_PENDING_JOBS','SHOW_NO_OF_RUNNING_JOBS','SHOW_QUEUE','SHOW_RESERVATION','SHOW_START','SUBMISSION','UNRECOGNIZED') NOT NULL,
  `RESOURCE_JOB_MANAGER_ID` varchar(255) NOT NULL,
  `COMMAND` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`COMMAND_TYPE`,`RESOURCE_JOB_MANAGER_ID`),
  KEY `FK8y5gcd5mulypltnxt4sypiiuu` (`RESOURCE_JOB_MANAGER_ID`),
  CONSTRAINT `FK8y5gcd5mulypltnxt4sypiiuu` FOREIGN KEY (`RESOURCE_JOB_MANAGER_ID`) REFERENCES `resource_job_manager` (`RESOURCE_JOB_MANAGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `notification` (
  `NOTIFICATION_ID` varchar(255) NOT NULL,
  `CREATION_DATE` datetime(6) DEFAULT NULL,
  `EXPIRATION_DATE` datetime(6) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `NOTIFICATION_MESSAGE` varchar(4096) DEFAULT NULL,
  `PRIORITY` enum('HIGH','LOW','NORMAL','NOTIFICATION_PRIORITY_UNKNOWN','UNRECOGNIZED') DEFAULT NULL,
  `PUBLISHED_DATE` datetime(6) DEFAULT NULL,
  `TITLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`NOTIFICATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `parallelism_command` (
  `COMMAND_TYPE` enum('APPLICATION_PARALLELISM_TYPE_UNKNOWN','CCM','CRAY_MPI','MPI','OPENMP','OPENMP_MPI','SERIAL','UNRECOGNIZED') NOT NULL,
  `RESOURCE_JOB_MANAGER_ID` varchar(255) NOT NULL,
  `COMMAND` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`COMMAND_TYPE`,`RESOURCE_JOB_MANAGER_ID`),
  KEY `FK1cggtq4i7gweg6dir32jb1xhh` (`RESOURCE_JOB_MANAGER_ID`),
  CONSTRAINT `FK1cggtq4i7gweg6dir32jb1xhh` FOREIGN KEY (`RESOURCE_JOB_MANAGER_ID`) REFERENCES `resource_job_manager` (`RESOURCE_JOB_MANAGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `parser` (
  `PARSER_ID` varchar(255) NOT NULL,
  `EXECUTION_COMMAND` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `IMAGE_NAME` varchar(255) DEFAULT NULL,
  `INPUT_DIR_PATH` varchar(255) DEFAULT NULL,
  `INPUT_FILES_JSON` tinytext DEFAULT NULL,
  `OUTPUT_DIR_PATH` varchar(255) DEFAULT NULL,
  `OUTPUT_FILES_JSON` tinytext DEFAULT NULL,
  PRIMARY KEY (`PARSER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `parsing_template` (
  `PARSING_TEMPLATE_ID` varchar(255) NOT NULL,
  `APP_INTERFACE_ID` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `INITIAL_INPUTS_JSON` tinytext DEFAULT NULL,
  `PARSER_CONNECTIONS_JSON` tinytext DEFAULT NULL,
  PRIMARY KEY (`PARSING_TEMPLATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `permission_type` (
  `PERMISSION_TYPE_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`PERMISSION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `plan` (
  `PLAN_ID` varchar(255) NOT NULL,
  `DATA` text DEFAULT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`PLAN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `process` (
  `PROCESS_ID` varchar(255) NOT NULL,
  `APPLICATION_DEPLOYMENT_ID` varchar(255) DEFAULT NULL,
  `APPLICATION_INTERFACE_ID` varchar(255) DEFAULT NULL,
  `COMPUTE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `EMAIL_ADDRESSES` tinytext DEFAULT NULL,
  `ENABLE_EMAIL_NOTIFICATION` bit(1) DEFAULT NULL,
  `EXPERIMENT_DATA_DIR` varchar(512) DEFAULT NULL,
  `EXPERIMENT_ID` varchar(255) DEFAULT NULL,
  `GATEWAY_EXECUTION_ID` varchar(255) DEFAULT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) DEFAULT NULL,
  `INPUT_STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime(6) DEFAULT NULL,
  `OUTPUT_STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `PROCESS_DETAIL` tinytext DEFAULT NULL,
  `TASK_DAG` tinytext DEFAULT NULL,
  `USE_USER_CR_PREF` bit(1) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PROCESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `process_resource_schedule` (
  `PROCESS_ID` varchar(255) NOT NULL,
  `NODE_COUNT` int(11) DEFAULT NULL,
  `NUMBER_OF_THREADS` int(11) DEFAULT NULL,
  `OVERRIDE_ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `OVERRIDE_LOGIN_USER_NAME` varchar(255) DEFAULT NULL,
  `OVERRIDE_SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  `QUEUE_NAME` varchar(255) DEFAULT NULL,
  `RESOURCE_HOST_ID` varchar(255) DEFAULT NULL,
  `STATIC_WORKING_DIR` varchar(255) DEFAULT NULL,
  `TOTAL_CPU_COUNT` int(11) DEFAULT NULL,
  `TOTAL_PHYSICAL_MEMORY` int(11) DEFAULT NULL,
  `WALL_TIME_LIMIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`PROCESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `project` (
  `PROJECT_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `PROJECT_NAME` varchar(255) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`PROJECT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `project_dataset` (
  `project_id` varchar(48) NOT NULL,
  `dataset_resource_id` varchar(48) NOT NULL,
  PRIMARY KEY (`project_id`,`dataset_resource_id`),
  KEY `FKm5n7mvaxvg0advhbpq87l8l97` (`dataset_resource_id`),
  CONSTRAINT `FKhjawdhkty2we04kbmiqdx1oh2` FOREIGN KEY (`project_id`) REFERENCES `research_project` (`id`),
  CONSTRAINT `FKm5n7mvaxvg0advhbpq87l8l97` FOREIGN KEY (`dataset_resource_id`) REFERENCES `dataset_resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `queue_status` (
  `HOST_NAME` varchar(255) NOT NULL,
  `QUEUE_NAME` varchar(255) NOT NULL,
  `CREATED_TIME` decimal(38,0) NOT NULL,
  `QUEUE_UP` bit(1) DEFAULT NULL,
  `QUEUED_JOBS` int(11) DEFAULT NULL,
  `RUNNING_JOBS` int(11) DEFAULT NULL,
  PRIMARY KEY (`HOST_NAME`,`QUEUE_NAME`,`CREATED_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `repository_resource` (
  `repositoryUrl` varchar(255) NOT NULL,
  `id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK81qd7hu5299qpu6ly7vhqjuib` FOREIGN KEY (`id`) REFERENCES `resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `research_io_param` (
  `PARAM_ID` varchar(255) NOT NULL,
  `APPLICATION_ARGUMENT` varchar(255) DEFAULT NULL,
  `DATA_MOVEMENT` bit(1) DEFAULT NULL,
  `DATA_STAGED` bit(1) DEFAULT NULL,
  `DIRECTION` varchar(255) NOT NULL,
  `ENTITY_ID` varchar(255) DEFAULT NULL,
  `INPUT_ORDER` int(11) DEFAULT NULL,
  `IS_READ_ONLY` bit(1) DEFAULT NULL,
  `IS_REQUIRED` bit(1) DEFAULT NULL,
  `LOCATION` varchar(255) DEFAULT NULL,
  `METADATA` varchar(4096) DEFAULT NULL,
  `PARAM_NAME` varchar(255) DEFAULT NULL,
  `OUTPUT_STREAMING` bit(1) DEFAULT NULL,
  `OVERRIDE_FILENAME` varchar(255) DEFAULT NULL,
  `REQUIRED_TO_ADDED_TO_CMD` bit(1) DEFAULT NULL,
  `SEARCH_QUERY` varchar(255) DEFAULT NULL,
  `STANDARD_INPUT` bit(1) DEFAULT NULL,
  `STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `DATA_TYPE` enum('DATA_TYPE_UNKNOWN','FLOAT','INTEGER','STDERR','STDOUT','STRING','UNRECOGNIZED','URI','URI_COLLECTION') DEFAULT NULL,
  `USER_FRIENDLY_DESCRIPTION` tinytext DEFAULT NULL,
  `PARAM_VALUE` tinytext DEFAULT NULL,
  PRIMARY KEY (`PARAM_ID`),
  KEY `FKkbn5prcl51e710tik76wj4pei` (`ENTITY_ID`),
  CONSTRAINT `FKkbn5prcl51e710tik76wj4pei` FOREIGN KEY (`ENTITY_ID`) REFERENCES `experiment` (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `research_project` (
  `id` varchar(48) NOT NULL,
  `createdAt` datetime(6) NOT NULL,
  `name` varchar(255) NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `state` enum('ACTIVE','DELETED') NOT NULL,
  `updatedAt` datetime(6) NOT NULL,
  `repository_resource_id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK9i0i273bj592y9u9afn1jdr87` (`repository_resource_id`),
  CONSTRAINT `FK9i0i273bj592y9u9afn1jdr87` FOREIGN KEY (`repository_resource_id`) REFERENCES `repository_resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `resource` (
  `id` varchar(48) NOT NULL,
  `createdAt` datetime(6) NOT NULL,
  `description` text NOT NULL,
  `headerImage` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `privacy` enum('PRIVATE','PUBLIC') NOT NULL,
  `state` enum('ACTIVE','DELETED') NOT NULL,
  `updatedAt` datetime(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `resource_authors` (
  `resource_id` varchar(48) NOT NULL,
  `author_id` varchar(255) DEFAULT NULL,
  KEY `FKtff3m72vmt398januomdg5ym3` (`resource_id`),
  CONSTRAINT `FKtff3m72vmt398januomdg5ym3` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `resource_job_manager` (
  `RESOURCE_JOB_MANAGER_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) NOT NULL,
  `JOB_MANAGER_BIN_PATH` varchar(255) DEFAULT NULL,
  `PUSH_MONITORING_ENDPOINT` varchar(255) DEFAULT NULL,
  `RESOURCE_JOB_MANAGER_TYPE` enum('AIRAVATA_CUSTOM','CLOUD','FORK','HTCONDOR','LSF','PBS','RESOURCE_JOB_MANAGER_TYPE_UNKNOWN','SLURM','UGE','UNRECOGNIZED') DEFAULT NULL,
  `UPDATE_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_JOB_MANAGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `resource_star` (
  `id` varchar(48) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `resource_id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_resource_star_user_resource` (`user_id`,`resource_id`),
  KEY `FKe8g40jht9trlg7x979t2v0qm1` (`resource_id`),
  CONSTRAINT `FKe8g40jht9trlg7x979t2v0qm1` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `resource_tags` (
  `resource_id` varchar(48) NOT NULL,
  `tag_id` varchar(48) NOT NULL,
  PRIMARY KEY (`resource_id`,`tag_id`),
  KEY `FKa9brxa2n8bug4cb8tbeb5n44t` (`tag_id`),
  CONSTRAINT `FKa9brxa2n8bug4cb8tbeb5n44t` FOREIGN KEY (`tag_id`) REFERENCES `tag` (`id`),
  CONSTRAINT `FKd5k9ys6jr0jpb1e9909af2ytu` FOREIGN KEY (`resource_id`) REFERENCES `resource` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `session` (
  `id` varchar(48) NOT NULL,
  `createdAt` datetime(6) NOT NULL,
  `sessionName` varchar(255) NOT NULL,
  `status` enum('CREATED','ERROR','FINISHED','RUNNING','TERMINATED') NOT NULL,
  `updatedAt` datetime(6) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `project_id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKc1yi1eldihmm4gfjk8p2qjcq3` (`project_id`),
  CONSTRAINT `FKc1yi1eldihmm4gfjk8p2qjcq3` FOREIGN KEY (`project_id`) REFERENCES `research_project` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `sharing` (
  `PERMISSION_TYPE_ID` varchar(152) NOT NULL,
  `INHERITED_PARENT_ID` varchar(152) NOT NULL,
  `GROUP_ID` varchar(152) NOT NULL,
  `ENTITY_ID` varchar(152) NOT NULL,
  `DOMAIN_ID` varchar(152) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `SHARING_TYPE` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`ENTITY_ID`,`GROUP_ID`,`INHERITED_PARENT_ID`,`PERMISSION_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `sharing_user` (
  `USER_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `slurm_group_compute_resource_preference` (
  `ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `SSH_PROVISIONER_CONFIG_JSON` tinytext DEFAULT NULL,
  `PREFERED_BATCH_QUEUE` varchar(255) DEFAULT NULL,
  `QUALITY_OF_SERVICE` varchar(255) DEFAULT NULL,
  `SSH_ACCOUNT_PROVISIONER` varchar(255) DEFAULT NULL,
  `SSH_ACCOUNT_PROVISIONER_ADDITIONAL_INFO` varchar(255) DEFAULT NULL,
  `USAGE_REPORTING_GATEWAY_ID` varchar(255) DEFAULT NULL,
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`RESOURCE_ID`,`GROUP_RESOURCE_PROFILE_ID`),
  CONSTRAINT `FKhtn4xjjd92ufhg1aeubl3qxcl` FOREIGN KEY (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`) REFERENCES `group_compute_resource_preference` (`RESOURCE_ID`, `GROUP_RESOURCE_PROFILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `storage_preference` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `STORAGE_RESOURCE_ID` varchar(255) NOT NULL,
  `FS_ROOT_LOCATION` varchar(255) DEFAULT NULL,
  `LOGIN_USERNAME` varchar(255) DEFAULT NULL,
  `RESOURCE_CS_TOKEN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`,`STORAGE_RESOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `storage_resource` (
  `STORAGE_RESOURCE_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `HOST_NAME` varchar(255) DEFAULT NULL,
  `SFTP_PORT` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `UPDATE_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`STORAGE_RESOURCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `tag` (
  `id` varchar(48) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_tag_value` (`value`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `task` (
  `TASK_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `LAST_UPDATE_TIME` datetime(6) DEFAULT NULL,
  `PARENT_PROCESS_ID` varchar(255) DEFAULT NULL,
  `SUB_TASK_MODEL` tinyblob DEFAULT NULL,
  `TASK_DETAIL` tinytext DEFAULT NULL,
  `TASK_TYPE` enum('DATA_STAGING','ENV_CLEANUP','ENV_SETUP','JOB_SUBMISSION','MONITORING','OUTPUT_FETCHING','TASK_TYPES_UNKNOWN','UNRECOGNIZED') DEFAULT NULL,
  PRIMARY KEY (`TASK_ID`),
  KEY `FKi0ugwcodlojq6dwo17d8eh2y4` (`PARENT_PROCESS_ID`),
  CONSTRAINT `FKi0ugwcodlojq6dwo17d8eh2y4` FOREIGN KEY (`PARENT_PROCESS_ID`) REFERENCES `process` (`PROCESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_compute_resource_preference` (
  `RESOURCE_ID` varchar(255) NOT NULL,
  `GATEWAY_ID` varchar(255) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  `ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `LOGIN_USERNAME` varchar(255) DEFAULT NULL,
  `PREFERED_BATCH_QUEUE` varchar(255) DEFAULT NULL,
  `QUALITY_OF_SERVICE` varchar(255) DEFAULT NULL,
  `RESERVATION` varchar(255) DEFAULT NULL,
  `RESERVATION_END_TIME` datetime(6) DEFAULT NULL,
  `RESERVATION_START_TIME` datetime(6) DEFAULT NULL,
  `RESOURCE_CS_TOKEN` varchar(255) DEFAULT NULL,
  `SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  `VALIDATED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`RESOURCE_ID`,`GATEWAY_ID`,`USER_ID`),
  KEY `FK6jy3r5xrlo0edsvhnp84i2tv` (`USER_ID`,`GATEWAY_ID`),
  CONSTRAINT `FK6jy3r5xrlo0edsvhnp84i2tv` FOREIGN KEY (`USER_ID`, `GATEWAY_ID`) REFERENCES `user_resource_profile` (`GATEWAY_ID`, `USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_configuration_data` (
  `EXPERIMENT_ID` varchar(255) NOT NULL,
  `AIRAVATA_AUTO_SCHEDULE` bit(1) DEFAULT NULL,
  `EXPERIMENT_DATA_DIR` varchar(512) DEFAULT NULL,
  `GROUP_RESOURCE_PROFILE_ID` varchar(255) DEFAULT NULL,
  `INPUT_STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `NODE_COUNT` int(11) DEFAULT NULL,
  `NUMBER_OF_THREADS` int(11) DEFAULT NULL,
  `OUTPUT_STORAGE_RESOURCE_ID` varchar(255) DEFAULT NULL,
  `OVERRIDE_ALLOCATION_PROJECT_NUMBER` varchar(255) DEFAULT NULL,
  `OVERRIDE_LOGIN_USER_NAME` varchar(255) DEFAULT NULL,
  `OVERRIDE_MANUAL_SCHEDULED_PARAMS` bit(1) DEFAULT NULL,
  `OVERRIDE_SCRATCH_LOCATION` varchar(255) DEFAULT NULL,
  `QUEUE_NAME` varchar(255) DEFAULT NULL,
  `RESOURCE_HOST_ID` varchar(255) DEFAULT NULL,
  `SHARE_EXPERIMENT_PUBLICALLY` bit(1) DEFAULT NULL,
  `STATIC_WORKING_DIR` varchar(255) DEFAULT NULL,
  `THROTTLE_RESOURCES` bit(1) DEFAULT NULL,
  `TOTAL_CPU_COUNT` int(11) DEFAULT NULL,
  `TOTAL_PHYSICAL_MEMORY` int(11) DEFAULT NULL,
  `IS_USE_USER_CR_PREF` bit(1) DEFAULT NULL,
  `WALL_TIME_LIMIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`EXPERIMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_group` (
  `GROUP_ID` varchar(255) NOT NULL,
  `DOMAIN_ID` varchar(255) NOT NULL,
  `CREATED_TIME` bigint(20) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `GROUP_CARDINALITY` varchar(255) DEFAULT NULL,
  `GROUP_TYPE` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `OWNER_ID` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`,`GROUP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_profile` (
  `AIRAVATA_INTERNAL_USER_ID` varchar(255) NOT NULL,
  `COMMENTS` tinytext DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `GATEWAY_ID` varchar(255) DEFAULT NULL,
  `GPG_KEY` tinytext DEFAULT NULL,
  `HOME_ORGANIZATION` varchar(255) DEFAULT NULL,
  `LAST_ACCESS_TIME` datetime(6) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `MIDDLE_NAME` varchar(255) DEFAULT NULL,
  `NAME_PREFIX` varchar(255) DEFAULT NULL,
  `NAME_SUFFIX` varchar(255) DEFAULT NULL,
  `ORCID_ID` varchar(255) DEFAULT NULL,
  `ORIGINATION_AFFILIATION` varchar(255) DEFAULT NULL,
  `STATE` varchar(255) DEFAULT NULL,
  `TIME_ZONE` varchar(255) DEFAULT NULL,
  `USER_ID` varchar(255) DEFAULT NULL,
  `USER_MODEL_VERSION` varchar(255) DEFAULT NULL,
  `VALID_UNTIL` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`AIRAVATA_INTERNAL_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_profile_email` (
  `AIRAVATA_INTERNAL_USER_ID` varchar(255) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  KEY `FKfossyc28pyv046gqxfu1finn7` (`AIRAVATA_INTERNAL_USER_ID`),
  CONSTRAINT `FKfossyc28pyv046gqxfu1finn7` FOREIGN KEY (`AIRAVATA_INTERNAL_USER_ID`) REFERENCES `user_profile` (`AIRAVATA_INTERNAL_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_profile_labeled_uri` (
  `AIRAVATA_INTERNAL_USER_ID` varchar(255) NOT NULL,
  `LABELED_URI` varchar(255) DEFAULT NULL,
  KEY `FKmycvdh3ihvdxuja6wcr1oxjbp` (`AIRAVATA_INTERNAL_USER_ID`),
  CONSTRAINT `FKmycvdh3ihvdxuja6wcr1oxjbp` FOREIGN KEY (`AIRAVATA_INTERNAL_USER_ID`) REFERENCES `user_profile` (`AIRAVATA_INTERNAL_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_profile_nationality` (
  `AIRAVATA_INTERNAL_USER_ID` varchar(255) NOT NULL,
  `NATIONALITY` varchar(255) DEFAULT NULL,
  KEY `FKptv69922abx8hhm92sipm1skm` (`AIRAVATA_INTERNAL_USER_ID`),
  CONSTRAINT `FKptv69922abx8hhm92sipm1skm` FOREIGN KEY (`AIRAVATA_INTERNAL_USER_ID`) REFERENCES `user_profile` (`AIRAVATA_INTERNAL_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_profile_phone` (
  `AIRAVATA_INTERNAL_USER_ID` varchar(255) NOT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  KEY `FKsq7y2v14vyy3l2mjbb6w9q1rp` (`AIRAVATA_INTERNAL_USER_ID`),
  CONSTRAINT `FKsq7y2v14vyy3l2mjbb6w9q1rp` FOREIGN KEY (`AIRAVATA_INTERNAL_USER_ID`) REFERENCES `user_profile` (`AIRAVATA_INTERNAL_USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_resource_profile` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  `CREATION_TIME` datetime(6) DEFAULT NULL,
  `CS_TOKEN` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_PWD_CRED_TOKEN` varchar(255) DEFAULT NULL,
  `IDENTITY_SERVER_TENANT` varchar(255) DEFAULT NULL,
  `UPDATE_TIME` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_storage_preference` (
  `GATEWAY_ID` varchar(255) NOT NULL,
  `STORAGE_RESOURCE_ID` varchar(255) NOT NULL,
  `USER_ID` varchar(255) NOT NULL,
  `FS_ROOT_LOCATION` varchar(255) DEFAULT NULL,
  `LOGIN_USERNAME` varchar(255) DEFAULT NULL,
  `RESOURCE_CS_TOKEN` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`GATEWAY_ID`,`STORAGE_RESOURCE_ID`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE `experiment_set` (
  `id` varchar(48) NOT NULL,
  `createdAt` datetime(6) NOT NULL,
  `gatewayId` varchar(255) NOT NULL,
  `owner` varchar(255) NOT NULL,
  `setName` varchar(255) NOT NULL,
  `sweepSpecJson` longtext DEFAULT NULL,
  `updatedAt` datetime(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `experiment_set_member` (
  `id` varchar(48) NOT NULL,
  `experimentId` varchar(255) NOT NULL,
  `ordinal` int(11) NOT NULL,
  `experiment_set_id` varchar(48) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK7jxgcnx5bslj9v24wr47r5j38` (`experiment_set_id`),
  CONSTRAINT `FK7jxgcnx5bslj9v24wr47r5j38` FOREIGN KEY (`experiment_set_id`) REFERENCES `experiment_set` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
CREATE TABLE `user_preferences` (
  `gatewayId` varchar(255) NOT NULL,
  `userId` varchar(255) NOT NULL,
  `preferencesJson` text DEFAULT NULL,
  `createdAt` datetime(6) DEFAULT NULL,
  `updatedAt` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`gatewayId`,`userId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

SET FOREIGN_KEY_CHECKS=1;
