-- Schema consolidation: combines data movement unification, legacy table cleanup,
-- gateway merge, job submission consolidation, and new entity tables.

-- ============================================================================
-- Part 1: Unify data movement (formerly V2)
-- ============================================================================

-- Step 1: Make DATA_MOVEMENT_INTERFACE standalone
-- Drop the old composite PK and FK to COMPUTE_RESOURCE
ALTER TABLE DATA_MOVEMENT_INTERFACE DROP FOREIGN KEY FK_DMI_RESOURCE;
ALTER TABLE DATA_MOVEMENT_INTERFACE DROP PRIMARY KEY;

-- Rename COMPUTE_RESOURCE_ID to RESOURCE_ID (generic)
ALTER TABLE DATA_MOVEMENT_INTERFACE CHANGE COLUMN COMPUTE_RESOURCE_ID RESOURCE_ID VARCHAR(255) NOT NULL;

-- Add new PK on just the DM ID + RESOURCE_ID
ALTER TABLE DATA_MOVEMENT_INTERFACE ADD PRIMARY KEY (RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID);

-- Step 2: Migrate STORAGE_INTERFACE data into DATA_MOVEMENT_INTERFACE
INSERT IGNORE INTO DATA_MOVEMENT_INTERFACE (RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID, CREATION_TIME, DATA_MOVEMENT_PROTOCOL, PRIORITY_ORDER, UPDATE_TIME)
SELECT STORAGE_RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID, CREATION_TIME, DATA_MOVEMENT_PROTOCOL, PRIORITY_ORDER, UPDATE_TIME
FROM STORAGE_INTERFACE;

-- Step 3: Drop the now-redundant STORAGE_INTERFACE table
DROP TABLE IF EXISTS STORAGE_INTERFACE;

-- ============================================================================
-- Part 2: Drop legacy user tables (formerly V3)
-- ============================================================================

-- Drop legacy user tables that have no JPA entity mapping.
-- USER_PROFILE (iam-service) is the canonical user table.
-- SHARING_USER (sharing-service) handles per-domain identity.

-- Drop FK from PROJECT_USER to USERS if it exists
SET @fk_exists = (SELECT COUNT(*) FROM information_schema.TABLE_CONSTRAINTS
                  WHERE CONSTRAINT_NAME = 'FK_PROJECT_USER_USER'
                  AND TABLE_NAME = 'PROJECT_USER'
                  AND TABLE_SCHEMA = DATABASE());
SET @stmt = IF(@fk_exists > 0,
    'ALTER TABLE PROJECT_USER DROP FOREIGN KEY FK_PROJECT_USER_USER',
    'SELECT 1');
PREPARE s FROM @stmt;
EXECUTE s;
DEALLOCATE PREPARE s;

DROP TABLE IF EXISTS GATEWAY_WORKER;
DROP TABLE IF EXISTS USERS;

-- ============================================================================
-- Part 3: Merge TENANT_GATEWAY into GATEWAY (formerly V4)
-- ============================================================================

-- Merge TENANT_GATEWAY into GATEWAY. Both have identical schemas.
-- GATEWAY keeps its PK (GATEWAY_ID). AIRAVATA_INTERNAL_GATEWAY_ID is added as unique column.

ALTER TABLE GATEWAY ADD COLUMN IF NOT EXISTS AIRAVATA_INTERNAL_GATEWAY_ID VARCHAR(255);

-- Backfill from TENANT_GATEWAY where possible
UPDATE GATEWAY g
  INNER JOIN TENANT_GATEWAY tg ON g.GATEWAY_ID = tg.GATEWAY_ID
  SET g.AIRAVATA_INTERNAL_GATEWAY_ID = tg.AIRAVATA_INTERNAL_GATEWAY_ID;

-- For rows without a TENANT_GATEWAY match, generate a UUID
UPDATE GATEWAY SET AIRAVATA_INTERNAL_GATEWAY_ID = UUID()
  WHERE AIRAVATA_INTERNAL_GATEWAY_ID IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_gateway_internal_id ON GATEWAY (AIRAVATA_INTERNAL_GATEWAY_ID);

DROP TABLE IF EXISTS TENANT_GATEWAY;

-- ============================================================================
-- Part 4: Consolidate job submission tables (formerly V5)
-- ============================================================================

-- Consolidate 6 separate job submission tables into COMPUTE_JOB_SUBMISSION.
-- Old tables are dropped after data migration.

CREATE TABLE IF NOT EXISTS COMPUTE_JOB_SUBMISSION (
    SUBMISSION_ID          VARCHAR(255)  NOT NULL,
    SUBMISSION_TYPE        VARCHAR(50)   NOT NULL,
    SECURITY_PROTOCOL      VARCHAR(255),
    CREATION_TIME          TIMESTAMP     NULL,
    UPDATE_TIME            TIMESTAMP     NULL,
    RESOURCE_JOB_MANAGER_ID VARCHAR(255),
    CONFIG_JSON            LONGTEXT,
    PRIMARY KEY (SUBMISSION_ID),
    CONSTRAINT FK_CJS_RJM FOREIGN KEY (RESOURCE_JOB_MANAGER_ID)
        REFERENCES RESOURCE_JOB_MANAGER (RESOURCE_JOB_MANAGER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Migrate SSH_JOB_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    JOB_SUBMISSION_INTERFACE_ID,
    'SSH',
    SECURITY_PROTOCOL,
    CREATION_TIME,
    UPDATE_TIME,
    RESOURCE_JOB_MANAGER_ID,
    JSON_OBJECT(
        'sshPort',               SSH_PORT,
        'alternativeSshHostname', COALESCE(ALTERNATIVE_SSH_HOSTNAME, ''),
        'monitorMode',            COALESCE(MONITOR_MODE, '')
    )
FROM SSH_JOB_SUBMISSION;

-- Migrate LOCAL_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    JOB_SUBMISSION_INTERFACE_ID,
    'LOCAL',
    SECURITY_PROTOCOL,
    CREATION_TIME,
    UPDATE_TIME,
    RESOURCE_JOB_MANAGER_ID,
    NULL
FROM LOCAL_SUBMISSION;

-- Migrate CLOUD_JOB_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    JOB_SUBMISSION_INTERFACE_ID,
    'CLOUD',
    SECURITY_PROTOCOL,
    NULL,
    NULL,
    NULL,
    JSON_OBJECT(
        'nodeId',          COALESCE(NODE_ID, ''),
        'executableType',  COALESCE(EXECUTABLE_TYPE, ''),
        'providerName',    COALESCE(PROVIDER_NAME, ''),
        'userAccountName', COALESCE(USER_ACCOUNT_NAME, '')
    )
FROM CLOUD_JOB_SUBMISSION;

-- Migrate UNICORE_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    SUBMISSION_ID,
    'UNICORE',
    SECURITY_PROTOCAL,
    NULL,
    NULL,
    NULL,
    JSON_OBJECT('unicoreEndPointURL', COALESCE(UNICORE_ENDPOINT_URL, ''))
FROM UNICORE_SUBMISSION;

-- Migrate GLOBUS_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    SUBMISSION_ID,
    'GLOBUS',
    SECURITY_PROTOCAL,
    NULL,
    NULL,
    NULL,
    JSON_OBJECT('resourceJobManager', COALESCE(RESOURCE_JOB_MANAGER, ''))
FROM GLOBUS_SUBMISSION;

-- Migrate GSISSH_SUBMISSION
INSERT INTO COMPUTE_JOB_SUBMISSION
    (SUBMISSION_ID, SUBMISSION_TYPE, SECURITY_PROTOCOL, CREATION_TIME, UPDATE_TIME, RESOURCE_JOB_MANAGER_ID, CONFIG_JSON)
SELECT
    SUBMISSION_ID,
    'GSISSH',
    NULL,
    NULL,
    NULL,
    NULL,
    JSON_OBJECT(
        'installedPath',     COALESCE(INSTALLED_PATH, ''),
        'monitorMode',       COALESCE(MONITOR_MODE, ''),
        'sshPort',           SSH_PORT,
        'resourceJobManager', COALESCE(RESOURCE_JOB_MANAGER, '')
    )
FROM GSISSH_SUBMISSION;

-- Drop old tables (auxiliary tables first to avoid FK violations)
DROP TABLE IF EXISTS GSISSH_EXPORT;
DROP TABLE IF EXISTS GSISSH_POSTJOBCOMMAND;
DROP TABLE IF EXISTS GSISSH_PREJOBCOMMAND;
DROP TABLE IF EXISTS GSISSH_SUBMISSION;
DROP TABLE IF EXISTS GLOBUS_GK_ENDPOINT;
DROP TABLE IF EXISTS GLOBUS_SUBMISSION;
DROP TABLE IF EXISTS UNICORE_SUBMISSION;
DROP TABLE IF EXISTS CLOUD_JOB_SUBMISSION;
DROP TABLE IF EXISTS LOCAL_SUBMISSION;
DROP TABLE IF EXISTS SSH_JOB_SUBMISSION;

-- ============================================================================
-- Part 5: Create new consolidated entity tables
-- ============================================================================

-- APP_IO_PARAM: application interface input/output parameters (research-service)
CREATE TABLE IF NOT EXISTS APP_IO_PARAM (
    PARAM_ID                VARCHAR(255)  NOT NULL,
    INTERFACE_ID            VARCHAR(255),
    DIRECTION               VARCHAR(50)   NOT NULL,
    PARAM_NAME              VARCHAR(255),
    PARAM_VALUE             VARCHAR(255),
    DATA_TYPE               VARCHAR(255),
    APPLICATION_ARGUMENT    VARCHAR(255),
    IS_REQUIRED             BOOLEAN       DEFAULT FALSE,
    REQUIRED_TO_ADDED_TO_CMD BOOLEAN      DEFAULT FALSE,
    METADATA                VARCHAR(4096),
    STANDARD_INPUT          BOOLEAN       DEFAULT FALSE,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    INPUT_ORDER             INT           DEFAULT 0,
    DATA_STAGED             BOOLEAN       DEFAULT FALSE,
    IS_READ_ONLY            BOOLEAN       DEFAULT FALSE,
    OVERRIDE_FILENAME       VARCHAR(255),
    DATA_MOVEMENT           BOOLEAN       DEFAULT FALSE,
    LOCATION                VARCHAR(255),
    SEARCH_QUERY            VARCHAR(255),
    OUTPUT_STREAMING        BOOLEAN       DEFAULT FALSE,
    PRIMARY KEY (PARAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- EXEC_ERROR: consolidated execution errors for processes and tasks (orchestration-service)
CREATE TABLE IF NOT EXISTS EXEC_ERROR (
    ERROR_ID                VARCHAR(255)  NOT NULL,
    ENTITY_TYPE             VARCHAR(50)   NOT NULL,
    ENTITY_ID               VARCHAR(255),
    CREATION_TIME           TIMESTAMP     NULL,
    ACTUAL_ERROR_MESSAGE    LONGTEXT,
    USER_FRIENDLY_MESSAGE   LONGTEXT,
    TRANSIENT_OR_PERSISTENT BOOLEAN       DEFAULT FALSE,
    ROOT_CAUSE_ERROR_ID_LIST LONGTEXT,
    PRIMARY KEY (ERROR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- EXEC_IO_PARAM: consolidated process input/output parameters (orchestration-service)
CREATE TABLE IF NOT EXISTS EXEC_IO_PARAM (
    PARAM_ID                VARCHAR(255)  NOT NULL,
    ENTITY_ID               VARCHAR(255),
    DIRECTION               VARCHAR(50)   NOT NULL,
    PARAM_NAME              VARCHAR(255),
    PARAM_VALUE             LONGTEXT,
    DATA_TYPE               VARCHAR(255),
    APPLICATION_ARGUMENT    VARCHAR(255),
    IS_REQUIRED             BOOLEAN       DEFAULT FALSE,
    REQUIRED_TO_ADDED_TO_CMD BOOLEAN      DEFAULT FALSE,
    METADATA                VARCHAR(4096),
    STORAGE_RESOURCE_ID     VARCHAR(255),
    STANDARD_INPUT          BOOLEAN       DEFAULT FALSE,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    INPUT_ORDER             INT           DEFAULT 0,
    DATA_STAGED             BOOLEAN       DEFAULT FALSE,
    IS_READ_ONLY            BOOLEAN       DEFAULT FALSE,
    OVERRIDE_FILENAME       VARCHAR(255),
    DATA_MOVEMENT           BOOLEAN       DEFAULT FALSE,
    LOCATION                VARCHAR(255),
    SEARCH_QUERY            VARCHAR(255),
    OUTPUT_STREAMING        BOOLEAN       DEFAULT FALSE,
    PRIMARY KEY (PARAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- EXEC_STATUS: consolidated execution statuses for processes, tasks, and jobs (orchestration-service)
CREATE TABLE IF NOT EXISTS EXEC_STATUS (
    STATUS_ID               VARCHAR(255)  NOT NULL,
    ENTITY_TYPE             VARCHAR(50)   NOT NULL,
    ENTITY_ID               VARCHAR(255),
    STATE                   VARCHAR(255),
    TIME_OF_STATE_CHANGE    TIMESTAMP     NULL,
    REASON                  LONGTEXT,
    PRIMARY KEY (STATUS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- RESEARCH_IO_PARAM: experiment input/output parameters (research-service)
CREATE TABLE IF NOT EXISTS RESEARCH_IO_PARAM (
    PARAM_ID                VARCHAR(255)  NOT NULL,
    ENTITY_ID               VARCHAR(255),
    DIRECTION               VARCHAR(50)   NOT NULL,
    PARAM_NAME              VARCHAR(255),
    PARAM_VALUE             LONGTEXT,
    DATA_TYPE               VARCHAR(255),
    APPLICATION_ARGUMENT    VARCHAR(255),
    IS_REQUIRED             BOOLEAN       DEFAULT FALSE,
    REQUIRED_TO_ADDED_TO_CMD BOOLEAN      DEFAULT FALSE,
    METADATA                VARCHAR(4096),
    STORAGE_RESOURCE_ID     VARCHAR(255),
    STANDARD_INPUT          BOOLEAN       DEFAULT FALSE,
    USER_FRIENDLY_DESCRIPTION LONGTEXT,
    INPUT_ORDER             INT           DEFAULT 0,
    DATA_STAGED             BOOLEAN       DEFAULT FALSE,
    IS_READ_ONLY            BOOLEAN       DEFAULT FALSE,
    OVERRIDE_FILENAME       VARCHAR(255),
    DATA_MOVEMENT           BOOLEAN       DEFAULT FALSE,
    LOCATION                VARCHAR(255),
    SEARCH_QUERY            VARCHAR(255),
    OUTPUT_STREAMING        BOOLEAN       DEFAULT FALSE,
    PRIMARY KEY (PARAM_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- STORAGE_DATA_MOVEMENT: unified data movement entity (storage-service)
CREATE TABLE IF NOT EXISTS STORAGE_DATA_MOVEMENT (
    DATA_MOVEMENT_ID        VARCHAR(255)  NOT NULL,
    MOVEMENT_TYPE           VARCHAR(50)   NOT NULL,
    SECURITY_PROTOCOL       VARCHAR(255),
    CREATION_TIME           TIMESTAMP     NULL,
    UPDATE_TIME             TIMESTAMP     NULL,
    CONFIG_JSON             LONGTEXT,
    PRIMARY KEY (DATA_MOVEMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PLAN: execution plans (agent-service)
CREATE TABLE IF NOT EXISTS PLAN (
    PLAN_ID                 VARCHAR(255)  NOT NULL,
    USER_ID                 VARCHAR(255)  NOT NULL,
    GATEWAY_ID              VARCHAR(255)  NOT NULL,
    DATA                    TEXT,
    PRIMARY KEY (PLAN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AGENT_EXECUTION: agent execution records (agent-service)
CREATE TABLE IF NOT EXISTS AGENT_EXECUTION (
    AGENT_EXECUTION_ID      VARCHAR(255)  NOT NULL,
    AGENT_ID                VARCHAR(255),
    AIRAVATA_EXPERIMENT_ID  VARCHAR(255),
    PRIMARY KEY (AGENT_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AGENT_EXECUTION_STATUS: agent execution status tracking (agent-service)
CREATE TABLE IF NOT EXISTS AGENT_EXECUTION_STATUS (
    AGENT_EXECUTION_STATUS_ID VARCHAR(255) NOT NULL,
    AGENT_EXECUTION_AGENT_EXECUTION_ID VARCHAR(255),
    UPDATED_TIME            BIGINT,
    STATUS                  VARCHAR(255),
    ADDITIONAL_INFO         VARCHAR(2000),
    PRIMARY KEY (AGENT_EXECUTION_STATUS_ID),
    CONSTRAINT FK_AES_AE FOREIGN KEY (AGENT_EXECUTION_AGENT_EXECUTION_ID)
        REFERENCES AGENT_EXECUTION (AGENT_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AGENT_DEPLOYMENT_INFO: agent deployment metadata (compute-service)
CREATE TABLE IF NOT EXISTS AGENT_DEPLOYMENT_INFO (
    AGENT_DEPLOYMENT_INFO_ID VARCHAR(255) NOT NULL,
    USER_FRINEDLY_NAME      VARCHAR(255) UNIQUE,
    COMPUTE_RESOURCE_ID     VARCHAR(255),
    AGENT_APPLICATION_ID    VARCHAR(255),
    PRIMARY KEY (AGENT_DEPLOYMENT_INFO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- RESEARCH_PROJECT: research projects (research-service)
CREATE TABLE IF NOT EXISTS RESEARCH_PROJECT (
    ID                      VARCHAR(48)   NOT NULL,
    NAME                    VARCHAR(255)  NOT NULL,
    OWNER_ID                VARCHAR(255)  NOT NULL,
    REPOSITORY_RESOURCE_ID  VARCHAR(48),
    CREATED_AT              TIMESTAMP     NOT NULL,
    UPDATED_AT              TIMESTAMP     NOT NULL,
    STATE                   VARCHAR(255)  NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RP_REPO FOREIGN KEY (REPOSITORY_RESOURCE_ID)
        REFERENCES RESOURCE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PROJECT_DATASET: join table for RESEARCH_PROJECT <-> DATASET_RESOURCE (research-service)
CREATE TABLE IF NOT EXISTS PROJECT_DATASET (
    PROJECT_ID              VARCHAR(48)   NOT NULL,
    DATASET_RESOURCE_ID     VARCHAR(48)   NOT NULL,
    PRIMARY KEY (PROJECT_ID, DATASET_RESOURCE_ID),
    CONSTRAINT FK_PD_PROJECT FOREIGN KEY (PROJECT_ID)
        REFERENCES RESEARCH_PROJECT (ID),
    CONSTRAINT FK_PD_DATASET FOREIGN KEY (DATASET_RESOURCE_ID)
        REFERENCES RESOURCE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- RESOURCE_STAR: user-starred resources (sharing-service)
CREATE TABLE IF NOT EXISTS RESOURCE_STAR (
    ID                      VARCHAR(48)   NOT NULL,
    USER_ID                 VARCHAR(255)  NOT NULL,
    RESOURCE_ID             VARCHAR(48)   NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RS_RESOURCE FOREIGN KEY (RESOURCE_ID)
        REFERENCES RESOURCE (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
