-- Step 1: Make DATA_MOVEMENT_INTERFACE standalone
-- Drop the old composite PK and FK to COMPUTE_RESOURCE
ALTER TABLE DATA_MOVEMENT_INTERFACE DROP FOREIGN KEY FK_DMI_RESOURCE;
ALTER TABLE DATA_MOVEMENT_INTERFACE DROP PRIMARY KEY;

-- Rename COMPUTE_RESOURCE_ID to RESOURCE_ID (generic)
ALTER TABLE DATA_MOVEMENT_INTERFACE CHANGE COLUMN COMPUTE_RESOURCE_ID RESOURCE_ID VARCHAR(255) NOT NULL;

-- Add new PK on just the DM ID + RESOURCE_ID
ALTER TABLE DATA_MOVEMENT_INTERFACE ADD PRIMARY KEY (RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID);

-- Step 2: Migrate STORAGE_INTERFACE data into DATA_MOVEMENT_INTERFACE
INSERT IGNORE INTO DATA_MOVEMENT_INTERFACE (RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID, CREATION_TIME, DATA_MOVEMENT_PROTOCOL, PRIORITY_ORDER, UPDATE_TIME)
SELECT STORAGE_RESOURCE_ID, DATA_MOVEMENT_INTERFACE_ID, CREATION_TIME, DATA_MOVEMENT_PROTOCOL, PRIORITY_ORDER, UPDATE_TIME
FROM STORAGE_INTERFACE;

-- Step 3: Drop the now-redundant STORAGE_INTERFACE table
DROP TABLE IF EXISTS STORAGE_INTERFACE;
