/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef experimentModel_CONSTANTS_H
#define experimentModel_CONSTANTS_H

#include "experimentModel_types.h"



class experimentModelConstants {
 public:
  experimentModelConstants();

  std::string DEFAULT_ID;
  std::string DEFAULT_PROJECT_NAME;
  std::string SINGLE_APP_NODE_NAME;
};

extern const experimentModelConstants g_experimentModel_constants;



#endif
