package org.apache.airavata.registry.cpi;

public enum ChildDataType {
    EXPERIMENT_INPUT,
    EXPERIMENT_OUTPUT,
    WORKFLOW_NODE_DETAIL,
    TASK_DETAIL,
    ERROR_DETAIL,
    APPLICATION_INPUT,
    APPLICATION_OUTPUT,
    NODE_INPUT,
    NODE_OUTPUT,
    JOB_DETAIL,
    DATA_TRANSFER_DETAIL,
    STATUS,
    EXPERIMENT_CONFIGURATION_DATA,
    COMPUTATIONAL_RESOURCE_SCHEDULING,
    ADVANCE_INPUT_DATA_HANDLING,
    ADVANCE_OUTPUT_DATA_HANDLING,
    QOS_PARAM
}