
ALTER TABLE `ENTITY` CHANGE `SHARED_COUNT` `SHARED_COUNT` BIGINT DEFAULT 0;
ALTER TABLE `SHARING` DROP FOREIGN KEY IF EXISTS `SHARING_ibfk_1`;
ALTER TABLE `SHARING` DROP FOREIGN KEY IF EXISTS `SHARING_ibfk_2`;
ALTER TABLE `SHARING` DROP FOREIGN KEY IF EXISTS `SHARING_ibfk_3`;
ALTER TABLE `SHARING` DROP FOREIGN KEY IF EXISTS `SHARING_ibfk_4`;
ALTER TABLE `SHARING` ADD CONSTRAINT `SHARING_PERMISSION_TYPE_ID_DOMAIN_ID_FK` FOREIGN KEY (PERMISSION_TYPE_ID, DOMAIN_ID) REFERENCES PERMISSION_TYPE(PERMISSION_TYPE_ID, DOMAIN_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `SHARING` ADD CONSTRAINT `SHARING_ENTITY_ID_DOMAIN_ID_FK` FOREIGN KEY (ENTITY_ID, DOMAIN_ID) REFERENCES ENTITY(ENTITY_ID, DOMAIN_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `SHARING` ADD CONSTRAINT `SHARING_INHERITED_PARENT_ID_DOMAIN_ID_FK` FOREIGN KEY (INHERITED_PARENT_ID, DOMAIN_ID) REFERENCES ENTITY(ENTITY_ID, DOMAIN_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `SHARING` ADD CONSTRAINT `SHARING_GROUP_ID_DOMAIN_ID_FK` FOREIGN KEY (GROUP_ID, DOMAIN_ID) REFERENCES USER_GROUP(GROUP_ID, DOMAIN_ID) ON DELETE CASCADE ON UPDATE NO ACTION;
