/**
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements. See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership. The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License. You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied. See the License for the
* specific language governing permissions and limitations
* under the License.
*/
package org.apache.airavata.orchestration.util;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.airavata.config.ServerSettings;
import org.apache.airavata.credential.service.CredentialStoreService;
import org.apache.airavata.model.appcatalog.gatewayprofile.proto.StoragePreference;
import org.apache.airavata.model.appcatalog.storageresource.proto.StorageResourceDescription;
import org.apache.airavata.model.credential.store.proto.SSHCredential;
import org.apache.airavata.orchestration.service.RegistryServerHandler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

/**
 * Cold-start initializer that registers a dev SFTP storage resource, SSH credential,
 * and gateway storage preference so the portal Storage page works out of the box.
 *
 * Reads the SSH keypair from conf/sftp/ (generated by Tiltfile on startup).
 * Idempotent: checks if the storage resource already exists before creating.
 */
@Component
public class DevStorageInitializer {

    private static final Logger logger = LoggerFactory.getLogger(DevStorageInitializer.class);

    // The storage-service runs inside the airavata-dind network and reaches the
    // atmoz/sftp container by its compose service name, not "localhost".
    private static final String STORAGE_HOST = "sftp";
    private static final String STORAGE_DESCRIPTION = "Dev SFTP storage (atmoz/sftp container)";
    private static final String SFTP_LOGIN_USER = "airavata";
    private static final String SFTP_FS_ROOT = "/storage";
    private static final String CREDENTIAL_DESCRIPTION = "Dev SFTP";

    @Value("${dev.sftp.private-key-path:conf/sftp/id_rsa}")
    private String privateKeyPath;

    @Value("${dev.sftp.public-key-path:conf/sftp/id_rsa.pub}")
    private String publicKeyPath;

    @Autowired
    private RegistryServerHandler registryHandler;

    @Autowired
    private CredentialStoreService credentialStoreService;

    // Run after DBInitConfig.postInit() creates the default gateway (@Order can't sequence @PostConstruct).
    @EventListener(ApplicationReadyEvent.class)
    public void initialize() {
        try {
            String gatewayId = ServerSettings.getDefaultUserGateway();
            String defaultUser = ServerSettings.getDefaultUser();

            // Check if a storage resource for this host already exists
            var allNames = registryHandler.getAllStorageResourceNames();
            for (var entry : allNames.entrySet()) {
                if (STORAGE_HOST.equals(entry.getValue())) {
                    logger.info("Dev storage resource already exists: {} ({})", entry.getValue(), entry.getKey());
                    return;
                }
            }

            // 1. Register storage resource. Transport is always SFTP; the resource carries the SFTP port directly.
            StorageResourceDescription storageResource = StorageResourceDescription.newBuilder()
                    .setHostName(STORAGE_HOST)
                    .setStorageResourceDescription(STORAGE_DESCRIPTION)
                    .setEnabled(true)
                    .setSftpPort(22)
                    .build();
            String storageResourceId = registryHandler.registerStorageResource(storageResource);
            logger.info("Registered dev storage resource: {} ({})", STORAGE_HOST, storageResourceId);

            // 2. Register SSH credential from Tiltfile-generated keypair
            String privateKey = readKeyFile(privateKeyPath);
            String publicKey = readKeyFile(publicKeyPath);
            if (privateKey == null || publicKey == null) {
                logger.warn(
                        "SSH keypair not found at {} / {} — run 'tilt up' to generate", privateKeyPath, publicKeyPath);
                return;
            }
            SSHCredential sshCredential = SSHCredential.newBuilder()
                    .setUsername(defaultUser)
                    .setGatewayId(gatewayId)
                    .setDescription(CREDENTIAL_DESCRIPTION)
                    .setPrivateKey(privateKey)
                    .setPublicKey(publicKey)
                    .build();
            String credentialToken = credentialStoreService.addSSHCredential(sshCredential);
            logger.info("Registered SSH credential from {} for dev storage: {}", privateKeyPath, credentialToken);

            // 3. Add gateway storage preference
            StoragePreference storagePreference = StoragePreference.newBuilder()
                    .setStorageResourceId(storageResourceId)
                    .setLoginUserName(SFTP_LOGIN_USER)
                    .setFileSystemRootLocation(SFTP_FS_ROOT)
                    .setResourceSpecificCredentialStoreToken(credentialToken)
                    .build();
            registryHandler.addGatewayStoragePreference(gatewayId, storageResourceId, storagePreference);
            logger.info("Added gateway storage preference for dev storage: {}", storageResourceId);

            logger.info("Dev storage cold-start initialization complete");

        } catch (Exception e) {
            logger.warn("Dev storage initialization failed (non-fatal): {}", e.getMessage());
            logger.debug("Dev storage init error details:", e);
        }
    }

    private String readKeyFile(String path) {
        try {
            Path keyPath = Path.of(path);
            if (Files.exists(keyPath)) {
                return Files.readString(keyPath).trim();
            }
        } catch (IOException e) {
            logger.warn("Failed to read key file {}: {}", path, e.getMessage());
        }
        return null;
    }
}
