name: Maven Build

on:
  pull_request:
    branches:
      - master
      - service-layer-improvements
  push:
    branches:
      - master
      - service-layer-improvements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"
      - name: Build and test with Maven
        run: ./mvnw clean install
        working-directory: airavata-api
