name: Style Check

on:
  pull_request:
    branches:
      - master
      - service-layer-improvements
  push:
    branches:
      - master
      - service-layer-improvements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"
      - name: Run Spotless Check
        run: ./mvnw spotless:check
        working-directory: airavata-api
      - name: Run Spotless Apply if Check Fails
        if: failure()
        run: ./mvnw spotless:apply
        working-directory: airavata-api
      - name: Generate Spotless Patch
        if: failure()
        run: |
          git diff > spotless-fixes.patch
      - name: Upload Spotless Patch as Artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: spotless-fixes
          path: spotless-fixes.patch
